### ISSUE TITLE
Operator Helm chart README inappropriately references old chart name

### ISSUE THREAD

**Issue by js8080** [minio/operator#1001]
## Expected Behavior

[The README for the Operator Helm chart](https://github.com/minio/operator/blob/master/helm/operator/README.md) should use the correct chart name (simply `operator`) in the example for "Installing the Chart":
```
helm install \
  --namespace minio-operator \
  --create-namespace \
  operator minio/operator
```

## Current Behavior

It currently refers to the old chart name which was `minio-operator`:
```
helm install \
  --namespace minio-operator \
  --create-namespace \
  minio-operator minio/operator
```

## Possible Solution

Just update the README to refer to the proper chart name.

## Context

I created a Helm chart with the MinIO Operator as a dependency and I referred to it as `minio-operator` and requested version 4.4.4:
```yaml
dependencies:
  - name: minio-operator
    condition: minio-operator.enabled
    version: 4.4.4
    repository: https://operator.min.io/
    alias: minio-operator
```

However, I got an error in Helm when trying to update the dependencies in my chart:
```
Error: can't get a valid version for repositories minio-operator. Try changing the version constraint in Chart.yaml
```

After changing the dependency to just refer to chart `operator`, it worked:
```
dependencies:
  - name: operator
    condition: minio-operator.enabled
    version: 4.4.4
    repository: https://operator.min.io/
    alias: minio-operator
```

## Your Environment

* Version used (`minio-operator`): 4.4.4
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:
