### ISSUE TITLE
Operator fails after deploying Tenant with buckets to create during provisioning

### ISSUE THREAD

**Issue by js8080** [minio/operator#1002]
## Expected Behavior

First I deploy the MinIO Operator via Helm (chart: https://github.com/minio/operator/tree/master/helm/operator) and I am accepting all the default values:
```
helm install minio-operator minio/operator -n minio
```

This results in 2 minio-operator pods running and they seem to be happy.

Next I attempt to deploy a Tenant using Helm (chart: https://github.com/minio/operator/tree/master/helm/tenant) and in this case since the default `values.yaml` is very hard-coded, I override more of those values. Most importantly for this issue, I am attempting to create 2 buckets during provisioning so I have the `buckets` array specified below.

```yaml
## MinIO Tenant Definition
tenants:
  # Tenant name
  - name: minio1
    ## Customize namespace for tenant deployment
    namespace: minio
    ## Specification for MinIO Pool(s) in this Tenant.
    pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
      - servers: 4
        ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
        volumesPerServer: 4
        ## size specifies the capacity per volume
        size: 100Mi  # 2Gi
        ## storageClass specifies the storage class name to be used for this pool
        storageClassName: local-path
        ## Used to specify a toleration for a pod
        tolerations: { }
        ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
        ## eligible to run on a node, the node must have each of the
        ## indicated key-value pairs as labels.
        ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
        nodeSelector: { }
        ## Affinity settings for MinIO pods. Read more about affinity
        ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
        affinity: { }
        ## Configure resource requests and limits for MinIO containers
        resources: { }
        ## Configure security context
        securityContext: { }
        ## Configure topology constraints
        topologySpreadConstraints: [ ]
    ## Mount path where PV will be mounted inside container(s).
    mountPath: /export
    ## Sub path inside Mount path where MinIO stores data.
    subPath: /data
    # pool secrets
    secrets:
      # create a kubernetes secret object with the accessKey and secretKey as defined here.
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
    # pool metrics to be read by Prometheus
    metrics:
      enabled: true
      port: 9000
    certificate:
      ## Use this field to provide one or more external CA certificates. This is used by MinIO
      ## to verify TLS connections with other applications:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCaCertSecret: { }
      ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
      ## TLS for MinIO Tenant pods. Create secrets as explained here:
      ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
      externalCertSecret: { }
      ## Enable automatic Kubernetes based certificate generation and signing as explained in
      ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
      requestAutoCert: false
      ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
      ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
      ## not provided. DNS name format is *.minio.default.svc.cluster.local
      certConfig: { }
    ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
    ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
    s3:
      ## This feature is turned off by default
      bucketDNS: false
    ## List of bucket names to create during tenant provisioning
    buckets:
    - name: "tempo"
    - name: "loki"
```

Ideally, this would deploy the Tenant and create the buckets.

## Current Behavior

Unfortunately, this does not succeed and instead the Tenant pods will appear to be running fine (based on readiness) but it seems they are not fine as `kubectl get tenants -n minio`  shows the state as stuck at `Provisioning default buckets`. This continues on for at least 8 minutes which is about as long as I've waited. After a minute or so, the Operator pods start to error and constantly keep restarting. The error shown in the Operator pods looks like this:

```
$ kubectl logs minio-operator-59fb779c44-xdnw5 -n minio
I0202 21:36:26.627415       1 main.go:71] Starting MinIO Operator
I0202 21:36:27.134091       1 main.go:150] caBundle on CRD updated
I0202 21:36:27.134663       1 main-controller.go:239] Setting up event handlers
I0202 21:36:27.134851       1 leaderelection.go:243] attempting to acquire leader lease minio/minio-operator-lock...
I0202 21:36:27.160652       1 leaderelection.go:253] successfully acquired lease minio/minio-operator-lock
I0202 21:36:27.160851       1 main-controller.go:450] minio-operator-59fb779c44-xdnw5: I've become the leader
I0202 21:36:27.161024       1 main-controller.go:365] Waiting for API to start
I0202 21:36:27.219783       1 main-controller.go:347] Starting HTTPS API server
I0202 21:36:27.220092       1 main-controller.go:369] Starting Tenant controller
I0202 21:36:27.220103       1 main-controller.go:372] Waiting for informer caches to sync
I0202 21:36:27.220110       1 main-controller.go:377] Starting workers
I0202 21:36:27.266626       1 status.go:120] Hit conflict issue, getting latest version of tenant
I0202 21:36:31.843819       1 status.go:120] Hit conflict issue, getting latest version of tenant
E0202 21:36:32.217250       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 155 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x172d5c0, 0xc0004f63a8})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009eaa40})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x75
panic({0x172d5c0, 0xc0004f63a8})
        runtime/panic.go:1038 +0x215
github.com/minio/operator/pkg/apis/minio.min.io/v2.(*Tenant).NewMinIOUserForAddress(0xc000d5a700, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000cb0900, 0x23a, 0x23b})
        github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:715 +0x431
github.com/minio/operator/pkg/apis/minio.min.io/v2.(*Tenant).NewMinIOUser(...)
        github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:703
github.com/minio/operator/pkg/controller/cluster.(*Controller).createBuckets(0xc0004c6360, {0x1a502d8, 0xc00009e000}, 0xc000d5a700, 0x0)
        github.com/minio/operator/pkg/controller/cluster/operator.go:328 +0x1fd
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0004c6360, {0xc0009afb30, 0xc})
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:1278 +0x4a8a
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x15b88a0, 0xc0009eaa40})
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:543 +0x245
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0004c6360)
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:555 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:495 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ff3dced4da0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000628990, {0x1a237e0, 0xc000791d10}, 0x1, 0xc00008b500)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0xc00075cca0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:380 +0x2dd
E0202 21:36:32.217353       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 155 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x172d5c0, 0xc0004f63a8})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4dcc74})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:48 +0x75
panic({0x172d5c0, 0xc0004f63a8})
        runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009eaa40})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x172d5c0, 0xc0004f63a8})
        runtime/panic.go:1038 +0x215
github.com/minio/operator/pkg/apis/minio.min.io/v2.(*Tenant).NewMinIOUserForAddress(0xc000d5a700, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000cb0900, 0x23a, 0x23b})
        github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:715 +0x431
github.com/minio/operator/pkg/apis/minio.min.io/v2.(*Tenant).NewMinIOUser(...)
        github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:703
github.com/minio/operator/pkg/controller/cluster.(*Controller).createBuckets(0xc0004c6360, {0x1a502d8, 0xc00009e000}, 0xc000d5a700, 0x0)
        github.com/minio/operator/pkg/controller/cluster/operator.go:328 +0x1fd
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0004c6360, {0xc0009afb30, 0xc})
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:1278 +0x4a8a
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x15b88a0, 0xc0009eaa40})
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:543 +0x245
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0004c6360)
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:555 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:495 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ff3dced4da0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000628990, {0x1a237e0, 0xc000791d10}, 0x1, 0xc00008b500)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0xc00075cca0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:380 +0x2dd
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 155 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x4dcc74})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x172d5c0, 0xc0004f63a8})
        runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0009eaa40})
        k8s.io/apimachinery@v0.20.2/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x172d5c0, 0xc0004f63a8})
        runtime/panic.go:1038 +0x215
github.com/minio/operator/pkg/apis/minio.min.io/v2.(*Tenant).NewMinIOUserForAddress(0xc000d5a700, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xc000cb0900, 0x23a, 0x23b})
        github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:715 +0x431
github.com/minio/operator/pkg/apis/minio.min.io/v2.(*Tenant).NewMinIOUser(...)
        github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:703
github.com/minio/operator/pkg/controller/cluster.(*Controller).createBuckets(0xc0004c6360, {0x1a502d8, 0xc00009e000}, 0xc000d5a700, 0x0)
        github.com/minio/operator/pkg/controller/cluster/operator.go:328 +0x1fd
github.com/minio/operator/pkg/controller/cluster.(*Controller).syncHandler(0xc0004c6360, {0xc0009afb30, 0xc})
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:1278 +0x4a8a
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem.func1({0x15b88a0, 0xc0009eaa40})
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:543 +0x245
github.com/minio/operator/pkg/controller/cluster.(*Controller).processNextWorkItem(0xc0004c6360)
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:555 +0x62
github.com/minio/operator/pkg/controller/cluster.(*Controller).runWorker(0x0)
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:495 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ff3dced4da0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000628990, {0x1a237e0, 0xc000791d10}, 0x1, 0xc00008b500)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0xc00075cca0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:90 +0x25
created by github.com/minio/operator/pkg/controller/cluster.(*Controller).Start.func1
        github.com/minio/operator/pkg/controller/cluster/main-controller.go:380 +0x2dd
```

The logs for Tenant pod look like this:
```
$ kubectl logs minio1-ss-0-0 -n minio

 You are running an older version of MinIO released 3 weeks ago
 Update:
Run `mc admin update`



API: SYSTEM()
Time: 21:35:30 UTC 02/02/2022
Error: Marking http://minio1-ss-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export1/data/v43 temporary offline; caused by Post "http://minio1-ss-0-2.minio1-hl.minio.svc.cluster.local:9000/minio/storage/export1/data/v43/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup minio1-ss-0-2.minio1-hl.minio.svc.cluster.local on 10.43.0.10:53: no such host (*fmt.wrapError)
       6: internal/rest/client.go:149:rest.(*Client).Call()
       5: cmd/storage-rest-client.go:152:cmd.(*storageRESTClient).call()
       4: cmd/storage-rest-client.go:520:cmd.(*storageRESTClient).ReadAll()
       3: cmd/format-erasure.go:406:cmd.loadFormatErasure()
       2: cmd/format-erasure.go:326:cmd.loadFormatErasureAll.func1()
       1: internal/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```

Now if I comment out the buckets in my values.yaml and re-deploy the Tenant, everything works fine. I am able to tunnel into the console UI and add the buckets I need myself. However, as part of a scripted deployment, I want the buckets to be defined for me automatically.

## Steps to Reproduce (for bugs)

See above.

## Context

I cannot seem to create buckets during Tenant deployment.

## Your Environment

* Version used (`minio-operator`): 4.4.5
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes (K3s): v1.22.5+k3s1
* Server type and version:
* Operating System and version (`uname -a`): Linux k8s-poc-mgmt01 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file: See above

**Comment by harshavardhana** [comment]
> github.com/minio/operator/pkg/apis/minio.min.io/v2/helper.go:715 +0x431

This crash is because your user credentials secret is empty.

**Comment by js8080** [comment]
@harshavardhana hmmm! That is specified in the default values.yaml (https://github.com/minio/operator/blob/master/helm/tenant/values.yaml):
```
    secrets:
      # create a kubernetes secret object with the accessKey and secretKey as defined here.
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
```

Is that the same credential secret you're referring to?

**Comment by harshavardhana** [comment]
No sir @js8080 this should be part of `spec.users` section.  https://github.com/minio/operator/blob/master/helm/tenant/templates/tenant.yaml#L90

So to create buckets its expecting that you also have normal users, not just the root credentials.

**Comment by harshavardhana** [comment]
this shouldn't be a requirement but its a workaround so if you have `users:` in values.yaml it will not crash.

**Comment by js8080** [comment]
Thank you -- that did the trick... For others reference, I created a secret like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-user
  namespace: minio
type: Opaque
data:
  CONSOLE_ACCESS_KEY: bWluaW8tZ2VuZXJhdGVkLXVzZXIK
  CONSOLE_SECRET_KEY: amprZGpzZGpoSlVJSVVJSVVVSVVJVUkzNDM0MzQzNDM0M0RTRFM9Cg==
```

And then in my values.yaml:
```yaml
      ## List of bucket names to create during tenant provisioning
      buckets:
      - name: "tempo"
      - name: "loki"
      ## List of secret names to use for generating MinIO users during tenant provisioning
      users:
      - name: "minio-user"
```

It seems the Tenant chart could be updated to allow more easily creating these users. Should this issue be kept open for that?

**Comment by saikiran2603** [comment]
@js8080 how are you applying the values file ? I am trying to override the values by creating the values file locally and applying it via , 
` kubectl apply -f minio-tenant.yaml`

But i get below error 
`error: error validating "./deployment-files/minio-tenant.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

i am unable to find a way to change / override the default values , either via kubectl  or helm ..

**Comment by js8080** [comment]
> @js8080 how are you applying the values file ? I am trying to override the values by creating the values file locally and applying it via , ` kubectl apply -f minio-tenant.yaml`
> 
> But i get below error `error: error validating "./deployment-files/minio-tenant.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`
> 
> i am unable to find a way to change / override the default values , either via kubectl or helm ..

Except for the secret I posted in my last post, I am deploying MinIO with Helm. Basically I'm doing it as described on the MinIO Operator README: https://github.com/minio/operator/tree/master/helm/operator

Unfortunately, the [Tenant Helm chart default values file](https://github.com/minio/operator/blob/master/helm/tenant/values.yaml) is all hard-coded and is not templatized so I basically copy that entire file, change what I want in there, and then pass it Helm during install / upgrade:
```
helm install minio-tenant minio/tenant -n minio --values minio-tenant.values.yaml
```

Beware the Tenant values file also hard-codes the namespace to `default` so if you want it to install to another namespace (e.g. `minio`), you have to change that in your override values file.

**Comment by cniackz** [comment]
Just confirming, no need to provide the secret in `users`, all is needed is the bucket list, example:

```yaml
  ## List of bucket names to create during tenant provisioning
  buckets:
    - name: "cesar"
  ## List of secret names to use for generating MinIO users during tenant provisioning
  users: [ ]
```

> and you will get these type of messages, first:

```
I0403 20:42:52.613318       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"tenant-ns", Name:"myminio", UID:"106dce33-d775-43a1-baab-a62fd6b5b9a6", APIVersion:"[minio.min.io/v2](http://minio.min.io/v2)", ResourceVersion:"2204", FieldPath:""}): type: 'Warning' reason: 'BucketsCreatedFailed' Buckets creation failed: Server not initialized, please try again.
```

That is expected, and information message because MinIO takes some time to get all pods up and running, once all pods are ready, you will get:

```
I0403 20:43:52.576800       1 helper.go:755] Successfully created bucket cesar
```

And if you check into the tenant you will see the bucket right after the tenant is deployed:


![image](https://user-images.githubusercontent.com/6667358/229628925-0be90b49-be7e-44d4-9883-57c4375e1fee.png)
