### ISSUE TITLE
Allow specifying bucket lifecycle when creating buckets as part of deployment

### ISSUE THREAD

**Issue by js8080** [minio/operator#1010]
**Is your feature request related to a problem? Please describe.**
MinIO has the ability to configure bucket lifecycles to "setup automatic deletion of objects after a specified number of days or a specified date": https://docs.min.io/docs/minio-bucket-lifecycle-guide.html

When deploying MinIO Tenants, the Operator does not seem to support settings for this lifecycle concept. From the [tenants spec](https://github.com/minio/operator/blob/master/manifests/4.4.7/minio.min.io_tenants.yaml), the `buckets` array is defined as:
```yaml
              buckets:
                items:
                  properties:
                    name:
                      type: string
                    objectLock:
                      type: boolean
                    region:
                      type: string
                  type: object
                type: array
```

**Describe the solution you'd like**
I'd like to be able to specify lifecycle settings as part of my deployment. For example, I want to create a bucket where items older than 7 days get deleted automatically.

**Describe alternatives you've considered**
One can manually configure their bucket lifecycle settings but requiring manual configuration steps post-deployment is undesirable when you are aiming for a fully scripted deployment approach.
