### ISSUE TITLE
monitor tenant from external prometheus instance

### ISSUE THREAD

**Issue by x3nb63** [minio/operator#1168]
**Is your feature request related to a problem? Please describe.**

I have a Prometheus instance running in the cluster, so I don't want the tenants to run their own prometheus pod each - and I disabled that.

Now I want my clusters prometheus just find all tenant pods by annotations. (I can accept the tenant consoles not showing metrics)

**Describe the solution you'd like**

some way of having the pods (actually the StatefulSets created by the operator)  contain this:

```
  metadata:
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/scheme: http
      prometheus.io/port: '9000'
  env:
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: public
```

**Additional context**

I partially achieved the above by `kubectl edit tenant/mytenant` and it accepts the `env:` part (which is active, as I can curl metrics w/o authorization header). But it does not accept `metadata:` or `annotations:`.

Also I assume when editing the tenant using Operator UI the `env:` change will disappear, right?

(in general the above reads a lot like #1151)
