### ISSUE TITLE
Improve documentation/values for disabling Prometheus & logging

### ISSUE THREAD

**Issue by OvervCW** [minio/operator#1191]
**Is your feature request related to a problem? Please describe.**
Right now you need to disable Prometheus and logging by setting their disk capacity to false:

```yaml
tenant:
  ...

  prometheus:
    diskCapacityGB: false

  log:
    audit:
      diskCapacityGB: false
```

This doesn't appear to be documented anywhere, so I had to read through the Helm chart itself to find out about this.

**Describe the solution you'd like**
I would expect there to be a simple "enabled" field for each of these so that the values become:

```yaml
tenant:
  ...

  prometheus:
    enabled: false

  log:
    enabled: false
```

**Describe alternatives you've considered**
The values could either include an `enabled` boolean or the behavior of `diskCapacityGB: false` could at least be documented somewhere.
