### ISSUE TITLE
Remove inheritance of some labels

### ISSUE THREAD

**Issue by aivanov-citc** [minio/operator#1230]
Hi! We use the Flux system to deliver the configuration to the GitOps cluster. The system marks its controlled resources with labels. Only those resources that are in the cluster configuration repository should be monitored.

In the case of minio, these are custom tenant resources, but not statefulsets generated by the operator.

Please add the ability to exclude labels when inheriting from a tenant in a statefulset, for example, using a regular expression, as implemented in the kafka operator
```yaml
containers:
  - name: strimzi-cluster-operator
    env:
      - name: STRIMZI_LABELS_EXCLUSION_PATTERN
        value: "^kustomize.toolkit.fluxcd.*"
```
