### ISSUE TITLE
OpenShift MinIO Operator "remote error: tls: bad certificate"

### ISSUE THREAD

**Issue by DannnIT** [minio/operator#1234]
The MinIO Operator available in the OpenShift OperatorHub appears to install successfully (Status = Succeeded under installed operators); however, logs show persistent TLS certificate errors. Tenant creations also fail and cause a spike in the same cert errors.

## Expected Behavior

A successful operator install followed by creation of a tenant with no TLS cert errors.

## Current Behavior

Installing the operator on a new OpenShift cluster immediately results in the following error in the minio-operator pod logs:

_2022/08/10 14:30:03 http: TLS handshake error from 10.128.0.1:54964: remote error: tls: bad certificate_

The kube-apiserver pod logs show the following error:

_E0810 14:47:19.080525 16 cacher.go:424] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.openshift-operators.svc:4222/webhook/v1/crd-conversion?timeout=30s": x509: certificate is valid for operator, operator.openshift-operators.svc, operator.openshift-operators.svc.cluster.local, not minio-operator-service.openshift-operators.svc; reinitializing..._

_W0810 14:47:20.091456 16 reflector.go:324] storage/cacher.go:/minio.min.io/tenants: failed to list minio.min.io/v1, Kind=Tenant: conversion webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://minio-operator-service.openshift-operators.svc:4222/webhook/v1/crd-conversion?timeout=30s": dial tcp 10.131.0.36:4222: connect: connection refused_

It looks like two TLS secrets were created in the openshift-operators namespace. Here are some of their details returned by openssl:
- operator-tls was issued by kube-csr-signer_@16599504 and contains the following SANs
  - DNS:operator
  - DNS:operator.openshift-operators.svc
  - DNS:operator.openshift-operators.svc.cluster.local
- minio-operator-service-cert was issued by Red Hat, Inc. and contains the following SANs
  - DNS:minio-operator-service.openshift-operators
  - DNS:minio-operator-service.openshift-operators.svc

## Possible Solution

Hopefully something simple we overlooked.

## Steps to Reproduce (for bugs)

1. Install OpenShift 4.10.0 on local ESXi host.
2. From the OperatorHub, install the MinIO Operator.
3. Check the minio-operator pods logs for the error "remote error: tls: bad certificate"

## Regression

Not sure.

## Your Environment

* Version used (`minio --version`): 4.4.25
* Server setup and configuration: OpenShift v4.10.0 on ESXi
* Operating System and version (`uname -a`): RHEL CoreOS/Linux clusterb-5ncj2-worker-mp4h8 4.18.0-305.49.1.el8_4.x86_64 minio/minio#1 SMP Wed May 11 09:47:48 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dvaldivia** [comment]
seems like we get installed to a different namespace and issued a certificate for that ns as well, so perhaps our openshift configuration should expect that and pick it up @Alevsk

**Comment by Alevsk** [comment]
@dvaldivia the problem is the operator service name
@DannnIT did you changed the service name from `operator` to `minio-operator-service`? that is not supported, the service name for operator must be `operator`, the error here is very clear

```
certificate is valid for operator, operator.openshift-operators.svc, operator.openshift-operators.svc.cluster.local, not minio-operator-service.openshift-operators.svc
```

**Comment by DannnIT** [comment]
@Alevsk No, that is the default name it is using. Initial attempts to redefine the name to `operator` were unsuccessful. I will see if I can make that work though.

**Comment by cniackz** [comment]
Hello @DannnIT 

After dealing with this for some time, I found a way to solve this problem in OpenShift version 4.11.0
It is similar to what it is observed at: https://gist.github.com/nmasse-itix/60c2369821171352098364e1ae0f51f6
And what I did locally was:

1. Delete all `Services` under Operator's Namespace
2. Delete all `Secrets` under Operator's Namespace
3. Delete all `Pods` under Operator's Namespace
4. Secrets and Pods will be regenerated or recreated from the Deploy
5. But services need to be created after deletion, nevertheless, notice I am adding an annotation here `service.alpha.openshift.io/serving-cert-secret-name: operator-tls`, as explained in https://docs.openshift.com/container-platform/3.9/dev_guide/secrets.html#service-serving-certificate-secrets:

* File: `operator-service.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  name: operator # Please do not change this value
  labels:
    name: minio-operator
  namespace: minio-operator
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: operator-tls
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: https
    - port: 4221
      name: http
  selector:
    name: minio-operator
    operator: leader
```

* File: `console-service.yaml`

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: console
  namespace: minio-operator
  name: console
spec:
  ports:
    - name: http
      port: 9090
    - name: https
      port: 9443
  selector:
    app: console
```

> To apply them do this:

```sh
oc apply -f ~/operator-service.yaml
oc apply -f ~/console-service.yaml
```

In the next iteration on the different catalogs, I will add this annotation by default.
