### ISSUE TITLE
"helm install minio/tenant" raises a prometheusOperator validation error

### ISSUE THREAD

**Issue by flypenguin** [minio/operator#1243]
I try to install a super minimal minio-tenant after installing the operator using basically this commandline:

```bash
# values file see below.
helm install -n minio-tenant-default -f values.yaml minio-tenant-default minio/tenant
```

## Expected Behavior
the helm chart is installed correctly.

## Current Behavior
a `ValidationError` is thrown:

```
Error: unable to build kubernetes objects from release manifest:
error validating "": 
error validating data: [
  ValidationError(Tenant.spec):
  unknown field "features" in io.min.minio.v2.Tenant.spec,
    ValidationError(Tenant.spec.prometheusOperator):
  invalid type for io.min.minio.v2.Tenant.spec.prometheusOperator:
  got "boolean", expected "map"
]
```

## Possible Solution
better documentation? or fix the bug if it is one :)

## Steps to Reproduce (for bugs)
1. install operator with `helm install -n minio-operator minio/operator`
2. install tenant as described above

## Context
Trying to install a minimal minio tenant on a single node cluster.

## Regression
No idea.

## Your Environment
* Version used (`minio-operator`): 4.3.7 (chart version)
* Version used (`minio-tenant`): 4.4.28 (chart version)
* Environment name and version (e.g. kubernetes v1.17.2): k3s v1.24.3+k3s1
* Server type and version: Hetzner VM
* Operating System and version (`uname -a`): `Linux test-cluster-1 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your deployment file: n/a

## values.yaml

```yaml
secrets:
  name: minio-tenant-default
  accessKey: minio
  secretKey: minio123

tenant:
  name: default

  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      size: 5Gi

      ## rancher "local-path" storage has bindingMode "waitForFirstConsumer", so cool
      storageClassName: local-path
```
