### ISSUE TITLE
affinity key gets rendered twice making the manifest invalid to apply

### ISSUE THREAD

**Issue by glotzerhotze** [minio/operator#1271]
We are trying to use a values.yaml file that defines a nodeAffinity only - see the values.yaml file provided.
Upon rendering the manifest via `helm template minio minio/operator --values values.yaml` the generated operator deployment manifest will have *two* keys named `affinity` - one will hold the nodeAntiAffinity that we did NOT put into the values.yaml file - the other key will hold the nodeAffinity that we declared in the values.yaml file.

## Expected Behavior
The operator deployment manifest is rendered correctly - the current version won't apply to the cluster as there are two identical keys defined.

## Current Behavior
Current behaviour renders two keys with the name `affinity` - thus breaking the operator manifest as it won't apply to the cluster.

## Possible Solution
Fix the helm-template - or make it clear in the documentation that you have to declare BOTH affinity settings for this to work correctly. Currently this is a very time-consuming trial&error process to get it correct.

## Steps to Reproduce (for bugs)

Use this values.yaml file: 

```
operator:
  ## Setup environment variables for the Operator
  env:
    - name: MINIO_OPERATOR_TLS_ENABLE
      value: "on"
    - name: CLUSTER_DOMAIN
      value: "cluster.local"
  replicaCount: 1
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gini.net/operator-home
                operator: In
                values:
                  - true
  tolerations:
    - operator: Exists
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

console:
  replicaCount: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: name
                operator: In
                values:
                  - minio-operator
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: gini.net/operator-home
                operator: In
                values:
                  - true
  tolerations:
    - operator: Exists
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-external
      nginx.ingress.kubernetes.io/force-ssl-redirect: true
    host: minio-operator-console.i.gini.net
    path: /
    pathType: Prefix
```

template the manifests via `helm template minio minio/operator --values values.yaml` 

try to apply the rendered manifests - watch it break with the operator deployment manifest

## Context
We tried to apply the manifest with flux and it would fail.

## Regression
I have no clue - have not used other versions besides v4.4.28 so far

## Your Environment
* Version used (`minio-operator`): v4.4.28 (latest as of now)
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.20.13
* Server type and version: bare-metal machines in a datacenter
* Operating System and version (`uname -a`): debian buster
* Link to your deployment file:
