### ISSUE TITLE
[log-search-api] CrashLoopBack - Error connecting to db: pq: password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by pjamenaja** [minio/operator#1275]
## Steps to Reproduce (for bugs)

1. Create MinIO tenant as usual by YAML below, actually I used helm chart version 4.4.28 to render the tenant manifest.
```yml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  labels:
    app: minio
  name: minio-soc
  namespace: minio-soc
spec:
  configuration:
    name: minio-admin-secret
  credsSecret:
    name: tenant-secret
  features:
    bucketDNS: false
  image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
  imagePullPolicy: IfNotPresent
  log:
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    audit:
      diskCapacityGB: 1
    db:
      affinity:
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      image: ""
      initimage: ""
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      serviceAccountName: ""
      tolerations: []
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: longhorn
    image: ""
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: ""
    tolerations: []
  logging:
    anonymous: true
    json: true
    quiet: true
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - name: pool-0
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: longhorn
    volumesPerServer: 4
  prometheus:
    affinity:
      nodeAffinity: {}
      podAffinity: {}
      podAntiAffinity: {}
    diskCapacityGB: 1
    image: ""
    initimage: ""
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: ""
    sidecarimage: ""
    storageClassName: longhorn
  prometheusOperator: false
  requestAutoCert: true
  subPath: /data
```
2. Delete the tenant using command `kubectl delete tenant minio-soc -n minio-soc`.
3. Create tenant again with the same manifest above, every pods started successfully except `log-search-api`  with error shown below.
> Error connecting to db: pq: password authentication failed for user "postgres"

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:
