### ISSUE TITLE
update to exposeServices after tenant creation doesn't have effect

### ISSUE THREAD

**Issue by pjuarezd** [minio/operator#1312]
## Expected Behavior

When we update the exposeServices flags to false, the services type should change to **ClusterIP**.

## Current Behavior

During creation of a tenant that have exposed services (see tenant manifest below), it creates the services as type **LoadBalancer**, which is a correct and desired result.

```yaml
...
spec:
  exposeServices:
    console: true
    minio: true
...
```

However, when we update the flags to false, the services are not updated to type **ClusterIP**.

## Possible Solution

Probably Operator is only recognizing the flags on creation time and ignore them on sync time, triage would find if the flag is ignored, or operator fails to execute the change for some reason.

## Steps to Reproduce (for bugs)

1. Create a tenant on Operator UI
2. Set the flags `exposeServices.console: true`, `exposeServices.minio=true`
3. Vrify the services `minio` and `namespace-console` are of type **LoadBalancer**
4. Edit the tenant on Operator UI
5. Set the flags `exposeServices.console: false`,`exposeServices.minio=false`
6. Verify the services `minio` and `namespace-console` have not changed from **LoadBalancer** to **ClusterIP**

## Regression
No

## Your Environment

* Version used (`minio-operator`): 4.5.2
* Environment name and version (e.g. kubernetes v1.17.2): 1.20
* Server type and version:
* Operating System and version (`uname -a`): `Linux minio-tenant-1-pool-0-0 #redacted#.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your deployment file:

```yaml
metadata:
  generation: 4
  name: minio-tenant-1
  namespace: minio-tenant-1
scheduler:
  name: ""
spec:
  configuration:
    name: minio-tenant-1-env-configuration
  credsSecret:
    name: minio-tenant-1-secret
  exposeServices:
    console: true
    minio: true
  features: {}
  image: minio/minio:RELEASE.2022-10-08T20-11-00Z
  imagePullSecret: {}
  log:
    audit:
      diskCapacityGB: 5
    db:
      resources: {}
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: Always
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          name: minio-tenant-1-log
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: "5368709120"
        status: {}
    resources: {}
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: Always
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - minio-tenant-1
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-0
          topologyKey: kubernetes.io/hostname
    name: pool-0
    resources:
      requests:
        cpu: "2"
        memory: 7Gi
    servers: 4
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "274877906944"
        storageClassName: gp2
      status: {}
    volumesPerServer: 1
  prometheus:
    diskCapacityGB: 5
    resources: {}
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: Always
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
  requestAutoCert: true
  users:
  - name: minio-tenant-1-user-0
```
