### ISSUE TITLE
How does this line work without .Values ?

### ISSUE THREAD

**Issue by rufreakde** [minio/operator#1342]
Hi colleagues,

we try to store the root secret in a k8ssecret but it seems to me that there is a flaw in the helm chart:
https://github.com/minio/operator/blob/711f93bac4e49515fe7e42b381e7ffd75ef8cf01/helm/tenant/templates/tenant.yaml#L30

Our Tenant values:
```yaml
        configuration:
          name: minio-access-secret
```

Our secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-access-secret
  namespace: up-monitoring
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="test"
    export MINIO_ROOT_PASSWORD="test123"
```

No pod has the ENV MINIO_ROOT_USER exposed and also no pod has MINIO_ROOT_PASSWORD. 

Should it not be?:
```
  ## Secret with default environment variable configurations
  configuration:
    name: {{ .Values.configuration.name }}
```

**Comment by dnskr** [comment]
Non of properties in `tenant.yaml` have `.Values` prefix because `with` is used to specify a scope:
```
{{- with .Values.tenant }}
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .name }}
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
...
```

The secret property `config.env` mounted to minio pods as file `/tmp/minio-config/config.env`.
