### ISSUE TITLE
Openshift 4: failed to create users using tenant cr

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [minio/operator#1345]
## Expected Behavior

Minio sever installation should be successfull and should be availiable server with pre-created user with name `storage`.

## Current Behavior
Installation S3 minio server interrupted with an error:

## Possible Solution
Delete section with user creation, then you will get working minio server, but only with admin.

## Steps to Reproduce (for bugs)
I recorded small video with reproduction https://youtu.be/suERTx-_JPA

1. Install minio operator using Openshift ui or subscription:

```yaml
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: minio-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: minio-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
```

2. Create tenant cr and use another parts from https://github.com/minio/operator/tree/v4.5.4/examples/kustomization/base:

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: storage
  namespace: minio-tenant
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  exposeServices:
    console: true
    minio: true
  features:
    bucketDNS: false
    domains: { }
  users:
    - name: storage-user
  certConfig: { }
  podManagementPolicy: Parallel
  configuration:
    name: storage-configuration
  env: [ ]
  serviceMetadata:
    minioServiceLabels: { }
    minioServiceAnnotations: { }
    consoleServiceLabels: { }
    consoleServiceAnnotations: { }
  priorityClassName: ""
  externalCaCertSecret: [ ]
  externalCertSecret: [ ]
  externalClientCertSecrets: [ ]
  image: quay.io/minio/minio:RELEASE.2022-09-17T00-09-45Z
  imagePullSecret: { }
  mountPath: /export
  subPath: ""
  serviceAccountName: ""
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 2
      nodeSelector: { }
      tolerations: [ ]
      affinity:
        nodeAffinity: { }
        podAffinity: { }
        podAntiAffinity: { }
      resources: { }
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: { }
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: { }
      securityContext: {}
  requestAutoCert: true
```

## Regression
I didn't use minio before v4.5.4, so I don't know if that's regression.

## Your Environment

* Version used (`minio-operator`): v4.5.2
* Environment name and version:  Openshift v4.11.7
* Server type and version:

* Operating System and version (`uname -a`):
Darwin Oleksandrs-MacBook-Pro 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64 i386 Darwin
* Link to your deployment file:
