### ISSUE TITLE
[Helm] Renovate doesnt work with minio operator

### ISSUE THREAD

**Issue by teimyBr** [minio/operator#1351]
```
apiVersion: v2
name: minio-operator
version: 0.0.0
dependencies:
- name: minio-operator
  version: 4.3.7
  repository: https://operator.min.io/
```

Renovate goes to this URL = https://operator.min.io/index.yaml 

and there is no newer version as 4.3.7 

## Expected Behavior
renovate good handle minio operator updates
 
Renovate Updates minio to latest

## Steps to Reproduce (for bugs)

1. setup Minio Operator Repo 
2. add Renovate 
3. Renovate doenst find any new version as 4.3.7

## Your Environment
renovate latest 
minio operator 4.3.7

**Comment by alfsch** [comment]
Same behavior for us, we configured this months ago and I already wondered why we don't get update requests.

**Comment by dvaldivia** [comment]
I belive part of the problem is that we split the chat from a single chart with Operator+Tenant to a two charts setup, one for operator and one for tenant, thus the chart `minio-operator` no longer exists, only `operator` and `tenant`, we'll fix this to point to the latest operator chart, but I'm not sure if the upgrade is going to be trivial for users of the older chart.

**Comment by allanrogerr** [comment]
@teimyBr 

1. What is the value of the field "operator.image.repository" and the field "operator.image.tag" in the file helm/operator/values.yaml?
2. How are you running renovate? e.g. thru the github app
3. Please provide your renovate.json, and a spool of the latest renovate log if possible.

**Comment by teimyBr** [comment]
Logs look normal says that it dont find any newer version then 4.3.7 

We running Renovate via Azure DevOps Pipeline.

this is our values.yaml. 
```
minio-operator:
  # we only want to install operator
  tenants: {}
  operator:
    env:
    - name: MINIO_OPERATOR_TLS_ENABLE
      value: "off"
    - name: CLUSTER_DOMAIN
      value: "cluster.local"
```
Maybe have had to add there "operator.image.repository" and the field "operator.image.tag" ? 

Or this is as @dvaldivia write, that the chart has changed ? 

renovate config in the repo. we have no specific config for helm for other things this works quite well. 
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json"
}
```

**Comment by allanrogerr** [comment]
@teimyBr After 4.3.7 the Helm setup was split into two directory structures; one for operator and console; the other for tenant. 

As you correctly mentioned, adding the field "operator.image.repository" and the field "operator.image.tag" will allow renovate to find newer versions of operator e.g.
```
minio-operator:
  # we only want to install operator
  tenants: {}
  operator:
    env:
    - name: MINIO_OPERATOR_TLS_ENABLE
      value: "off"
    - name: CLUSTER_DOMAIN
      value: "cluster.local"
    image:
      repository: minio/operator
      tag: v4.3.8
```
