### ISSUE TITLE
features domain broken on Tenant helm chart

### ISSUE THREAD

**Issue by Rid** [minio/operator#1354]
## Expected Behavior
MINIO_DOMAIN to be set correctly

## Current Behavior
```
        - name: MINIO_DOMAIN
          value: ','
```

## Steps to Reproduce (for bugs)
```
spec:
  features:
    ## Specify a list of domains used to access MinIO and Console
    domains:
      minio:
        - domain1.minio
        - domain2.minio
```

## Context
@dvaldivia I'm using the latest helm version with 

```
spec:
  features:
    ## Specify a list of domains used to access MinIO and Console
    domains:
      minio:
        - domain1.minio
        - domain2.minio
```

However the statefulset has:

```
        - name: MINIO_DOMAIN
          value: ','
```

The statefulset pods fail with:

```
{"level":"FATAL","errKind":"","time":"2022-11-24T19:46:20.079437507Z","message":"unexpected scheme found ","error":{"message":"unexpected scheme found ","source":["cmd/server-main.go:215:cmd.serverHandleEnvVars()"]}}
```

## Regression
Yes

## Your Environment
Latest helm operator & tenant charts

Fix: https://github.com/minio/operator/pull/1378

**Comment by harshavardhana** [comment]
Feel free to send a fix @Rid

**Comment by allanrogerr** [comment]
@Rid This issue is due to the way URLs are parsed by golang. Since there is no slash after the scheme in your example domains (there is actually no scheme), they are parsed in the following way "scheme:opaque[?query][#fragment]" resulting in empty domains (see https://pkg.go.dev/net/url#URL).

A workaround is to add a scheme to your domains, while a permanent fix is analyzed e.g.
```
spec:
  features:
    ## Specify a list of domains used to access MinIO and Console
    domains:
      minio:
        - **https://**domain1.minio
        - **https://**domain2.minio
```

Please let me know your thoughts.
