### ISSUE TITLE
expose MinIO console via Traefik

### ISSUE THREAD

**Issue by kamikaze** [minio/operator#1356]
Hi. I failed looking for any docs on how to expose minio console / tenant api via Traefik. Is there any? Thanks

**Comment by kamikaze** [comment]
It's IngressRoute, but it's manual addition... would be nice to exclude manual steps :)

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tenant1-console-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`host.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: tenant1-console
      port: 9090

```
