### ISSUE TITLE
Support loadBalancerIP and externalTrafficPolicy values for exposeServices

### ISSUE THREAD

**Issue by RomanKrasavtsev** [minio/operator#1357]
Currently there is no option to specify loadBalancerIP and externalTrafficPolicy values for exposeServices
https://github.com/minio/operator/blob/master/helm/tenant/values.yaml#L110

`Some cloud providers allow you to specify the loadBalancerIP. In those cases, the load-balancer is created with the user-specified loadBalancerIP.`
https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

`You can set the spec.externalTrafficPolicy field to control how traffic from external sources is routed. Valid values are Cluster and Local. Set the field to Cluster to route external traffic to all ready endpoints and Local to only route to ready node-local endpoints. If the traffic policy is Local and there are no node-local endpoints, the kube-proxy does not forward any traffic for the relevant Service.`
https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy

**Describe the solution you'd like**
```yaml
exposeServices:
  console: false
  minio: true
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.10
```

**Comment by dvaldivia** [comment]
the challenge here is that we would need to migrate people from the boolean value to an object value, so I think something along the lines of the following might be the way.
```yaml
exposeServices:
  console: false
  minio: true
  minioMeta:
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.1.10
```
