### ISSUE TITLE
Allow configuration of probes for created containers in Helm chart

### ISSUE THREAD

**Issue by djessich** [minio/operator#1367]
**Is your feature request related to a problem? Please describe.**
Probes cannot be configured when deployed with Helm, although each container should have a liveness, readyness and startup probe configured to conform to Kubernetes best practices.

**Describe the solution you'd like**
Please allow configuration of probes and provide a reasonable default. This should be available for all created containers.

**Describe alternatives you've considered**
Currently there is no possibility to configure probes.

**Additional context**
Each container should have a liveness, readiness and startup probe configured to conform to current Kubernetes best practices. Currently this chart does not support this feature.

**Comment by cniackz** [comment]
Synced with Allan on this, and we discovered that `liveness` and `readiness` is already implemented, all you need to do is add that into the values:

File: operator/helm/tenant/values.yaml
Content:
```yaml
  # Liveness Probe for container liveness. Container will be restarted if the probe fails.
  # Refer https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.
  liveness:
      tcpSocket:
        port: 9000
      initialDelaySeconds: 15
      periodSeconds: 20
  # Readiness Probe for container readiness. Container will be removed from service endpoints if the probe fails.
  # Refer https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  readiness:
      tcpSocket:
        port: 9000
      initialDelaySeconds: 5
      periodSeconds: 10
```
And then call it:
```sh
helm install --namespace tenant-ns \
  --create-namespace tenant minio/tenant \
  -f operator/helm/tenant/values.yaml
```
That way containers will have them:

```yaml
      livenessProbe:
        tcpSocket:
          port: 9000
        initialDelaySeconds: 15
        timeoutSeconds: 1
        periodSeconds: 20
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 9000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
```

But we are missing `startup` probe and Allan will create PR for it soon

**Comment by allanrogerr** [comment]
Startup probe has been implemented as part of the Helm install, in the next release. This may be added as part of `operator/helm/tenant/values.yaml`. See example value content below:
```
  # Startup Probe for container startup. Container will be restarted if the probe fails.
  # Refer https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  startup:
    tcpSocket:
      port: 9000
    initialDelaySeconds: 15
    timeoutSeconds: 10
    periodSeconds: 20
    successThreshold: 1
    failureThreshold: 2
```

After a helm install with the above example startup probe, the containers will register:
```
startupProbe:
      failureThreshold: 2
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      tcpSocket:
        port: 9000
      timeoutSeconds: 10
```
