### ISSUE TITLE
Can't download file through webconsole

### ISSUE THREAD

**Issue by gecube** [minio/operator#1377]
Hi!

I am still facing the issue when I can't download file through webconsole

Steps to reproduce:

1. create new k8s cluster
2. install minio operator for instance with the next values:
```yaml
    operator:
      env:
      - name: PROMETHEUS_NAMESPACE
        value: "monitoring-system"
      - name: MINIO_PROMETHEUS_URL
        value: "https://prometheus.prod.***.ai/"
    tenants: {}
    console:
      ingress:
        enabled: true
        ingressClassName: nginx
        host: console.minio.prod.***.ai
        path: /
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-http01-nginx-issuer
        tls:
        - hosts:
          - console.minio.prod.***.ai
          secretName: minio-tls
```
3. create a tenant:
```yaml
    secrets:
      name: minio1-env-configuration
      accessKey: ***
      secretKey: ***
    tenant:
      name: minio1
      prometheusOperator: true
      metrics:
        enabled: true
      env:
      - name: MINIO_PROMETHEUS_URL
        value: "https://prometheus.prod.***.ai/"
      pools:
      - servers: 4
        volumesPerServer: 1
        size: 4000Gi
        storageClassName: gp2
        tolerations: { }
        nodeSelector: { }
        affinity: { }
        resources: { }
        securityContext: { }
        topologySpreadConstraints: [ ]
      prometheus:
        storageClassName: gp2
      log:
        db:
          volumeClaimTemplate:
            spec:
              storageClassName: gp2
    ingress:
      api:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-http01-nginx-issuer
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        host: minio.prod.portsight.ai
        path: /
        pathType: Prefix
        tls:
        - hosts:
          - minio.prod.***.ai
          secretName: source-tls
```
4. Now - If I login to web console of operator and then go to the tenant, I can't download file.
The fix is easy - add the Ingress like:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01-nginx-issuer
    nginx.ingress.kubernetes.io/rewrite-target: https://console.minio.prod.***.ai/api/hop/minio-tenant/minio1/api/v1/buckets/$1
  name: minio-operator-console-fix
  namespace: minio-operator
spec:
  ingressClassName: nginx
  rules:
  - host: console.minio.prod.***.ai
    http:
      paths:
      - backend:
          service:
            name: console
            port:
              name: http
        path: /api/v1/buckets/(.*)
        pathType: Prefix
  tls:
  - hosts:
    - console.minio.prod.***.ai
    secretName: minio-tls
```

But it is definitely workaround.

Desired behaviour: the links to download of the files must work out of the box.
