### ISSUE TITLE
operator  operator-4.5.8.tgz   unauthenticated for invalid credentials

### ISSUE THREAD

**Issue by 631068264** [minio/operator#1417]
## Expected Behavior

helm install operator-4.5.8.tgz 

get the JWT to login 
<img width="894" alt="image" src="https://user-images.githubusercontent.com/8144089/215254500-ab6af009-d884-4228-af47-2d1a34596f4e.png">
operator console

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by pjuarezd** [comment]
provide more details
how to reproduce

**Comment by 631068264** [comment]
@pjuarezd 
just install and create a nodeport svc to login it

```
helm install minio-operator  operator-4.5.8.tgz -n minio-operator --create-namespace
```

apply 
```
apiVersion: v1
kind: Service
metadata:
  name: console-nodeport
  namespace: minio-operator
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
```


get jwt

```
kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode
```
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/8144089/215255454-7e99b8d7-cd75-4158-8eb0-5be27604fd44.png">


and then failed
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/8144089/215255511-eb1fcd76-81ef-4ebb-9a60-cf5e1c5efcca.png">
