### ISSUE TITLE
same JWT  not work for login operator console,  get  401  unauthenticated for invalid credentials

### ISSUE THREAD

**Issue by qwegas** [minio/operator#1422]
just install and create a nodeport svc to login it

```
helm install minio-operator  operator-4.5.8.tgz -n minio-operator --create-namespace
```

apply 
```
apiVersion: v1
kind: Service
metadata:
  name: console-nodeport
  namespace: minio-operator
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  type: NodePort

---

apiVersion: v1
kind: Secret
metadata:
  name: console-sa-secret
  namespace: minio-operator
  annotations:
    kubernetes.io/service-account.name: console-sa
type: kubernetes.io/service-account-token
```

get jwt

```
kubectl -n minio-operator  get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode
```
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/8144089/215255454-7e99b8d7-cd75-4158-8eb0-5be27604fd44.png">

and then failed
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/8144089/215255511-eb1fcd76-81ef-4ebb-9a60-cf5e1c5efcca.png">

console log
```
Serving operator at http://[::]:9090
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
ErrorWithContext:Get "https://dl.min.io/server/minio/release/linux-amd64/": dial tcp: lookup dl.min.io on 10.43.0.10:53: server misbehaving
```

## Your Environment

* Version used (`minio-operator`):  4.5.8
* Environment name and version (e.g. kubernetes v1.17.2):  1.23.6
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by qwegas** [comment]
use 4.5.7 save my life

**Comment by qwegas** [comment]
same problem in 4.5.7  
At the first time，it can login the operator console  
- and then install tenant  by helm 
- maybe the login timeout and refresh  to the login page.
- use same jwt to login 
- get same error

<img width="943" alt="image" src="https://user-images.githubusercontent.com/123848894/215311124-94d3b48a-f70a-463b-858b-29a94c3881e6.png">

<img width="947" alt="image" src="https://user-images.githubusercontent.com/123848894/215311137-645b61e2-716d-4b83-9e72-de10b9aa13c2.png">

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/123848894/215311149-2df85ee9-a63a-4215-b840-67629d9ed9eb.png">

**Comment by z666k** [comment]
I also get such a problem,my version :
k8s: 1.23.17
minio: 4.5.8
install style:  kubectl minio init --console-tls

<img width="945" alt="企业微信截图_16790386417936" src="https://user-images.githubusercontent.com/127073101/225842515-b2f274f3-1ba8-4726-a9e2-bfb776d83dd8.png">

**Comment by yaohwu** [comment]
got same 401 error after following https://min.io/docs/minio/kubernetes/upstream/operations/installation.html doc and creating a minio tenant.

Token maybe be invalid after sometime or creating a tenant or other actions that I don't know.

<img width="1142" alt="image" src="https://github.com/minio/operator/assets/9320666/4e4b6ad7-9e2a-4563-b67f-e549a0d4bafa">
<img width="1716" alt="image" src="https://github.com/minio/operator/assets/9320666/e53bf212-3cf4-4010-8b6a-4e2d0a8305be">

kubectl minio version
v5.0.6

<img width="467" alt="image" src="https://github.com/minio/operator/assets/9320666/7c73d921-e8df-4a11-a575-1761989c1eed">


Even using 
kubectl get secret/console-sa-secret -n minio-operator -o json | jq -r '.data.token' | base64 -d
to get the token but the 401 happened again.

**Comment by yaohwu** [comment]
Here is the logs
> E: 2023/07/04 09:08:40 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
Serving operator at http://[::]:9090
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value

From the key word,it maye be same with https://github.com/minio/operator/issues/1534.

**Comment by yaohwu** [comment]
> Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: operator-minio-external
spec:
  type: NodePort
  ports:
  - nodePort: 31909
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: operator
```

Using this to create a NodePort, get same error 401

**Comment by asura-10** [comment]
> Here is the logs
> 
> > E: 2023/07/04 09:08:40 Unable to load certs: unable to create certs CA directory at /tmp/certs/CAs: failed with mkdir /tmp/certs/CAs: read-only file system
> > Serving operator at http://[::]:9090
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> > Unable to validate the session token Anonymous: invalid character 'A' looking for beginning of value
> 
> From the key word,it maye be same with #1534.

To use Chrome's incognito mode， give a shot

**Comment by allanrogerr** [comment]
> 4.5.8 @qwegas This is not how a NodePort is defined. You are missing `.spec.ports[].nodePort` Please observe the following sample:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: minio-operator
    meta.helm.sh/release-namespace: minio-operator
  creationTimestamp: "0001-01-01T01:01:01Z"
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
    app.kubernetes.io/version: v4.5.8
    helm.sh/chart: operator-4.5.8
  name: console
  namespace: minio-operator
  resourceVersion: "1333"
  uid: 1-2-3-4-5
spec:
  clusterIP: x.x.x.x
  clusterIPs:
  - x.x.x.x
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31000
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

**Comment by allanrogerr** [comment]
The secret should also be autogenerated by the `minio-operator`. Please do not modify it.

**Comment by allanrogerr** [comment]
Here is a complete example:
# Install k3s. Print versions.
```
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - --snapshotter=fuse-overlayfs
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
k3s --version
```

Output
```
k3s version v1.27.6+k3s1 (bd04941a)
go version go1.20.8
```
sudo systemctl status k3s.service

Output
```
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; preset: enabled)
     Active: active (running) since Thu 2023-10-12 19:00:40 UTC; 26min ago
```

# Install helm
```
wget https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
tar -zxvf helm-v3.6.3-linux-amd64.tar.gz
sudo mv linux-amd64/helm /usr/local/bin/helm
helm version
```

Output
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

# Install minio-operator. Print version.
```
curl -O https://raw.githubusercontent.com/minio/operator/master/helm-releases/operator-4.5.8.tgz
tar -xvf operator-4.5.8.tg
helm install --namespace minio-operator --create-namespace minio-operator operator-4.5.8.tgz -f operator/values.yaml
helm inspect chart operator
```

Output
```
apiVersion: v2
appVersion: v4.5.8
description: A Helm chart for MinIO Operator
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: operator
sources:
- https://github.com/minio/operator
type: application
version: 4.5.8
```

# Validate minio-operator running
```
kubectl get pods -n minio-operator
```
Output
```
NAME                              READY   STATUS    RESTARTS   AGE
minio-operator-7d988dd6b6-lckt4   1/1     Running   0          24m
console-5756b69c9f-8s8d8          1/1     Running   0          24m
minio-operator-7d988dd6b6-swvnj   1/1     Running   0          24m
```

# Add Nodeport to service
```
kubectl patch service -n minio-operator console --type='merge' -p '{"spec":{"type": "NodePort", "ports":[{"name": "http", "port": 9090, "nodePort": 31000}]}}'
kubectl -n minio-operator get svc/console -o yaml
```
Output (redacted)
```
apiVersion: v1
kind: Service
...
spec:
  clusterIP: x.x.x.x
  clusterIPs:
  - x.x.x.x
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31000
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: minio-operator-console
    app.kubernetes.io/name: operator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

# Get jwt and login
```
kubectl -n minio-operator get secret console-sa-secret -o jsonpath="{.data.token}" | base64 --decode
```
<img width="1728" alt="image" src="https://github.com/minio/operator/assets/16472240/5e538dc2-aa86-4eb4-bd68-1f2259ff1eab">

<img width="1311" alt="image" src="https://github.com/minio/operator/assets/16472240/2d6f216f-cd6c-4b76-8353-6972b1e2b14f">
