### ISSUE TITLE
Because the default domain name suffix of coredns is not "cluster. local", it is impossible to communicate with operator. 由于coredns默认域名后缀不是"cluster. local" 导致无法与operator通信

### ISSUE THREAD

**Issue by qww-ygg** [minio/operator#1464]
**请问有什么方法可以修改“cluster.local”为我现在的默认域名后缀吗？**

pj: Is there any way to modify "cluster.local" to my current default domain name suffix?

**Comment by pjuarezd** [comment]
hi @qww-ygg let me take a look at this please

**Comment by pjuarezd** [comment]
You can set the Env variable `CLUSTER_DOMAIN` in the Operator deployment to specify a cluster DNS,

ie:

Helm chart values.yaml 
https://github.com/minio/operator/blob/86e89650bf879f912de42b2d768fc482582c6163/helm/operator/values.yaml#L10-L11
```yaml
operator:
  ## Setup environment variables for the Operator
  env:
     - name: CLUSTER_DOMAIN
       value: "internal.local"
  image:
    repository: minio/operator
    tag: v4.5.8
...
```

or directly the `minio-operator` deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: minio-operator
  labels:
    app.kubernetes.io/instance: minio-operator
    app.kubernetes.io/name: operator
spec:
  template:
    spec:
      containers:
        - name: minio-operator
          image: minio/operator:v4.5.8
...
          env:
            - name: MINIO_CONSOLE_TLS_ENABLE
              value: "off"
            - name: OPERATOR_STS_ENABLED
              value: "off"
            - name: CLUSTER_DOMAIN
              value: internal.local
...
```
