### ISSUE TITLE
Tenant Creation failed after some time - Cert Issue

### ISSUE THREAD

**Issue by rufreakde** [minio/operator#1471]
## Expected Behavior

minio tenant pod should be up and healthy

## Current Behavior

operator log
```
http: TLS handshake error from 100.64.4.74:48332: remote error: 
tls: bad certificate
```

tried:
```
curl https://operator.up-monitoring-db.svc.cluster.local:4222 --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
tenant pod is crashing with:
```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://XXXXXXXXXXX@operator.up-monitoring-db.svc.cluster.local:4222/webhook/v1/getenv/up-monitoring-db/minio1: Get "https://operator.up-monitoring-db.svc.cluster.local:4222/webhook/v1/getenv/up-monitoring-db/minio1?key=MINIO_ARGS": x509: certificate has expired or is not yet valid: current time 2023-02-28T08:43:56Z is after 2023-01-07T13:20:42Z
Stream closed EOF for up-monitoring-db/minio1-ss-0-0 (minio)
```

"certificate has expired or is not yet valid" how did this happen? Is there a guide to refresh it with the operator automatically?

## Possible Solution

Let operator take care of certificate rotation to fix this issue.
How to fix expiration? Just replace it with a self signed certificate? Is there documentation for a step by step guide? Wouldnt the operator do this step?

## Steps to Reproduce (for bugs)

1. install helm chart: 
2. chart: operator
    repoURL: https://operator.min.io/
    targetRevision: 4.4.9
3. check operator pod image version: `minio/minio:RELEASE.2022-01-08T03-11-54Z`
4. after some time certificate fails (I guess it expired?)

## Regression

regression: https://github.com/minio/operator/issues/803 ? Symptom might be same but the cause seems to be different so I would asume no?

## Your Environment

* Version used (`minio-operator`): minio/minio:RELEASE.2022-01-08T03-11-54Z
* Environment name and version (e.g. kubernetes v1.17.2): v1.22.x

**Comment by rufreakde** [comment]
Okay saw that somehow the setting was set to false I changed it to true: 
```
  requestAutoCert: true
```

So a new secret got created:
```
minio1-tls (same name as our tenant)
```

Restarted the statefulset (scale 0 scale 1) still same issue in the log pod crashing.

**Comment by rufreakde** [comment]
update: I had to do the scale up and scale down twice to get the volume mount of the minio1-tls certificate to mount.
But it still fails with the same error message

```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://AHDKAHDJHSKDHAKDJLK@operator.up-monitoring-db.svc.cluster.local:4222/webhook/v1/getenv/up-monitoring-db/minio1: Get "https://operator.up-monitoring-db.svc.cluster.local:4222/webhook/v1/getenv/up-monitoring-db/minio1?key=MINIO_ARGS": x509: certificate has expired or is not yet valid: current time 2023-02-28T09:15:02Z is after 2023-01-07T13:20:42Z
Stream closed EOF for up-monitoring-db/minio1-ss-0-0 (minio)
```

is it the operator certificate not the minio certificate that expired?

**Comment by rufreakde** [comment]
Tenant CR has a status section:
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
...
status:
  availableReplicas: 1
  certificates:
    autoCertEnabled: false # why is this false?
  currentState: Initialized
  drivesOnline: 4
  healthStatus: green
  pools:
  - legacySecurityContext: false
    ssName: minio1-ss-0
    state: PoolInitialized
  provisionedBuckets: true
  provisionedUsers: true
  revision: 0
  syncVersion: v4.3.0
  usage:
    capacity: 263794860032
    rawCapacity: 536870912000
    rawUsage: 8190611456
  writeQuorum: 3

```

**Comment by rufreakde** [comment]
So checking the operator-tls secret public key resulted in:
```yaml
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            44:9c:f5:3f:3a:e7:bf:21:b8:56:5c:4e:0a:c7:42:7c
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=ca-kubelet
        Validity
            Not Before: Dec  8 13:20:42 2022 GMT
            Not After : Jan  7 13:20:42 2023 GMT  # it is expired but the operator doesnt rotate it? 
```
So then with this informaton found the issue ticket closely related to the root cause:
https://github.com/minio/operator/issues/888
