### ISSUE TITLE
Error in console UI after deploying the operator helm chart: `open build/index.html: file does not exist`

### ISSUE THREAD

**Issue by usersina** [minio/operator#1528]
I installed the MinIO operator using the [Helm Chart](https://github.com/minio/operator/tree/master/helm/tenant) with the default configuration, port forwarded the console to access it in a browser, but I see the following error instead:

> open build/index.html: file does not exist

## Expected Behavior
The MinIO console should successfully show up in http://localhost:9090 after a default Helm Chart installation and a port forward.

## Current Behavior
Browser shows the following output
> open build/index.html: file does not exist

Here is a more detailed curl output

```bash
bash-4.4$ curl -v localhost:9090

* Rebuilt URL to: localhost:9090/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9090 (#0)
> GET / HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Server: MinIO Operator
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< Date: Tue, 28 Mar 2023 09:06:55 GMT
< Content-Length: 43
<
open build/index.html: file does not exist
* Connection #0 to host localhost left intact
```

## Steps to Reproduce

Installing the Helm chart

1. Configure the repo
```bash
helm repo add minio https://operator.min.io/
```

2. Install the chart
```bash
helm upgrade \
    --install \
    --namespace minio-operator \
    --create-namespace \
    minio-operator minio/operator
```

3. Port forward the console

```bash
kubectl --namespace minio-operator port-forward svc/console 9090:9090 --address='0.0.0.0'
```

4. Access the console in a browser or with curl

```bash
curl -v localhost:9090
```

## Your Environment
* Version used (`minio-operator`): `v5.0.0` (default from the Chart)
* Environment name and version: `K8s Client Version: v1.26.3` | `K8s Server Version: v1.26.1`
* Operating System and version (`uname -a`): `Linux kube-controller 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by sylvainOL** [comment]
Hello, I've got the exact same issue here as well

**Comment by dvaldivia** [comment]
That's strange, can you confirm the image the console deployment on the MinIO-operator namespace is using?

**Comment by usersina** [comment]
@dvaldivia, it's the same as the one specified in the [values.yaml](https://github.com/minio/operator/blob/master/helm/operator/values.yaml) of the chart

```bash
kubectl describe deployment console -n minio-operator
```

```yml
Pod Template:
  Labels:           app.kubernetes.io/instance=minio-operator-console
                    app.kubernetes.io/name=operator
  Service Account:  console-sa
  Containers:
   operator:
    Image:       quay.io/minio/operator:v5.0.0 # <==
    Ports:       9090/TCP, 9443/TCP
    Host Ports:  0/TCP, 0/TCP
```
