### ISSUE TITLE
Error in Operator logs after upgrading to `5.0.0`: `resource name may not be empty`

### ISSUE THREAD

**Issue by 9numbernine9** [minio/operator#1530]
Hello! :wave: 

After upgrading our deployed Minio Operator in AKS to `5.0.0` (deployed via Helm), we now see the following error in the Operator logs :
```
I0328 15:11:55.564523       1 upgrades.go:89] Upgrading v5.0.0
E0328 15:11:55.569301       1 main-controller.go:666] error syncing 'minio/tenant': resource name may not be empty
```
`tenant` is the name of the `Tenant`, deployed to the `minio` namespace. The error message above repeats about every minute as the operator attempts to perform whatever upgrade action it is trying to perform as part of the `5.0.0` upgrade.

The existing CR for `tenant` appears to validate against the CRD, so if changes to the CR are required as part of this upgrade then I'm not sure what they are. :man_shrugging: 

EDIT: I should also mention that this only appears to be an issue when _upgrading_. Deploying a brand new Minio `Tenant` with the same configuration (but different namespace) appears to work fine.

## Expected Behavior
Deploying the `5.0.0` operator should be able to perform whatever upgrade steps are required without issue.

## Current Behavior
The error message stated above repeats every minute. 

## Possible Solution
N/A. Not sure what has triggered this.

## Steps to Reproduce (for bugs)
1. Using an Operator with version `< 5.0.0`, deploy a `Tenant` CR. (We are using Minio version `RELEASE.2023-03-24T21-41-23Z`)
2. Once the Minio deployment is available, upgrade the Operator to version `5.0.0`.

## Your Environment

* Version used (`minio-operator`):
`5.0.0`
* Environment name and version (e.g. kubernetes v1.17.2):
Kubernetes `1.24.6` on Microsoft Azure AKS; nodes are running Ubuntu `18.04`.
* Link to your deployment file:
<details>
<summary>Helm chart `values.yml` file:</summary>

```
---
tenants: []
```
</details>

<details>
<summary>Kubernetes Resources</summary>

```
apiVersion: v1
kind: Secret
metadata:
  name: minio-configuration
  namespace: minio
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="verysecretpassword"
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: tenant
  namespace: minio
spec:
  configuration:
    name: minio-configuration
  requestAutoCert: false
  podManagementPolicy: Parallel
  image: minio/minio:RELEASE.2023-03-24T21-41-23Z
  env:
  - name: MINIO_BROWSER_REDIRECT_URL
    value: https://minio-console.mydomain.com
  pools:
  - servers: 4
    volumesPerServer: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        storageClassName: default
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
    resources:
      requests:
        cpu: 250m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    securityContext:
      fsGroup: 0
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
  exposeServices:
    minio: false
```
</details>
