### ISSUE TITLE
Upgrade operator 4.5.8 -> 5.0.x breaks tenants

### ISSUE THREAD

**Issue by D1StrX** [minio/operator#1544]
## Expected Behavior

No upgrade issues when upgrading the operator -> tenants from 4.5.8 to 5.0.x.

## Current Behavior

After upgrading the Operator from 4.5.8 to 5.0.2, the automatic upgrades breaks the minio tenants.
`kubectl logs -n <namespace> release-pool-0-0/0-1`

Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)
{"level":"ERROR","errKind":"APPLICATION","time":"2023-04-02T21:36:52.044482226Z","api":{"name":"SYSTEM","args":{"bucket":"<bucket_id>","object":"<object_id>"}},"remotehost":"<remote_host_something>","error":{"message":"*net.DNSError","source":["internal/logger/logger.go:258:logger.LogIf()","internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:135:logger.LogOnceIf()","cmd/endpoint.go:429:cmd.hostResolveToLocalhost()","cmd/endpoint.go:476:cmd.Endpoints.UpdateIsLocal()","cmd/endpoint.go:674:cmd.CreateEndpoints()","cmd/endpoint-ellipses.go:383:cmd.createServerEndpoints()","cmd/server-main.go:220:cmd.serverHandleCmdArgs()","cmd/server-main.go:524:cmd.serverMain()"]}}
{"level":"ERROR","errKind":"APPLICATION","time":"2023-04-02T21:36:52.047841032Z","api":{"name":"SYSTEM","args":{"bucket":"<bucket_id>","object":"<object_id>"}},"remotehost":"<remote_host_something>","error":{"message":"*net.DNSError","source":["internal/logger/logger.go:258:logger.LogIf()","internal/logger/logonce.go:104:logger.(*logOnceType).logOnceIf()","internal/logger/logonce.go:135:logger.LogOnceIf()","cmd/endpoint.go:429:cmd.hostResolveToLocalhost()","cmd/endpoint.go:476:cmd.Endpoints.UpdateIsLocal()","cmd/endpoint.go:674:cmd.CreateEndpoints()","cmd/endpoint-ellipses.go:383:cmd.createServerEndpoints()","cmd/server-main.go:220:cmd.serverHandleCmdArgs()","cmd/server-main.go:524:cmd.serverMain()"]}}

## Possible Solution

I am using the ENV - name: CLUSTER_DOMAIN. Something to do with that?

## Steps to Reproduce (for bugs)

1. Disabled logs & prometheus feature on tenants, prior to upgrade
2. Updated the values.yml to match the new images releases and relevant fields. Only images + priorityClassName: "" was changed
3. helm repo update
4. helm upgrade <release> minio/operator --values .\values.yml --namespace <ns> --version 5.0.<0-2>
```yaml
Operator starts to automatically upgrade tenants. Tenants are configured to use latest image.

# Default values for minio-operator.

operator:
  ## Setup environment variables for the Operator
  env:
    #   - name: MINIO_OPERATOR_TLS_ENABLE
    #     value: "off"
    #   - name: MINIO_CONSOLE_TLS_ENABLE
    #     value: "off"
    - name: CLUSTER_DOMAIN
      value: "example.com"
```
Ingress is configured.. shouldn't matter.?

## Context

All tenants are down and broken after the upgrade. Luckily a rollback to 4.5.8 is possible... but a lot of work.

## Regression

yes. 5.0.0 - 5.0.2

## Your Environment

* Version used (`minio-operator`): 4.5.8 -> 5.0.2
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes 1.26.2
* Server type and version: On-prem
* Operating System and version (`uname -a`): Ubuntu 22.04
* Link to your deployment file: .
