### ISSUE TITLE
Error: Unrecognized scope when using external idp

### ISSUE THREAD

**Issue by shkpk** [minio/operator#1545]
I'm trying to use an IDP having selfsigned SSL on it, and as per a thread from [minio](https://github.com/minio/minio/issues/16616) , it uses `/root/.minio/certs/CAs` to read selfsigned SSL.

## Expected Behavior
Allow to edit custom location for --certs-dir arguments.

## Current Behavior
I'm using command `kubectl edit statefulset.apps/minio-tenant-pool-0 -n namespace` for this purpose.

1. I'm trying to edit `--certs-dir` in stateful set of tenant, to `/root/.minio/certs` but after edit, it just resets back to original value of `/tmp/certs`
```
containers:
      - args:
        - server
        - --certs-dir
        - /tmp/certs
        - --console-address
        - :9090
```
2. I tried to volume so that I can put my selfsigned SSL on /tmp/certs/CAs location, but it also gets reset to original value
```
volumes:
      - name: minio-test-tls
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: public.crt
                path: CAs/operator.crt
              name: operator-tls
```

## Possible Solution
May be its a bug or I'm missing something where I needs to edit.

## Your Environment
* Version used (`minio-operator`): 4.5.8
* Environment name and version (e.g. kubernetes v1.17.2): 1.23.4
* Server type and version:
* Operating System and version (`uname -a`): Red Hat Enterprise Linux 8.7

**Comment by cniackz** [comment]
Hello @shkpk 

First of all, thank you for contacting us via issues!.

There are couple of things I would like to point out:

1. If using Operator, don't edit the `sts` but the `Tenant` as the `Tenant` is the CR that owns the `sts`.

2. We have no option to achieve exactly the change you are looking for, nevertheless we offer other fields to trust external certificates. I would suggest you to use `spec.externalCertSecret` as this field saves certs inside MinIO container at path: `/tmp/certs`

> Secret with self-signed cert:

```yaml
apiVersion: v1
data:
  tls.crt: <base64value>
  tls.key: <base64value>
immutable: true
kind: Secret
metadata:
  labels:
    v1.min.io/tenant: main-storage
  name: <tenant-name>-enqpg-external-server-certificate-0
  namespace: <tenant-namespace>
type: kubernetes.io/tls
```

> Tenant using above secret:

```yaml
  spec:
    externalCertSecret:
    - name: <tenant-name>-enqpg-external-server-certificate-0
      type: kubernetes.io/tls
```

Please let us know if that works for you!.
Or open new issue if it does not.

**Comment by cgiraldo** [comment]
I managed to integrate a minio Tenant with Keycloak IdP configuring the `additionalVolumes` and `additionalVolumeMounts`:

```
      additionalVolumes:
      - name: ca-certificate-only
        configMap:
          name: custom-ca-cert
          defaultMode: 0644
          optional: false
          items:
          - key: custom-ca.crt
            path: custom-ca.crt
      additionalVolumeMounts:
      - mountPath: /etc/ssl/certs/
        name: ca-certificate-only
        readOnly: true
```

Then you have to provide the ca certificate through the custom-ca-cert configmap:

```
kubectl create configmap custom-ca-cert --from-file custom-ca.crt
```

I hope this helps.
