### ISSUE TITLE
credsSecret deprecated - why?!

### ISSUE THREAD

**Issue by baznikin** [minio/operator#1584]
It' s just a cry of helplessness.

With operator v4 in my application I referenced same keys from secret, used by tenant like this:
```
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-tenant-creds
              key: accesskey
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-tenant-creds
              key: secretkey
```

Now I had to hard-code keys into deployment OR create TWO separate secrets with same values - one for app and another for tenant. Why you change it? What the logic behind this decision? It was very convenient.
