### ISSUE TITLE
Pools.0.tolerations.0.tolerationSeconds.seconds in body is required when trying to specify NoSchedule without seconds

### ISSUE THREAD

**Issue by VPelmeSHko** [minio/operator#1595]
Got **Pools.0.tolerations.0.tolerationSeconds.seconds in body is required.** when trying to specify NoSchedule without seconds in PodPlacement -> Tolerations screen.
Specifying seconds to 0 this will cause **invalid: spec.tolerations[0].effect** issue on statefulset

kubectl minio version
v4.5.0

kubectl -n test describe statefulset test-pool-0
~~~
Events:
  Type     Reason            Age                  From                    Message
  ----     ------            ----                 ----                    -------
  Warning  FailedCreate      2m6s (x69 over 37m)  statefulset-controller  create Pod test-pool-0-3 in StatefulSet test-pool-0 failed error: Pod "test-pool-0-3" is invalid: spec.tolerations[0].effect: Invalid value: "NoSchedule": effect must be 'NoExecute' when `tolerationSeconds` is set
~~~

kubectl -n test get  statefulset test-pool-0 -o yaml
~~~
tolerations:                          
      - effect: NoSchedule                                                                                            
        key: nvidia.com/gpu                            
        operator: Equal              
        tolerationSeconds: 0
        value: "true"
~~~

**Comment by debugger24** [comment]
Facing same issue. If i don't set tolerationSeconds it says `pools.0.tolerations.0.tolerationSeconds.seconds in body is required`

If I set it to non zero it says
`Invalid value: \"NoSchedule\": effect must be 'NoExecute' when tolerationSeconds is set`

**Comment by debugger24** [comment]
In the minio console, I checked the API call being made and updated the API call to set `tolerationSeconds` to null, it worked after that.

@bexsoft is this bug related to console given the API call is being made from console ?

Old payload (only tolerations section)
```yaml
"tolerations": [
    {
      "key": "demo",
      "tolerationSeconds": {
        "seconds": null
      },
      "value": "core",
      "effect": "NoSchedule",
      "operator": "Equal"
    }
  ]
  ```
  
  New Payload (only tolerations section)
  ```yaml
  "tolerations": [
    {
      "key": "demo",
      "tolerationSeconds": null,
      "value": "core",
      "effect": "NoSchedule",
      "operator": "Equal"
    }
  ]
  ```
