### ISSUE TITLE
Tenant creation via Operator Console gets stuck in "Provisioning initial users"

### ISSUE THREAD

**Issue by realulim** [minio/operator#1605]
## Expected Behavior
I want to create a tenant "mytenant" via the Operator Console.

## Current Behavior
Upon clicking "create" the operator gets stuck in the "Provisioning initial users" phase. The pods get stuck in "terminating". Don't be confused by the age numbers, they are continually reset to 0, so this is the state after waiting about 30 minutes:

```
NAME                   READY   STATUS        RESTARTS   AGE
mytenant-pool-0-0   0/2     Terminating   0          2s
mytenant-pool-0-1   0/2     Terminating   0          109s
mytenant-pool-0-2   0/2     Terminating   0          5s

```
The operator pod fails some kind of healthcheck according to its log:

```
I0512 14:05:08.698110       1 event.go:285] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"minio", Name:"mytenant", UID:"54905f0d-1a26-48f4-88c4-d698dea936b1", APIVersion:"minio.min.io/v2", ResourceVersion:"322074", FieldPath:""}): type: 'Warning' reason: 'UsersCreatedFailed' Users creation failed: Put "https://minio.minio.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxxxxxxxxxxxxx": dial tcp 10.43.136.176:443: connect: connection refused
I0512 14:05:11.065919       1 monitoring.go:124] 'minio/mytenant' Failed to get cluster health: Get "https://minio.minio.svc.cluster.local/minio/health/cluster": dial tcp 10.43.136.176:443: connect: connection refused

```

## Steps to Reproduce (for bugs)
1. Install Operator via `curl -L https://github.com/minio/operator/releases/download/v5.0.4/kubectl-minio_5.0.4_linux_amd64 -o /usr/local/bin/kubectl-minio`
2. `kubectl minio init`
3. `kubectl minio proxy -n minio-operator`
4. Go to Web Console and create tenant

## Context
The environment is a multi-node K3s cluster, cert-manager is installed and working. The node-local volumes are actually created ok, but they are not attached to any pod. After deleting the tenant via `kubectl minio tenant delete mytenant -n minio` the PVCs and PVs remain, as well as the backing volumes.

## Your Environment

* Version used (`minio-operator`): v5.0.4
* Environment name and version (e.g. kubernetes v1.17.2): v1.24.13+k3s1
* Server type and version:
* Operating System and version (`uname -a`): Rocky Linux 9

**Comment by shtripat** [comment]
Have you tried this with higher versions of k8s?
With v1.25.3 locally I don't see an issue and able to create tenant fine.

**Comment by realulim** [comment]
I haven't tried it with any other K8s version, as the one I am using is explicitly supported (Kubernetes 1.21 or Later). Since I haven't done anything but run the installation scripts, there must be a bug in them that triggers in my case and not yours. The error message says that the healthcheck endpoint isn't reachable, therefore I think that MinIO hasn't come up at all.

**Comment by dvaldivia** [comment]
Are you using upstream kubernetes 1.21? That problem you are describing could be due to a problem with TLS, which means the `CertificateSigningRequests` (or CSRs) Are not getting issued

**Comment by realulim** [comment]
I am using v1.24.13+k3s1 (K3s). The Cert Manager seems to work fine in general, i. e. I can issue certificates for other purposes.

**Comment by cesnietor** [comment]
We'll try to replicate it using that version.

**Comment by allanrogerr** [comment]
@realulim am also unable to replicate the issue. Are you still facing this - If so, could you try creating a tenant without TLS or with Auto TLS; or consider trying a later version of k3s and k8s?

**Comment by realulim** [comment]
I am now using another object store on this cluster, but when I start another project with a new cluster, I will try it again with the then current versions. Thank you for looking into it.

**Comment by allanrogerr** [comment]
As a workaround, simply, try changing your `.spec.pools` podAntiAffinity to NOT schedule on tenants that are NOT your tenant and on pools that are NOT your pools. e.g.
```
  - affinity:                                    
      podAntiAffinity:                           
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:                               
            matchExpressions:                          
            - key: v1.min.io/tenant                    
              operator: NotIn                          
              values:                                  
              - myminio            
            - key: v1.min.io/pool  
              operator: NotIn      
              values:            
              - pool-0           
          topologyKey: kubernetes.io/hostname
```

I'm looking more into this.
