### ISSUE TITLE
Operator console not listing pools without name

### ISSUE THREAD

**Issue by pjuarezd** [minio/operator#1613]
1) When a pool is created but it is missing the pool name, the Operator console UI do not list the pool.

2) Found that the kubectl krew command `should` define a default name if the parameter `--pool` or `-p` (name of the pool) is not provided, just as how Operator Console does when creating a new pool, but it doesn't.

## Expected Behavior
Operator console to list all pools
To kubectl krew command to assign a default pool name when no any specified.

## Current Behavior
Operator console is only listing pools with a name

## Possible Solution
* Use another field as ID in the grid, instead of name, ie: the element index
* Add a default name to pools

1) Create a tenant
2) Go to Operator console UI, list the pools
![pool 0 listed](https://github.com/minio/operator/assets/1334362/1d4b5276-b907-4c9b-833d-fb1f54f0b475)

3) Expand tenant with a new pool using kubectl kew command, do not provide pool name

```sh
kubectl-minio tenant expand minio-tenant-1 -n minio-tenant-1 --servers 3 --storage-class standard --volumes 6 --capacity 16Gi
```
4) Verify the pool is created, list the statefulsets 

```
kubectl get sts -n minio-tenant-1
NAME                    READY   AGE
minio-tenant-1-pool-0   2/4     3m33s
minio-tenant-1-pool-1   2/3     62s
```

Also checking the tenant yaml, it includes two pools, one with a `name`, one other without a `name`

```yaml
...
  pools:
  - affinity:
...
    name: pool-0
    resources:
      requests:
        cpu: "2"
        memory: 5Gi
    runtimeClassName: ""
    servers: 4
    volumeClaimTemplate:
...
    volumesPerServer: 4
  - affinity:
...
    resources: {}
    servers: 3
    volumeClaimTemplate:
...
    volumesPerServer: 2
  requestAutoCert: true
```
5) Notice the second pool do not list in Operator Console

![pool 1 no listed](https://github.com/minio/operator/assets/1334362/af28471b-d790-4ef8-95fa-a5afb40c2505)

## Your Environment

* Version used (`minio-operator`): 5.0.4
* Environment name and version (e.g. kubernetes v1.17.2): 
```
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:36:32Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:
