### ISSUE TITLE
BUG: Pool creation name conflict when Expanding Tenant

### ISSUE THREAD

**Issue by bobacarOrpheo** [minio/operator#1626]
## Expected Behavior

When expanding tenant, the new pool should have a name different from the others pools, thanks to incrementation, to provoke restart of the MinIO tenant and process of it's creation. 

I suggest the possibility of deleting a pool directly inside the Pools interface.

## Current Behavior

When extanding the tenant with a new pool, there is no effect since the new pool "pool-1" have the same name of another active pool "pool-1".
If i try to add on top of that a new pool, this creation have now a different name "pool-2" and make the tenant restart.
It never occurs since it's stuck.

## Possible Solution

My workaround was to avoid the double "pool-1" name who break the expand of the tenant.
So for that, instead of decommissioning the "pool-0", i do it on the "pool-1" that i delete once completed.

Like that i have no conflict.

This approach work for the PoC i try to do, but if want to decommission the "pool-0" it may be a problem after due to the presence of "pool-1" name used again when expanding the tenant.

## Steps to Reproduce (for bugs)
I built the nodes thanks to those commands:
```bash
kubectl krew install directpv
kubectl directpv install
kubectl directpv discover
kubectl directpv init drives.yaml --dangerous
kubectl krew install minio
kubectl minio init
kubectl minio proxy -n minio-operator
```

Once in the Operator Console web interface, i first create a tenant named test with 4 servers, 36 Gi in total and 1 volume per server.
Like that i obtain my **first Pool named "pool-0"**.

After creating a bucket where i upload one file, i go back to the Operator Console web interface.
In the **Pool section**, i click on **Expand Tenant**.

There i put 4 Number of Servers, 9 Gi as Volume Size, 1 Volumes per Server, and i choose directpv-min-io for Storage Class.
Like that i obtain my **second Pool named "pool-1"**.

I decommission the "pool-0", then deleted it once completed using multiple different approachs:
- Edit the tenant configuration inside the Operator Console with the icon of the pen at the up-right

- Get the tenant.yaml from this command:
```bash
kubectl get tenants test -n test -o yaml > tenant.yaml
```
Then i remove the corresponding pools block starting from - affinity to volumesPerServer in the yaml and multiple others things to finish with this:

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: test
  namespace: test
  uid: 42296fa6-b7b5-4e78-924d-c7170f8fa160
scheduler:
  name: ""
spec:
  configuration:
    name: test-env-configuration
  credsSecret:
    name: test-secret
  exposeServices:
    console: true
    minio: true
  image: minio/minio:RELEASE.2023-06-02T23-17-26Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - test
            - key: v1.min.io/pool
              operator: In
              values:
              - pool-1
          topologyKey: kubernetes.io/hostname
    name: pool-1
    resources: {}
    runtimeClassName: ""
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "9663676416"
        storageClassName: directpv-min-io
      status: {}
    volumesPerServer: 1
  requestAutoCert: true
  users:
  - name: test-user-0
```

- Used this command and removing approximatively the same extra parts than previously:
```bash
kubectl edit tenants test -n test
```

## Context
I'm trying to find a way for expanding storage size of a tenant without having to create numbers of other servers for cumulative gains.

## Your Environment
A Kubernetes cluster from OVH composed of 8 nodes with 10 Go HDD attached for each.

* Version used (`minio-operator`): 5.0.4
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes 1.26.4-0
* Server type and version: OVH Provider, 4 CPU with 8 Go RAM
* Operating System and version (`uname -a`): Arch-Linux
* Link to your deployment file: See the commands i used, no deployment file.
