### ISSUE TITLE
Node Affinity selectors use "AND" instead of "OR" logic

### ISSUE THREAD

**Issue by ravindk89** [minio/operator#1635]
Using latest stable Operator:

Attempted to apply node selectors as follows:

![image](https://user-images.githubusercontent.com/14060842/215905371-11b0e0a7-1e81-4f3e-9d95-023d3bae8d80.png)

for node 2 -> 5

This results in the following YAML:

```yaml
  pools:
  - affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node2
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node3
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node4
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node5
```

This fails scheduling as Kubernetes appears to look for hostnames with all of those labels at once, not just any single one

The correct YAML via @pjuarezd is:

```yaml
 pools:
  - affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - node2
              - node3
              - node4
              - node5
```

I think the reasonable expectation here is to either:

- Convert the selector field to be a manual entry or pickbox for "or" semantics, or
- Treat the entire list like one giant "or"

The current functionality I think would not suffice for something like "restrict this tenant to the following node hostnames." It would work if you just applied a label I suppose.
