### ISSUE TITLE
Additional volume mount options when creating a new tenant.

### ISSUE THREAD

**Issue by gpaluru** [minio/operator#1710]
**Is your feature request related to a problem? Please describe.**
I have installed the minio operator v4.5.2 and trying to create a new tenant, which uses NFS (protected with Kerberos) as the backend for storage. I want to do additional volume mounts to include `keytab` file as the secret and `krb5.conf` as configmap which I can use to access the NFS (protected with kerberos) within the image. But unfortunately I don't see any option to do the additional mounts within the tenant helm values or If it is there is such option to do please let me know how can I do it!

**Describe the solution you'd like**
I want to mount volumes like below

```
        volumeMounts:
        - name: krb5conf
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
        - name: kerberos-keytab
          mountPath:  /tmp/kerberos.keytab
          subPath:  kerberos.keytab
      volumes:
      - name: krb5conf
        configMap:
          name: krb5conf
          items:
          - key: krb5.conf
            path: krb5.conf
      - name: kerberos-keytab
        secret:
          secretName: kerberos-keytab
          items:
          - key: kerberos.keytab
            path:  kerberos.keytab
```

**Describe alternatives you've considered**
Currently, I'm trying to add it Dockerfile and rebuild the image, but I have to rebuild the image each time when I have re-generate the keytab file.
