### ISSUE TITLE
PROMETHEUS_NAME env variable seems to be not correctly integrated

### ISSUE THREAD

**Issue by ventaubain** [minio/operator#1760]
## Expected Behavior
I want to use `prometheusOperator` option to add scrap configuration to a kube-prometheus placed on a custom namespace.
I set `PROMETHEUS_NAMESPACE` and `PROMETHEUS_NAME` in the operator yaml but the operator logs (during tenant creation) return:

`E0907 08:34:06.480375       1 main-controller.go:676] error syncing 'minio-storage/minio-storage': More than 1 prometheus found on namespace monitoring. PROMETHEUS_NAME not specified.`

## Current Behavior
`PROMETHEUS_NAMESPACE` is correctly handle but `PROMETHEUS_NAME` seems to not.

## Steps to Reproduce (for bugs)
1. `helm install --namespace minio-operator --create-namespace minio-operator minio/operator -f values.yaml`

values.yaml

```
# https://github.com/minio/operator/blob/master/helm/operator/values.yaml
operator:
  ## Setup environment variables for the Operator
   env:
     - name: PROMETHEUS_NAMESPACE
       value: "monitoring"
     - name: PROMETHEUS_NAME
       value: "kube-prometheus-stack-prometheus"
```
2. Create a tenant with `prometheusOperator: true` in the corresponding values.yaml. Be sure to have a kube-prometheus operator deployed in the `monitoring` namesapce
4. Show logs `kubectl logs service/operator -n minio-operator`

## Your Environment

* Version used (`minio-operator`): 5.0.7
* Environment name and version (e.g. kubernetes v1.17.2): v1.26.8
