### ISSUE TITLE
tenant install failed - references non-existent secret key: public.crt

### ISSUE THREAD

**Issue by chancez** [minio/operator#1839]
## Expected Behavior
We were using minio-operator 5.0.6 in CI using the operator and tenant helm charts. We configure minio with TLS using cert-manager based on the following the [docs](https://github.com/minio/operator/blob/master/docs/tls.md#using-cert-manager). This works correctly.

## Current Behavior

After upgrading to 5.0.10 CI started failing while waiting for the minio tenant statefulset to become ready. In the k8s events for the minio tenant statefulset, we see the following warnings:

```
  Normal   Scheduled    9m34s                 default-scheduler  Successfully assigned minio/quickstart-ss-0-0 to kind-control-plane
  Warning  FailedMount  80s (x12 over 9m34s)  kubelet            MountVolume.SetUp failed for volume "quickstart-tls" : references non-existent secret key: public.crt
  Warning  FailedMount  47s (x4 over 7m31s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[quickstart-tls], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
 ```

## Possible Solution
Make `public.crt` optional in the volume mount, or remove it entirely.

## Steps to Reproduce (for bugs)
1. Install cert-manager, and [follow the docs for setting up minio-operator w/ cert-manager](https://github.com/minio/operator/blob/master/docs/tls.md#using-cert-manager)
2. Install minio-operator 
3. Install minio tenant using helm using the `values.yaml` for minio-tenant that are provided at the bottom of the issue
4. See minio tenant never becomes ready

## Context

We use minio for testing our product with s3 compatible object storage, and in our Quickstart docs. This issue prevents us from upgrading minio.

## Regression
Is this issue a regression? Yes
If Yes, optionally please include minio-operator version caused the regression: It regressed somewhere between 5.0.6 and 5.0.10.

## Your Environment

* Version used (`minio-operator`): `5.0.10`
* Environment name and version (e.g. kubernetes v1.17.2): kind v0.20.0, Kubernetes 1.27.3.
* Server type and version:
* Operating System and version (`uname -a`): ubuntu 22.04 via GitHub hosted runners
* Link to your deployment file:

```
secrets:
  enabled: true
  name: minio-secret
  accessKey: minio
  secretKey: quickstart
tenant:
  name: quickstart
  configuration:
    name: minio-secret
  pools:
    - servers: 1
      volumesPerServer: 4
      size: 2Gi
      storageClassName: standard
  buckets:
    - name: "timescape"
    - name: "clickhouse"
  certificate:
    externalCertSecret:
      - name: tls-minio
        type: kubernetes.io/tls
  kes:
    configuration: false
  log:
    disabled: true
  prometheus:
    disabled: true
```

**Comment by cniackz** [comment]
Sorry guys, yes this is broken. I can reproduce it locally with our kustomize example published by Lenin:

```
MountVolume.SetUp failed for volume "myminio-tls" : references non-existent secret key: public.crt
```

Tomorrow I will continue with it and fix it

**Comment by cniackz** [comment]
<img width="1840" alt="Screenshot 2023-10-30 at 7 05 01 PM" src="https://github.com/minio/operator/assets/6667358/da48a2aa-6f41-4868-995b-69117c7919f3">

**Comment by cniackz** [comment]
For now testing notes at my repo: https://github.com/cniackz/public/wiki/cert%E2%80%90manager, will fix and move the notes to minio wiki once this is working again.

**Comment by cniackz** [comment]
Thank you @chancez for reporting this issue 👍

**Comment by cniackz** [comment]
@chancez the solution I found is simple, you just need to delete `operator-ca-tls` secret from `minio-operator` ns and from tenant's ns. Then regenerate it with `pubilc.crt` instead, here the PR:

https://github.com/minio/operator/pull/1842

**Comment by cniackz** [comment]
@chancez the page I am updating is: https://github.com/minio/operator/blob/master/docs/cert-manager.md#create-operator-ca-tls-secret where the secret has now to contain `public.crt` to work for `cert-manager`

**Comment by chancez** [comment]
Also why `public.crt` instead of `ca.crt`? The latter is somewhat more 'standard' (though there is no standard naming convention, but I'd argue `ca.crt` is more common than `public.crt`.

**Comment by chancez** [comment]
Okay, after looking at the tenant pod, I see why you're suggesting that. The tenant pod is mounting the `operator-tls-ca`. Why though? Does the tenant talk to the operator? Why does it need a CA? 

```
    - name: quickstart-tls
      projected:
        defaultMode: 420
        sources:
        - secret:
            items:
            - key: tls.crt
              path: public.crt
            - key: tls.key
              path: private.key
            - key: tls.crt
              path: CAs/public.crt
            name: tls-minio
        - secret:
            items:
            - key: public.crt
              path: CAs/operator-ca.crt
            name: operator-ca-tls
```

**Comment by chancez** [comment]
I can confirm the suggested change in the docs fixes it, but I still have the questions about why the why the tenant is mounting the CA instead of the operator.

**Comment by chancez** [comment]
So I tried creating the secret with both `ca.crt` and `public.crt`:

```
kubectl -n minio-operator create secret generic operator-ca-tls --from-file=ca.crt=ca-cert.pem --from-file=public.crt=ca-cert.pem
```

But that wasn't sufficient, the operator is still unable to verify the tenant's certificate.

**Comment by cniackz** [comment]
In version `Version 5.0.11` of Operator, this issue should no longer persist.

**Comment by bendemott** [comment]
This problem still exists in 5.0.15

**Comment by larssb** [comment]
Yeah still happens in v6.0.3 as well.

**Comment by rolinh** [comment]
That's because the minio image in v6.0.3 is not recent enough. It should work if you override it with tag `RELEASE.2024-08-29T01-40-52Z` or newer (`tenant.image.tag`). Or wait for v6.0.4 to be released.

**Comment by larssb** [comment]
@rolinh thank you. Thought that the needed fix was there long time ago now that it was declared fixed mid May this year.

Thank you very much for the info.

**Comment by khmarochos** [comment]
Today I've stepped on the same rake. But my problem (at least the most significant one) was in the type of the certificate:
```yaml
tenant:
  certificate:
    requestAutoCert: false
    externalCertSecret:
      - name: tls-minio
        type: cert-manager.org/v1
```
The type I set was wrong, it should be `kubernetes.io/tls` instead of `cert-manager.org/v1`. When it's set to `cert-manager.org/v1`, the operator forms the StatefulSet with references to `public.crt` and `private.key`, not to `tls.crt` and `tls.key` like in the case of `kubernetes.io/tls`.
