### ISSUE TITLE
requestAutoCert makes tenant stuck in "Provisioning default buckets", operator can't find Kubernetes CA (CN=kubernetes)

### ISSUE THREAD

**Issue by krishgu** [minio/operator#1845]
Trying to use a default setup of the minio-operator and a tenant, using Helm charts version 5.0.10.  The operator is installed in `minio-operator` namespace, and tenant is `appzero` in `tenant-ns` namespace, with 3 buckets defined. This is the tenant yaml file. the `requestAutoCert` is `true` by default in the [Tenant helm values.yaml](https://github.com/minio/operator/blob/master/helm/tenant/values.yaml#L118)

```yaml
tenant:
  name: appzero
  image:
  ...
  mountPath: /apps/minio-data
  subPath: /appzero
  configuration:
    name: appzero-env-configuration
  pools:
...
  metrics:
    enabled: true
  features:
    bucketDNS: false
    domains: { }
    enableSFTP: true
  buckets: 
    - name: "bkt1"
    - name: "bkt2"
    - name: "bkt3"
  prometheusOperator: false
  ingress:
    api:
      enabled: true
      ingressClassName: "nginx"
      host: minio.local
    console:
      enabled: true
      ingressClassName: "nginx"
      host: minio-console.local
```

## Expected Behavior
I expect this to work, with this tenant and the three buckets created

## Current Behavior
1. The tenant Status is in "Provisioning Default buckets"
```yaml
status:
  availableReplicas: 0
  certificates:
    autoCertEnabled: true
    customCertificates: {}
  currentState: Provisioning default buckets
  drivesOffline: 13
  drivesOnline: 3
  healthMessage: Service Unavailable
  healthStatus: red
```
2. additionally, there are three services created for the tenant in the `tenant-ns` namespace. `appzero-console`, `appzero-hl`, and just `minio` . Why is the `minio` service created without the prefix of the tenant name (should be `appzero-minio`)?  Is it because of the ingress configuration for the tenant? 
4. an unrelated -- if I set `prometheusOperator: true`, it looks at the default namespace, is there a way to specify the namespace for the Prometheus?

5. ## Additional information
* The operator gets stuck in 
```
I1031 23:10:23.883357       1 event.go:298] Event(v1.ObjectReference{Kind:"Tenant", Namespace:"tenant-ns", Name:"appzero", UID:"xxxx", APIVersion:"minio.min.io/v2", ResourceVersion:"22030816", FieldPath:""}): type: 'Warning' reason: 'BucketsCreatedFailed' Buckets creation failed: Put "https://minio.tenant-ns.svc.cluster.local/bkt1/": dial tcp 10.107.23.215:443: connect: connection refused
```
* Doing curl from the operator-leader pod, shows that it **can't find the kubernetes ca.crt, with CN=kubernetes**, get stuck in `SSL certificate problem: unable to get local issuer certificate`
** the `minio.tenant-ns` service is showing ```subject: O=system:nodes; CN=system:node:*.appzero-hl.tenant-ns.svc.cluster.local
  start date: Oct 31 23:05:16 2023 GMT
 expire date: Oct 30 23:05:16 2024 GMT
 issuer: CN=kubernetes```
* curl to the endpoint without cert-validation (`curl -k https://minio.tenant-ns.svc.cluster.local/bkt1`) works. curl uses only `/etc/pki/tls/certs/ca-bundle.crt` to validate certs
 
## Possible Solution
* we can add the SSL_CERTS_DIR to include /var/run/kubernetes.io/secrets/serviceaccounts as one option, but shouldn't that be the default? 
* I also haven't tried setting `requestAutoCert: false` so as to get a closure to this issue
* Will try removing the ingress settings to observe the behavior

## Context
Thank you!

## Your Environment

* Version used (`minio-operator`): 5.0.17
* Environment name and version (e.g. kubernetes v1.17.2): v1.21.4
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:
