### ISSUE TITLE
Tenants cannot be restored from velero, k8up, restic PVC backups because chart does not accept an existing claim

### ISSUE THREAD

**Issue by cloudymax** [minio/operator#1869]
The documented process for restoring Minio from Valero, Resit, and K8up is to create a PVC, copy backups to the PVC, then specify that PVC as an existing claim for Minio.

The ability to specify an existing claim was removed when migrating from the vanilla chart to the new operator/tenant.

reference: https://github.com/minio/minio/blob/22d59e757da6e83ccb954fc6abc094375d73d444/helm/minio/values.yaml#L148

## Expected Behavior

I would expect to be able to specify an existing claim as is possible in the vanilla chart and use the tools Mino member harshavardhana says are the endorsed ways to do backups in https://github.com/minio/minio/issues/4135:

```
There some tools which we recommend such as

    Restic https://docs.minio.io/docs/restic-with-minio
    Rclone https://docs.minio.io/docs/rclone-with-minio-server
```

## Current Behavior

There are no-longer any options for specifying which PVC is used by the tenant.

## Possible Solution

Allow a pool to contain 1 server which will respect the `spec.dataSource` field of `volumeClaimTemplate` such that the pool will attach to an existing PVC 

PVC:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-restore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # Must be sufficient to hold your data
      storage: 5Gi
```

Pool:
```yaml
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      volumeClaimTemplate:
        spec:
          dataSource:
            backup-restore
```

## Context

The lack of control over PVCs breaks Valero, K8up, and Restic PVC backups
