### ISSUE TITLE
GitHub release missing for  v5.0.11

### ISSUE THREAD

**Issue by xoxys** [minio/operator#1871]
The operator v5.0.11 was released through https://github.com/minio/operator/pull/1865, but there is no GitHub release for this version. Where do we get the prebuild binaries or the changelog for this release? Was it just an oversight, or will there be no more GitHub releases in the future?

**Comment by harshavardhana** [comment]
It is not released yet, we just merged the commit we will release.

**Comment by xoxys** [comment]
Well, but this PR has uploaded the helm release targz file already. Due to this upload helm is already aware of this release and tools around helm version updates often use in GitOps will detect this new version through the helm registry as well. This is pretty confusing and make GitOps automation quiet useless.

```
❯ helm search repo minio
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                                                   
minio/operator      	5.0.11       	v5.0.11    	A Helm chart for MinIO Operator                   
minio/tenant        	5.0.11       	v5.0.11    	A Helm chart for MinIO Operator   
```

**Comment by jessebot** [comment]
yeah, this broke my Argo CD Application because I let renovateBot update the version as I thought it was ready based on the response https://github.com/minio/operator/issues/1867#issuecomment-1815922097. Here's an example PR that dependency updaters like RenovateBot will pick up when you make that tar ball available: https://github.com/small-hack/argocd-apps/pull/350
 
 but since it wasn't actually ready, all my pods are in an `ImagePullBackOff` state like this console pod from the replicaSet for the operator:
 
 ```yaml
 status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2023-11-17T12:06:01Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2023-11-17T12:06:01Z'
      message: 'containers with unready status: [operator]'
      reason: ContainersNotReady
      status: 'False'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2023-11-17T12:06:01Z'
      message: 'containers with unready status: [operator]'
      reason: ContainersNotReady
      status: 'False'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2023-11-17T12:06:01Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - image: 'quay.io/minio/operator:v5.0.11'
      imageID: ''
      lastState: {}
      name: operator
      ready: false
      restartCount: 0
      started: false
      state:
        waiting:
          message: 'Back-off pulling image "quay.io/minio/operator:v5.0.11"'
          reason: ImagePullBackOff
 ```
 
 with this in the logs:
 
 ```
 container "operator" in pod "console-5ddcd987db-8h2xs" is waiting to start: trying and failing to pull image
 ```
 
 
![screenshot of the argo cd graph for the minio helm chart release sohwing v5.0.11 but every pod is in a degraded state with imagepullbackoff](https://github.com/minio/operator/assets/2389292/fe028cd1-3b67-4c93-b0b3-b36db6c6f044)
