### ISSUE TITLE
Operator Console in Read-Only mode

### ISSUE THREAD

**Issue by sathieu** [minio/operator#1905]
**Is your feature request related to a problem? Please describe.**

By mistake (trying to delete a pool), we deleted a tenant (on a test cluster 🥉).

**Describe the solution you'd like**

We use GitOps (ArgoCD) to create tenants. However, will still use the Operator Console to check configuration and metrics, and connect to MinIO console (this time RW).

Having a global `readonly` flag to the MinIO operator console would avoid this kind of mistake.

**Describe alternatives you've considered**
Disabling the operator console.

**Additional context**

**Comment by cniackz** [comment]
We can play around with the RBAC permissions; so that Operator has no way to delete the tenant and by doing that no extra code change is required at all... Give me some time to prepare an example or a wiki for you to take a look at....

**Comment by cniackz** [comment]
Got it, steps are:

1. Change `console-sa-role` which is a Cluster Role:

From: 

```yaml
  - verbs:
      - '*'
    apiGroups:
      - minio.min.io
    resources:
      - '*'
```

To:

```yaml
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - minio.min.io
    resources:
      - '*'
```

That way, when you hit delete, you will see:

<img width="1840" alt="Screenshot 2024-04-08 at 3 14 23 PM" src="https://github.com/minio/operator/assets/6667358/fba6ffc8-b595-48ad-8d3f-d3bb84f84231">
