### ISSUE TITLE
Console Prometheus integration does not seem to support authentication to Prometheus service

### ISSUE THREAD

**Issue by bukovjanmic** [minio/operator#1911]
We try to enable Prometheus integration in the Minio console.

We are installing Minio operator 5.0.10 on Openshift 4.12, with Openshift built-in Prometheus stack. Prometheus can be queried via Thanos querier service, however, this service requires token authentication on the endpoint.

According to documentation, we set up MINIO_PROMETHEUS_URL, however, there seems no way to enable token authentication (via Authentication Bearer: <token> header).

Possibly there should be an option to use a token defined by a secret reference.

Or maybe better yet, since the operator is meant for Kubernetes anyway, the corresponding token is usually mounted under /var/run/secrets/kubernetes.io/serviceaccount/token in the console pod, so the console could use this when querying the Prometheus endpoint automatically.

Note that this is about integrating Prometheus data into console dashboards. Exporting the minio metrics is working according to documentation and we see the metrics in Grafana dashboards.

**Comment by jiuker** [comment]
@bukovjanmic You can sen minio's env with `MINIO_PROMETHEUS_AUTH_TYPE` set by `public`.

**Comment by cniackz** [comment]
@bexsoft has some useful information that might be related to this, please Benjamin share what information you have applicable for console just to see if we can apply it in here and thank you

**Comment by bexsoft** [comment]
Hi @bukovjanmic!

We implemented `CONSOLE_PROMETHEUS_AUTH_TOKEN` for these cases where you need a Bearer token to access your Prometheus data.

In this case you just need to pass your Bearer token to this env variable and it should start connecting to your Prometheus service.

We will close this ticket, please feel to reopen it in case you find some issues with this.

Thank you.

**Comment by bukovjanmic** [comment]
According to documentation - https://min.io/docs/minio/linux/reference/minio-server/settings/console.html, this is not a Bearer token, but Basic auth token, which is not used on Openshift user workload monitoring.

For the time being, we solved this by using nginx as forward proxy, here is what works for us (if someone is looking for a solution they might find it useful):

The service account referenced in s3-sa-token should have corresponding RBAC granted.

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: s3-sa-token
  annotations:
    kubernetes.io/service-account.name: default
data:
type: kubernetes.io/service-account-token
```

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-monitoring-view
  namespace: <your namespace>
subjects:
  - kind: ServiceAccount
    name: default
    namespace: <your namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
```

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf
data:
  nginx.conf: |-

    events {
      worker_connections 1024;
    }

    http {
      default_type application/octet-stream;

      proxy_http_version 1.1;
      proxy_redirect off;
      proxy_buffer_size          128k;
      proxy_buffers              4 256k;
      proxy_busy_buffers_size    256k;
      proxy_next_upstream error timeout invalid_header http_502 http_503 non_idempotent;
      proxy_next_upstream_tries 2;

      proxy_read_timeout 30s;
      proxy_send_timeout 5s;

      upstream thanos {
        server thanos-querier.openshift-monitoring.svc.cluster.local:9092;
        keepalive 2;
      }

      upstream thanos-health {
        server thanos-querier.openshift-monitoring.svc.cluster.local:9091;
        keepalive 2;
      }

      server {
        include /etc/nginx/conf.d/default.conf;
      }
    }
```
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-conf-templates
data:
  default.conf.template: |-
    listen 8080;

    location /-/healthy {
      proxy_pass https://thanos-health;
    }

    location / {
      rewrite ^/?(.*) /$1?namespace=${S3_NAMESPACE} break;
      proxy_set_header Authorization "Bearer ${S3_SA_TOKEN}";
      proxy_pass https://thanos$uri$is_args$args;
    }
```

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      serviceAccountName: default
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 150m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          name: nginx
          env:
            - name: S3_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: S3_SA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: s3-sa-token
                  key: token
          securityContext:
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
            - name: nginx-conf-templates
              mountPath: /etc/nginx/templates
            - name: cache
              mountPath: /var/cache/nginx
            - name: runtime
              mountPath: /var/run
            - name: conf
              mountPath: /etc/nginx/conf.d
          terminationMessagePolicy: File
          image: 'central-docker-release.artif.cc.corp/nginx:1.25.4-alpine'
      serviceAccount: default
      volumes:
        - name: nginx-conf-templates
          configMap:
            name: nginx-conf-templates
            defaultMode: 420
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 420
        - name: cache
          emptyDir: {}
        - name: runtime
          emptyDir: {}
        - name: conf
          emptyDir: {}
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

```yaml
kind: Service
apiVersion: v1
metadata:
  name: thanos-proxy
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: nginx
```

And in Tenant CR for Minio, we use:

```yaml
  env:
    - name: MINIO_PROMETHEUS_URL
      value: 'http://thanos-proxy'
    - name: CONSOLE_PROMETHEUS_URL
      value: 'http://thanos-proxy'
```

Hopefully it helps someone and Opemshift monitoring will be netter supported :-)
