### ISSUE TITLE
invalid Login whenever operator provisioned tenant console is accessed

### ISSUE THREAD

**Issue by gelato** [minio/operator#1945]
## Expected Behavior
Tenant console allows user access with credentials set up during provisioning using operator ui

## Current Behavior
Always getting invalid Login when trying to access console. mc admin works though. I've tried deploying tenant with/without TLS, tried setting MINIO_BROWSER_REDIRECT_URL, my additional domains are also always set. I even tried creating new user through mc admin app and assigning consoleAdmin policy to it - still getting 401 from console (Failed to load resource: the server responded with a status of 401 ()). One thing I can tell - my public domain resolves to local addresses, but don't think that it matters.

## Possible Solution
No clue

## Steps to Reproduce (for bugs)
Deploy MinIO Operator with helm, deploy tenant with setting external domains and turning off service exposure

## Context
I can't login to console

## Regression
No clue

## Your Environment

* Version used (`minio-operator`): 5.0.10
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes Server Version: v1.28.5
* Server type and version: ??
* Operating System and version (`uname -a`): Linux 6.6.6-76060606-generic #202312111032~1702306143~22.04~d28ffec SMP PREEMPT_DYNAMIC Mon D x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file: https://app.assembla.com/spaces/k8s/git-2/source/main/clusters/monolith/infrastructure/minio/values.yaml?_format=raw&disposition=inline

Ingresses from here: https://github.com/minio/operator/blob/master/docs/nginx-ingress.md

**Comment by gelato** [comment]
Figured it myself by deploying outdated version of tenant, which showed much more verbose error messages, instead of just "Invalid login". So my k8s cluster is self-hosted cluster witrh certmanager and enabled TLS. And for tenant to work properly i need to add secret names of my ingress's certificates to tenant yaml config after tenant is created. (there's a set of yaml parameters for that in tenant chart, but nothing in the webui)

**Comment by dharapvj** [comment]
We also faced the same issue.. 

Older minio version .. `RELEASE.2023-05-27T05-56-19Z` gave more verbose error..
`Post "https://tenant_name.svc.k8s_domain_name/": x509: certificate signed by unknown authority`

To fix this issue - we added below config in tenant helm values block.
```
minio-tenant:
  tenant:  
    certificate:
      externalCertSecret:
      - name: minio-TENANT_NAME-certificate
        type: kubernetes.io/tls
```

and we created this secret as below. Replace names appropriately.
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: TENANT-tls
  namespace: TENANT
spec:
  dnsNames:
    - "*.TENANT.svc.cluster.local"
    - "*.TENANT-hl.TENANT.svc.cluster.local"
    - "*.TENANT.TENANT.svc.cluster.local"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-prod
  secretName: minio-TENANT_NAME-certificate

```

This fixed the issue.

@harshavardhana - can we re-open this issue to fix the error message in newer version of minio? New version minio gives only very vague `invalid Login` error message.
