### ISSUE TITLE
[Helm] ClusterRole is missing job.min.io access

### ISSUE THREAD

**Issue by schnapsidee** [minio/operator#1980]
The operator ClusterRole is missing access to the new miniojobs CR.

## Expected Behavior
The operator serviceAccount should have access to all needed CRs

## Current Behavior
operator Logs are being spammed with the following error:
`failed to list *v1alpha1.MinIOJob: miniojobs.job.min.io is forbidden: User "system:serviceaccount:minio-operator:minio-operator" cannot list resource "miniojobs" in API group "job.min.io" at the cluster scope`

## Possible Solution
Add new APIGroup to operator ClusterRole in `helm/operator/templates/operator-clusterrole.yaml`

```yaml
  - apiGroups:
      - minio.min.io
      - sts.min.io
      - job.min.io
    resources:
      - "*"
    verbs:
      - "*"
```

I only installed via Helm, so I'm not sure if other deployment types are affected.

## Steps to Reproduce (for bugs)
1. Install or Update Helm Chart Version 5.0.12
2. Check Operator Logs
