### ISSUE TITLE
Fail to delete console service labels

### ISSUE THREAD

**Issue by TZ-zzz** [minio/operator#2038]
## Expected Behavior
 When the users delete labels from `consoleServiceLabels`, the operator should delete the label from the service.

## Current Behavior
 The operator fails to delete the corresponding labels in the service.

## Possible Solution
 In the function `minioSvcMatchesSpecification`, it checks for each expected label if there is a corresponding label in current state. If we attempt to delete a tag, the function will not be able to correctly detect the label changes that occur. The possible solution could be also check whether there are redundant labels. 

Note that, same bug exists for the `serviceMetadata.consoleServiceAnnotations` property.

## Steps to Reproduce (for bugs)

1. apply an initial CR with some `consoleServiceLabels` 
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: test-cluster
  namespace: minio-operator
  labels:
    app: minio
spec:
  features:
    bucketDNS: false
  users:
    - name: storage-user
  podManagementPolicy: Parallel
  configuration:
    name: storage-configuration
  env: [ ]
  serviceMetadata:
    consoleServiceLabels: 
      LABELKEY: LABELVALUE
    # same bug for consoleServiceAnnotations
  image: quay.io/minio/minio:RELEASE.2024-02-09T21-25-16Z
  mountPath: /export
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: { }
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: standard
        status: { }
  requestAutoCert: true
```
2. remove the labels under `consoleServiceLabels`

## Your Environment

* Version used (`minio-operator`): RELEASE.2024-02-06T21-36-22Z
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.29.2
