### ISSUE TITLE
Fail to add defualt label to console

### ISSUE THREAD

**Issue by TZ-zzz** [minio/operator#2047]
## Expected Behavior

The operator should add a default label to service `xxx-console`.

## Current Behavior

If we apply a CR that omits `consoleServiceLabels` field under `spec.serviceMetadata`, operator will create a service called `xxx-console` without default label. However, if we apply a CR that has the field `consoleServiceLabels` with an empty dictionary, the operator will add the default label to the service. 

## Possible Solution

https://github.com/minio/operator/blob/master/pkg/resources/services/service.go#L90C1-L91C1  At this line, internalLabels are added to the varaible labels only when Spec.ServiceMetadata.ConsoleServiceLabels != nil. There should be an else statement like https://github.com/minio/operator/blob/master/pkg/resources/services/service.go#L38 in the `NewClusterIPForMinIO` function. That is add the following code right after line 91
```
else {
		labels = internalLabels
	}
```
## Steps to Reproduce (for bugs)

1. Simply apply this CR 
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: test-cluster
  namespace: minio-operator
  labels:
    app: minio
spec:
  features:
    bucketDNS: false
  users:
    - name: storage-user
  podManagementPolicy: Parallel
  configuration:
    name: storage-configuration
  env: [ ]
  serviceMetadata: {}
    # if you add consoleServiceLabels : {} here, the operator will add the default label correctly 
  image: quay.io/minio/minio:RELEASE.2024-02-09T21-25-16Z
  mountPath: /export
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        metadata: { }
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: standard
        status: {}
  requestAutoCert: true
```
This will create a service without default label in my case `test-cluster-console` without label `v1.min.io/console": "test-cluster-console`.

## Your Environment

* Version used (`minio-operator`): 5.0.11
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.29.2
