### ISSUE TITLE
ERROR Unable to use the drive /export/data: file access denied: Invalid arguments specified

### ISSUE THREAD

**Issue by Danieloni1** [minio/operator#2064]
Deploying a MinIO tenant with (almost) default configuration on a k8s single node resulted with the following error: 
`kubectl logs -n minio-operator minio-tenant-pool-0-0` ->
`Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)
ERROR Unable to use the drive /export/data: file access denied: Invalid arguments specified`

## Expected Behavior
As the `/export/data` is the default paths from the charts, the user running it with the default configuration should be able to access it.

## Current Behavior
Operator is running as expected with all services defined, but the statefulset of the tenant is not ready, and the tenant pod's logs are as follows:
`Defaulted container "minio" out of: minio, sidecar, validate-arguments (init)
ERROR Unable to use the drive /export/data: file access denied: Invalid arguments specified`

## Steps to Reproduce (for bugs)

Deploy the default helm chart operator, then deploy PVs and storageClass, then the tenants as follows:
PVs and storageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-local 
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  hostPath: /var/lib/connect/minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-local0-minio-tenant-pool-0-0
  labels:
    app: minio
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-local
  hostPath:
    path: /var/lib/connect/minio
```
The tenant:
```
---
# Source: tenant/templates/tenant-configuration.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-env-configuration
  namespace: minio-operator
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
---
# Source: tenant/templates/tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-tenant
  namespace: minio-operator
  labels:
    app: minio
spec:
  image: "quay.io/minio/minio:RELEASE.2024-03-15T01-07-19Z"
  imagePullPolicy: IfNotPresent
  configuration:
    name: minio-tenant-env-configuration
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: minio-local
        spec:
          storageClassName: minio-local
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
  mountPath: "/var/lib/connect/minio"
  subPath: "/data"
  requestAutoCert: true
  features:
    bucketDNS: false
    enableSFTP: false
  podManagementPolicy: Parallel
  prometheusOperator: false
```

## Your Environment
* Version used (`minio-operator`): operator-5.0.14, tenant-5.0.14
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes: Client Version: v1.28.8, Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3, Server Version: v1.28.0
* Operating System and version (`uname -a`): Linux node-0 5.14.0-432.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 20 20:26:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jiuker** [comment]
change your hostpath permission as `minio:minio`

**Comment by chakraborty29** [comment]
For anyone else that might be losing their mind over this issue, I had something similar with the `/export/data` drive not being found on a k8s install, where I was getting the following error:
```
API: SYSTEM.grid
Time: 21:38:56 UTC 04/30/2025
DeploymentID: 66d1e348-006d-4b5a-9453-b839aa227c9f
Error: grid: https://tenant-authentik-pool-0-0.tenant-authentik-hl.authentik.svc.cluster.local:9000 re-connecting to https://tenant-authentik-pool-0-3.tenant-authentik-hl.authentik.svc.cluster.local:9000: dial tcp 10.42.4.126:9000: connect: connection refused (*net.OpError) Sleeping 1.546s (3) (*fmt.wrapError)
       6: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       5: internal/logger/logonce.go:149:logger.LogOnceIf()
       4: internal/grid/connection.go:59:grid.gridLogOnceIf()
       3: internal/grid/connection.go:672:grid.(*Connection).connect.func1()
       2: internal/grid/connection.go:678:grid.(*Connection).connect()
       1: internal/grid/connection.go:275:grid.newConnection.func3()
INFO: Unable to use the drive https://tenant-authentik-pool-0-2.tenant-authentik-hl.authentik.svc.cluster.local:9000/export/data: drive not found, will be retried
INFO: Unable to use the drive https://tenant-authentik-pool-0-3.tenant-authentik-hl.authentik.svc.cluster.local:9000/export/data: drive not found, will be retried
INFO: Waiting for all MinIO sub-systems to be initialize...
INFO: Configured max API requests per node based on available memory: 37
INFO: All MinIO sub-systems initialized successfully in 21.427732ms
INFO: IAM load(startup) finished. (duration: 25.513111ms)
```

This was due to the tenant resource values being lowered than default in the helm values and when I reset the values back to the default, the deployment worked and I was able to get the minio tenant running again:
```
tenant:
...
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
          ephemeral-storage: 500Mi
        limits:
          cpu: 500m
          memory: 512Mi
          ephemeral-storage: 500Mi
```
