### ISSUE TITLE
Change prometheus config from additional scrape config to probe

### ISSUE THREAD

**Issue by dbason** [minio/operator#2067]
**Is your feature request related to a problem? Please describe.**
Our infrastructure is handled with GitOps and as such our Prometheus object is statically defined.  Modifying a global object breaks this pattern.

**Describe the solution you'd like**
Rather than using additional scrape configs would a [Probe](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Probe) be an option?  This should handle the single endpoint nature of cluster metrics.  It might also be nice to include a ServiceMonitor for scraping node metrics

**Describe alternatives you've considered**
We have considered bootstrapping the minio additional scrape config however this would be an anti pattern as the secret and naming is minio specific for a global object

**Additional context**

**Comment by dbason** [comment]
We have manually created a probe to confirm this works:
```yaml
spec:
  authorization:
    credentials:
      key: token
      name: token-secret
    type: Bearer
  jobName: minio-tenant-test-job
  prober:
    path: /minio/v2/metrics/cluster
    scheme: https
    url: minio.test.svc.cluster.local
  targets:
    staticConfig:
      static:
      - minio.test.svc.cluster.local
  tlsConfig:
    ca:
      configMap:
        key: ca.crt
        name: kube-root-ca.crt
```
If this is something that people agree is a good idea I could look at creating a PR for this.  It would need the ability to add arbitrary labels to the probe incase there is a probeSelector on the prometheus
