### ISSUE TITLE
Tenant memory limit

### ISSUE THREAD

**Issue by pasztorl** [minio/operator#2131]
When I create a new tenant and add resources.limits.memory the operator does not set the GOMEMLIMIT and if i start to stress test minio it will be killed by the OOM.
I'v tried to add it with the spec.env in the tenant CRD but it seems this setting not handled by the operator since it not shows in the statefulset.
So I needed to stop the operator then add the env by hand, and it worked, the finally the minio pod not killed by the OOM.
 
## Expected Behavior
The operator should create the GOMEMLIMIT env if the resources.limits.memory set in the tenant CRD.
The operator should add the spec.env contents to the statefulset if set in the CRD.

## Steps to Reproduce (for bugs)
```
apiVersion: minio.min.io/v2
kind: Tenant
...
spec:
  env:
    - name: GOMEMLIMIT
      value: 4GiB
    - name: MINIO_MEMLIMIT
      value: 4GiB
```

I've tested with the latest operator image, and here is the memory stats reported by prometheus(lens)

<img width="699" alt="Screenshot 2024-05-23 at 15 38 03" src="https://github.com/minio/operator/assets/26776276/b2a7d99b-d3d0-4fca-8e6f-78833f5811f0">

The first peek around 14:50 was without the env, then the second test started at 15:25 with 4GiB GOMEMLIMIT. After all it used around 8GiB but there was enough free RAM so OOM not kicked.

After the test the minio is idle but the ram usage was not decreased at all. This is a minio problem?
