### ISSUE TITLE
Ingress subpath blank white page

### ISSUE THREAD

**Issue by ptisma** [minio/operator#2206]
I am trying to expose the minio-operator console through ingress, when exposing on root path` /`, it works normally, UI loads in and asks for JWT token, but when adding a subpath, its not loading properly, it's just a blank white page with 3 picture icons.

```
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: replacepath
  namespace: minio-operator
spec:
 replacePathRegex:
    regex: "^/test(/|$)(.*)"
    replacement: "/${2}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-stage"
    traefik.ingress.kubernetes.io/router.middlewares: "minio-operator-replacepath@kubernetescrd"
  name: minio
  namespace: minio-operator
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - ptisma.online
    - www.ptisma.online
    secretName: ptisma-online-tls
  rules:
  - host: ptisma.online
    http:
      paths:
        - pathType: Prefix
          path: /test/
          backend:
            service:
              name: console
              port:
                number: 9090
  - host: www.ptisma.online
    http:
      paths:
        - pathType: Prefix
          path: /test/
          backend:
            service:
              name: console
              port:
                number: 9090

```
![Screenshot 2024-07-09 110236](https://github.com/minio/operator/assets/65658668/ce1d2d8e-3e7e-4ff4-94be-c5b8012f2183)
