### ISSUE TITLE
MinIOJob does not pull value from secret

### ISSUE THREAD

**Issue by JamesAtIntegratnIO** [minio/operator#2233]
I'm attempting to create an admin user with a MinIOJob, but the secrets are never used. Instead it creates a user of `${USERNAME}`
## Expected Behavior
secrets reference and env vars parsed for values

## Current Behavior
env vars are not parsed and user of ${USERNAME} is created

### job.yaml
[job.yaml](https://github.com/JamesAtIntegratnIO/gitops-homelab/blob/main/gitops/workloads/monitoring-cluster/minio-tenant/manifests/jobs.yaml)
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-job-sa
automountServiceAccountToken: true

---
apiVersion: sts.min.io/v1alpha1
kind: PolicyBinding
metadata:
  name: mc-job-binding
spec:
  application:
    serviceaccount: mc-job-sa
    namespace: minio-tenant
  policies:
    - consoleAdmin
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: minio-tenant
 name: mc-job-sa-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: mc-job-sa-secret-reader-binding
 namespace: minio-tenant
subjects:
- kind: ServiceAccount
  name: mc-job-sa
  namespace: minio-tenant
roleRef:
 kind: Role
 name: mc-job-sa-secret-reader
 apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-admin-policy
data:
  policy.json: |
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Action": [
                    "admin:*"
                ]
            }
        ]
    }
---
apiVersion: job.min.io/v1alpha1
kind: MinIOJob
metadata:
  name: minio-user-creation-job
  namespace: minio-tenant
spec:
  serviceAccountName: mc-job-sa
  tenant: 
    name: default
    namespace: minio-tenant
  commands:
    - name: add-admin-user
      op: admin/user/add
      args:
        user: ${USERNAME}
        password: ${PASSWORD}
      envFrom:
        - secretRef:
            name: minio-tenant-user
    - name: admin-policy-create
      op: admin/policy/create
      args:
        name: admin-access
        policy: /temp/policy.json
      volumeMounts:
        - name: policy
          mountPath: /temp
      volumes:
        - name: policy
          configMap:
            name: mc-admin-policy
            items:
              - key: policy.json
                path: policy.json
    - name: admin-policy-attach
      op: admin/policy/attach
      dependsOn:
        - add-admin-user
        - admin-policy-create
      args:
        user: ${USERNAME}
        policy: admin-access
      envFrom:
        - secretRef:
            name: minio-tenant-user
```

### secret.yaml
```yaml
apiVersion: v1
data:
  PASSWORD: ++++++++
  USERNAME: ++++++++
kind: Secret
metadata:
  annotations:
    operator.1password.io/item-path: vaults/you/dont/need/this/path
    operator.1password.io/item-version: '5'
  creationTimestamp: '2024-07-21T23:04:27Z'
  labels:
    argocd.argoproj.io/instance: minio-tenant
  name: minio-tenant-user
  namespace: minio-tenant
  ownerReferences:
    - apiVersion: onepassword.com/v1
      kind: OnePasswordItem
      name: minio-tenant-user
      uid: 6b4b10ee-970f-46ee-b881-416ca1bb4b55
  resourceVersion: '22002'
  uid: 8f350a9c-4a97-41f3-8964-18e91d1922b9
type: Opaque
```
### Tenant Volume info
```
root@Tower:/mnt/user/kube_storage/minio-tenant-data0-default-default-pool-0-pvc-445099ae-b3e6-440d-8608-0c08bbdc7726/data/.minio.sys/config/iam/users# ls -la
total 3
drwxr-xr-x 1 nobody users 3 Jul 21 17:15 ${USERNAME}/

root@Tower:/mnt/user/kube_storage/minio-tenant-data0-default-default-pool-0-pvc-445099ae-b3e6-440d-8608-0c08bbdc7726/data/.minio.sys/config/iam/users# ls -la \$\{USERNAME\}/
total 3
drwxr-xr-x 1 nobody users 3 Jul 21 17:15 ./
drwxr-xr-x 1 nobody users 3 Jul 21 17:15 ../
drwxr-xr-x 1 nobody users 3 Jul 21 17:15 identity.json/
```

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:
