### ISSUE TITLE
helm release 6.0.1 can't use .tenant.configSecret

### ISSUE THREAD

**Issue by JoKrefting** [minio/operator#2255]
## Expected Behavior

Expectation is, that i can start using .tenant.configSecret on first deployment like in docs:
```
tenant:
  configSecret:
    name: myminio-env-configuration
    accessKey: minio 
    secretKey: minio123
```

## Current Behavior

The current default value in [values.yaml](https://github.com/minio/operator/blob/ccade59dbe074c10855bc4125226954e1d8229ab/helm/tenant/values.yaml#L20)
```
secrets:
  name: myminio-env-configuration
  accessKey: minio 
  secretKey: minio123
```

Results into error:
`Error: execution error at (tenant/templates/tenant-configuration.yaml:5:4): ERROR: '.secrets' and '.tenant.configSecret' are mutually exclusive. Please use 'tenant.configSecret' instead.`

## Possible Solution

Define secrets section to be empty like:
```
secrets: {}
```

Alternative could be adapting the logic within tenant/templates/tenant-configuration.yaml to use e.g. a priorization like:
1. if .tenant.configSecret is defined -> create secret -> ignore possible .secret definition

## Steps to Reproduce (for bugs)

1. run `helm template tenant minio/tenant --set tenant.configSecret.name="myminio-env-configuration" --set tenant.configSecret.accessKey="minio" --set tenant.configSecret.secretKey="minio123" `

## Context

Make use of new secret structure was the goal.
