### ISSUE TITLE
Tenant is getting an empty string from env referencing a secret

### ISSUE THREAD

**Issue by EStork09** [minio/operator#2279]
After upgrading to 6.0.x, the tenant is no longer getting the environment value from the secret.
i.e.
```
spec:
  configuration:
    name: minio-configuration
  env:
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM
      valueFrom:
        secretKeyRef:
          key: client-secret
          name: minio-oidc
```
shows up in the `/tmp/minio/config.env` as `export MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM=""`

## Expected Behavior

`export MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM=""` should be a value and not an empty string.

## Current Behavior

`export MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM=""` is being set as an empty string.

## Possible Solution

I suppose I could look at putting the secret in the config file with the admin credentials, but I would rather keep that clean and just what is needed.

## Steps to Reproduce (for bugs)

1. Update tenant with a environment variable referencing a secret

## Context

My OIDC auth has failed because it is now passing an empty string as teh secret.

## Regression

Yes? v6.0.x

## Your Environment

* Version used (`minio-operator`): 6.0.2
* Environment name and version (e.g. kubernetes v1.17.2): 1.29.4
* Server type and version: container, RELEASE.2024-08-03T04-33-23Z
* Operating System and version (`uname -a`): `Linux rke2-worker-1 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux`
* Link to your deployment file: [values.yaml](https://gitlab.com/navenest/kubernetes/infra-apps/minio/-/blob/main/clusters/rke2/values.yaml?ref_type=heads)
