### ISSUE TITLE
Tenant Helm chart: Confusing use of configuration/configSecret

### ISSUE THREAD

**Issue by stephan2012** [minio/operator#2280]
## Expected Behavior

The current Tenant Helm chart shows a confusing mix of `.tenant.configuration.name` (required by the Operator) and `.tenant.configSecret.name` (required by the Tenant chart). However, both values shall reference the same Kubernetes Secret.

To make the chart work, you have to configure both.

Example:

```yaml
  configuration:
    name: foobar
  configSecret:
    name: foobar
    existingSecret: true
```

## Current Behavior

This is how the template currently looks like:

```yaml
  ###
  # The Kubernetes secret name that contains MinIO environment variable configurations.
  # The secret is expected to have a key named config.env containing environment variables exports.
  configuration:
    name: myminio-env-configuration
  ###
  # Root key for dynamically creating a secret for use with configuring root MinIO User
  # Specify the ``name`` and then a list of environment variables.
  #
  # .. important::
  #
  #    Do not use this in production environments.
  #    This field is intended for use with rapid development or testing only.
  #
  # For example:
  #
  # .. code-block:: yaml
  #
  #    name: myminio-env-configuration
  #    accessKey: minio
  #    secretKey: minio123
  #
  # configSecret:
  #   name: myminio-env-configuration
  #   accessKey: minio
  #   secretKey: minio123
  ###
  # If this variable is set to true, then enable the usage of an existing Kubernetes secret to set environment variables for the Tenant.
  # The existing Kubernetes secret name must be placed under .tenant.configuration.name e.g. existing-minio-env-configuration
  # The secret must contain a key ``config.env``.
  # The values should be a series of export statements to set environment variables for the Tenant.
  # For example:
  #
  # .. code-block:: shell
  #
  #    stringData:
  #       config.env: |-
  #         export MINIO_ROOT_USER=ROOTUSERNAME
  #         export MINIO_ROOT_PASSWORD=ROOTUSERPASSWORD
  #
  #   existingSecret: false
```

## Possible Solution

Unify both by going for `.tenant.configuration.name` only.

## Steps to Reproduce (for bugs)

See chart.

## Context

Upgrading chart from v5.x to v6.0.2.

## Regression
No.

## Your Environment

* Version used (`minio-operator`): v6.0.2
* Environment name and version (e.g. kubernetes v1.17.2): v1.29.7
* Server type and version: Debian GNU/Linux 12 (Bookworm)
* Operating System and version (`uname -a`): `Linux n0251 6.9.7+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.7-1~bpo12+1 (2024-07-03) x86_64 GNU/Linux`
* Link to your deployment file: N/A

(Possibly) Related: #2255, #2279
