### ISSUE TITLE
MinIOJob Tenant service endpoint wrong if Tenant is in other namespace

### ISSUE THREAD

**Issue by chrmang** [minio/operator#2293]
I want to run a MinIOJob to create users and buckets in a different namespace than Tenant.
I followed documentation https://github.com/minio/operator/blob/master/docs/minio-job.md for creating resources
and https://min.io/docs/minio/kubernetes/upstream/developers/sts-for-operator.html to configure it for cross namespace.

access with mc works without any issues.

Based on the fix for https://github.com/minio/operator/issues/2290 I tried it again, but found an other issue.

**The Jobs started from MinIOJob are trying to access the wrong endpoint:**
The error message of the Pod is:
`mc: <ERROR> Unable to make bucket 'myminio/dev'. Put "http://minio.dev.svc.cluster.local/dev/": dial tcp: lookup minio.dev.svc.cluster.local on 10.96.0.10:53: no such host` 

The Tenant is in namespace `minio-tenant`. The used endpoint should be `minio.minio-tenant.svc.cluster.local`

The configuration is the same as in https://github.com/minio/operator/issues/2290:

### namespace minio-tenant

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: mytenant
  namespace: minio-tenant
spec:
  requestAutoCert: false
  env:
    - name: MINIO_DOMAIN
      value: <set according to doc>
    - name: MINIO_BROWSER_REDIRECT_URL
      value: <set according to doc>
    - name: MINIO_SERVER_URL
      value: <set according to doc>
  configuration:
    name: tenant-config
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
```

```yaml
apiVersion: sts.min.io/v1alpha1
kind: PolicyBinding
metadata:
  name: minio-job
  namespace: minio-tenant
spec:
  application:
    serviceaccount: minio-job
    namespace: dev
  policies:
    - consoleAdmin
```

### namespace dev (using minio-tenant)

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-job
  namespace: dev
```

```yaml
apiVersion: job.min.io/v1alpha1
kind: MinIOJob
metadata:
  name: minio-job
  namespace: dev
spec:
  #  mcImage: quay.io/minio/mc:latest
  serviceAccountName: minio-job
  securityContext: {}
  containerSecurityContext: {}
  tenant:
    name: mytenant
    namespace: minio-tenant
  commands:
    - name: create-bucket
      op: make-bucket
      args:
        name: dev
```

## Expected Behavior
The Job startet from MinIOJob using the service endpoint in Tenant namespace from `spec.tenant.namespace`

## Current Behavior
The Jobs are trying to use the service endpoint in MinIOJob namespace and failing to connect.
`mc: <ERROR> Unable to make bucket `myminio/dev`. Put "http://minio.dev.svc.cluster.local/dev/": dial tcp: lookup minio.dev.svc.cluster.local on 10.96.0.10:53: no such host` 

## Steps to Reproduce (for bugs)
Apply provided config to 2 namespaces.

## Your Environment
* MinIO operator: `kubectl apply -k https://github.com/minio/operator?ref=v6.0.3`
* Kubernetes v1.30.3
* Operating System and version (`uname -a`):
  `Linux storebot 6.6.0-odroid-arm64 #1 SMP PREEMPT Wed, 08 May 2024 07:36:13 +0000 aarch64 aarch64 aarch64 GNU/Linux`
