### ISSUE TITLE
helm: tenant: Regression on tenant.configSecret.existingConfiguration

### ISSUE THREAD

**Issue by ClemaX** [minio/operator#2297]
Setting `tenant.configSecret.existingConfiguration` to `true` has no effect.

## Expected Behavior

The default `myminio-env-configuration` should not be created if the `existingConfiguration` parameter is `true`

## Current Behavior

The default `myminio-env-configuration` is created.

## Possible Solution

Add an `if` condition to create the secret unless the parameter is set.
 
## Steps to Reproduce (for bugs)

1. Create values.yaml
```sh
cat > values.yaml <<EOF
tenant:
  configuration:
    name: custom-minio-env
  configSecret:
    name: custom-minio-env
    existingSecret: true
EOF
```
3. Install with dry-run
```sh
helm install \
  -n minio --create-namespace \
  --values values.yaml \
  minio-test minio-operator/tenant \
  --dry-run
```
4. Inspect the output

You can see that the `Secret` is part of the output:
```yaml
# Source: tenant/templates/tenant-configuration.yaml
apiVersion: v1
kind: Secret
metadata:
  name: custom-minio-env
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
```

## Context

Providing a custom preexisting secret.

## Regression

Regression from #2265 

## Your Environment

* Version used (`minio-operator`): `6.0.3`
