### ISSUE TITLE
host 127.0.0.1:9000: server update failed with: open /usr/bin/.minio.check-perm: permission denied, do not restart the servers yet

### ISSUE THREAD

**Issue by pschichtel** [minio/operator#2305]
I tried upgrading to MinIO `RELEASE.2024-08-29T01-40-52Z` (from `RELEASE.2024-08-17T01-24-54Z`) using operator 6.0.3 on my single-node home lab after #2229 has been fixed in recent images, just to hit a new issue: The operator seems to be unable to update the image due to failing a permission check, the operator logs `host 127.0.0.1:9000: server update failed with: open /usr/bin/.minio.check-perm: permission denied, do not restart the servers yet` and also sets that as the tenant's currentState.

This currently prevents me from upgrading at all.

## Expected Behavior
Operator upgrades the tenant.

## Current Behavior
Tenant repeatedly switches between the states `host 127.0.0.1:9000: server update failed with: open /usr/bin/.minio.check-perm: permission denied, do not restart the servers yet` and `Updating MinIO Version`. The STS also hasn't been touched.

## Possible Solution
No clue

## Steps to Reproduce (for bugs)

1. Deploy single node k0s with operator 6.0.3 and MinIO `RELEASE.2024-08-17T01-24-54Z`
2. Update the Tenant to version `RELEASE.2024-08-29T01-40-52Z`

## Context
This prevents me form upgrading.

## Regression
y

## Your Environment

* Version used (`minio-operator`): 6.0.3
* Environment name and version (e.g. kubernetes v1.17.2): `v1.30.4+k0s`
* Server type and version: `RELEASE.2024-08-17T01-24-54Z`
* Operating System and version (`uname -a`): `Linux server 6.10.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000 x86_64 GNU/Linux`
* Link to your deployment file: n/a

**Comment by pschichtel** [comment]
I can't find `/usr/bin/.minio.check-perm` in other the tenant or the operator containers, but I guess it might be temporary.

**Comment by pschichtel** [comment]
@jiuker this is how I configure the tenant chart:

```yaml
tenant:
    name: tenant-name
  image:
    tag: 'RELEASE.2024-08-17T01-24-54Z' # updated to 'RELEASE.2024-08-29T01-40-52Z'
  configuration:
    name: env-configuration
  configSecret:
    name: env-configuration
  pools:
  - servers: 1
    name: pool-0
    volumesPerServer: 1
    size: 200Gi
  metrics:
    enabled: true
  certificate:
    requestAutoCert: false
  env:
  - name: MINIO_DOMAIN
    value: "s3.example.org"
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "https://console.s3.example.org"
  - name: MINIO_SERVER_URL
    value: "https://s3.example.org"
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: public
  prometheusOperator: true
ingress:
  api:
    enabled: true
    host: s3.example.org
    tls:
    - hosts:
      - s3.example.org
      secretName: tenant-api-tls
  console:
    enabled: true
    host: console.s3.example.org
    tls:
    - hosts:
      - console.s3.example.org
      secretName: tenant-console-tls
```
