### ISSUE TITLE
ScrapeConfig is not pushed to PrometheusAgent objects

### ISSUE THREAD

**Issue by stijzermans** [minio/operator#2311]
**Is your feature request related to a problem? Please describe.**
When using Prometheus in [Agent mode](https://prometheus.io/blog/2021/11/16/agent/), scrape configs are not pushed by the operator. The operator logs the following message:

```
main-controller.go:1546] error syncing 'infra-minio/minio': prometheuses.monitoring.coreos.com "prometheus-grafana-kube-pr-prometheus" not found
```

My prometheus is running with the following deployment.
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-grafana-kube-pr-prometheus
  namespace: infra-monitoring
spec:
  ...
```

Operator is configured as following:
```yaml
  values:
    operator:
      env:
        - name: PROMETHEUS_NAMESPACE
          value: "infra-monitoring"
        - name: PROMETHEUS_NAME
          value: "prometheus-grafana-kube-pr-prometheus"
        - name: WATCHED_NAMESPACE
          value: "infra-minio"
```

When running the operator with the same configuration, but Prometheus running as `kind: Prometheus`, it does work as expected.

**Describe the solution you'd like**
Both `prometheuses.monitoring.coreos.com` and `prometheusagents.monitoring.coreos.com` should be considered when searching for `PROMETHEUS_NAME` and pushing scraping config, not just `prometheuses.monitoring.coreos.com`

**Describe alternatives you've considered**
Using manual deployment of a probe (such as https://github.com/minio/operator/issues/2067) or a manual scrape config, but this removes the purpose of this functionality to dynamically provision this.

Can also mount the `additionalScrapeConfigsSecret` on PrometheusAgent, but that is be limited to a single scrape config secret.
