### ISSUE TITLE
Existing secret config.env doens't work

### ISSUE THREAD

**Issue by D1StrX** [minio/operator#2328]
## Expected Behavior
Only the existing secret should exist when `tenant.configSecret.existingSecret:` `true`.

## Current Behavior
When `tenant.configSecret.existingSecret:` `true` and `tenant.configuration.name:` `<secret name>`, there shouldn't be a secret created by MinIO. Yet in ArgoCD I can see that configSecret creates the default secret, despite `existingSecret = true`. The other secret is deployed by a SealedSecret, which should be the only one existing.

## Possible Solution
Helm values should probably be looked after. Not sure where the problem lies.

## Steps to Reproduce (for bugs)
Create a tenant with this config specifically, deployed by ArgoCD:
The existing secret is for example deployed with SealedSecrets.

```
  configuration:
    name: <secret>
  configSecret:
    existingSecret: true
```

Then you can clearly see 2 secrets are created. One by MinIO, one by SealedSecrets.

## Context
Locks you out of your MinIO instance and Bucket creation fails with error `buckets creation failed: The Access Key Id you provided does not exist in our records.`

## Regression
Yes, since 6.0.0 due to secret deprecation.

## Your Environment
* Version used (`minio-operator`): 6.0.3
* Environment name and version (e.g. kubernetes v1.17.2): K8s 1.30

**Comment by ravindk89** [comment]
@D1StrX this may be resolved in 6.0.4 based on another user report - @harshavardhana @pjuarezd we need to cut that release fully

**Comment by D1StrX** [comment]
@ravindk89 Updated to v6.0.4. Another issue arise:  `...failed exit status 1: Error: execution error at (tenant/templates/tenant-configuration.yaml:21:4): # ERROR: cannot set access-key when an existing secret is used Use --debug flag to render out invalid YAML`
I tried this:
```yaml
  configuration:
    name: <secret>
  configSecret:
    existingSecret: true
 ```
and tried
```yaml
  configuration:
    name: <secret>
  configSecret:
    name: <secret>
    existingSecret: true
 ```
 
 and tried
```yaml
  configSecret:
    name: <secret>
    existingSecret: true
 ```

**Comment by D1StrX** [comment]
Apparently `tenant/templates/tenant-configuration.yaml` expects this, empty `accessKey` and `secretKey`:

```yaml
  configuration:
    name: <secret>
  configSecret:
    name: <secret>
    accessKey:
    secretKey:
    existingSecret: true
 ```
 Makes sense with the default `values.yaml`... it contains `minio` and `myminio123`

**Comment by D1StrX** [comment]
Another issue arise:

`host <pool>.<tenant>-hl.<namespace>.svc.cluster.local:9000: server update failed with: open /usr/bin/.minio.check-perm: permission denied, do not restart the servers yet`

**Comment by D1StrX** [comment]
Here we go:

```yaml
# Root key for MinIO Tenant Chart
tenant:
  name: example
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2024-10-02T17-50-41Z
    pullPolicy: IfNotPresent
  imagePullSecret: {}
  scheduler: {}
  configuration:
    name: minio-example-env-configuration
  configSecret:
    accessKey:
    secretKey:
    name: minio-example-env-configuration
    existingSecret: true
  pools:
    - servers: 4
      name: pool-0
      volumesPerServer: 2
      size: 15Gi
      storageClassName: standard
      storageAnnotations: {}
      annotations: {}
      labels: {}
      tolerations: []
      nodeSelector: []
      affinity: {}
      resources: {}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: true
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      topologySpreadConstraints: []
  mountPath: /export
  subPath: /data
  metrics:
    enabled: false
    port: 9000
    protocol: http
  certificate:
    externalCaCertSecret: []
    externalCertSecret:
      - name: external-minio-certificate
        type: kubernetes.io/tls
    requestAutoCert: false
    certConfig: {}
  features:
    bucketDNS: false
    domains: {}
    enableSFTP: false
  buckets:
    - name: example-bucket
  users:
    - name: example-user

  podManagementPolicy: Parallel
  liveness: {}
  readiness: {}
  startup: {}
  lifecycle: {}
  exposeServices: {}
  serviceAccountName: ""
  prometheusOperator: false
  logging: {}
  serviceMetadata: {}
  env:
    - name: MINIO_STORAGE_CLASS_STANDARD
      value: EC:2
    - name: MINIO_SITE_REGION
      value: <region>
  priorityClassName: ""
  additionalVolumes: []
  additionalVolumeMounts: []
# Set the keys to conform to the Ingress controller and configuration of your choice.
ingress:
  api:
    enabled: false
  console:
    enabled: true
    ingressClassName: "controller"
    labels:
      service: minio-console
    annotations:
      cert-manager.io/cluster-issuer: <issuer>
      nginx.org/ssl-services: "example-console"
      nginx.org/websocket-services: "example-console"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/proxy-body-size: "5t"
      nginx.org/client-max-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        chunked_transfer_encoding off;
    tls:
      - hosts:
          - console.domain.tld
        secretName: minio-console-tls-secret
    host: console.domain.tld
    path: /
    pathType: Prefix
```

By coincidence related to #2319 and #2305 ?
