### ISSUE TITLE
Issue: Invalid Login Error in Tenant Console

### ISSUE THREAD

**Issue by ntqp97** [minio/operator#2377]
**Expected Behavior**
The login to the MinIO Tenant Console should succeed when valid credentials are provided
**Current Behavior**
Attempting to log in to the Tenant Console results in an Invalid Login error, even when valid credentials are used. (minio/minio123)
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/efbcdeb4-83bf-4ec7-85a2-5c4347f94ee9" />
**Steps to Reproduce (for bugs)**
Deploy MinIO Operator with the following configuration:

```
operator:
  env:
    - name: OPERATOR_STS_AUTO_TLS_ENABLED
      value: "off"
    - name: OPERATOR_STS_ENABLED
      value: "on"

```
Deploy MinIO Tenant using the configuration below:

```
tenant:
  name: tenant0
  features:
    bucketDNS: false
    domains:
      console: https://minio-console.domain
  pools:
    - name: pool-0
      size: 20Gi
  certificate:
    requestAutoCert: false
    externalCertSecret:
      - name: tenant0-tls
        type: cert-manager.io/v1
  env:
    - name: MINIO_SERVER_URL
      value: "http://tenant0-hl.minio-tenant.svc.cluster.local:9000"
    - name: MINIO_BROWSER_REDIRECT_URL
      value: "https://minio-console.domain"
```
Access the Tenant Console at https://minio-console.domain.
Enter valid credentials and observe the error message.
**Context**
This issue prevents users from accessing the MinIO Tenant Console, blocking management operations and potentially impacting workflows that depend on console accessibility.
**Version**
minio-operator: v6.0.4
minio-tenant: v6.0.4
kubernetes: v1.24.17
