### ISSUE TITLE
Ingress broke after Nginx Ingress Controller update 1.12.0

### ISSUE THREAD

**Issue by sim500** [minio/operator#2383]
## Expected Behavior
The ingresses of the console and the api server should work properly, managing HTTPS requests from the outside and proxy them to the HTTPS minio backend service.

## Current Behavior
Using minio-operator and minio-tenant v6.0.4, both installed with helm.
After the latest upgrade of Nginx Ingress Controller to the application version 1.12.0, we are encountering issues with the annotations specified here https://github.com/minio/operator/blob/master/docs/nginx-ingress.md, that are the following:
``` yaml
  nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  nginx.ingress.kubernetes.io/configuration-snippet: |
    chunked_transfer_encoding off;
  nginx.ingress.kubernetes.io/proxy-body-size: "0"
  nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
  nginx.ingress.kubernetes.io/rewrite-target: /
  nginx.ingress.kubernetes.io/server-snippet: |
        client_max_body_size 0;
        # Deny access to the cluster metrics endpoint
        location = /minio/v2/metrics/cluster {
                                  deny all;
                                  return 403;
                                }
```

Issuing a request towards an ingress configured in this way, now return a 404 error from nginx. The Nginx Ingress Controller doesn't log any specific error, other then the warning: 
`annotation group ConfigurationSnippet contains risky annotation based on ingress configuration`
It's not clear which one of those annotations cause this malfunction, and I'm not sure if they're all necessary for the correct functioning of minio.

## Possible Solution
After understanding which nginx annotations are causing the issue, removing or editing some of them should fix the problem

## Steps to Reproduce (for bugs)
1. Remove all those annotations, the Ingress is able to contact the backend minio service, responding:
    "_Client sent an HTTP request to an HTTPS server."_
2. Add all the annotations again, the Ingress continues to work, still responding
    "_Client sent an HTTP request to an HTTPS server_." 
Which is weird since now there's the `nginx.ingress.kubernetes.io/backend-protocol: HTTPS` annotation there.
3. Remove all of them again, except for these two:
``` yaml 
nginx.ingress.kubernetes.io/backend-protocol: HTTPS
nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
```

Now you finally receive an _Access Denied_ from the actual minio backend.
Add again all the other annotation and it should continue to work fine.

## Context
Both Minio backend and console are not accessible from the outside

## Your Environment
k8s version: **1.31**
**minio-operator** and **minio-tenant** versions: **v6.0.4**, both installed with helm
Nginx Ingress Controller version: **1.12.0**
