### ISSUE TITLE
Minio operator allows to run single node single server setup

### ISSUE THREAD

**Issue by L1ghtman2k** [minio/operator#2389]
## Expected Behavior
Based on the https://github.com/minio/operator/issues/457, and comments, I would expect the operator not to support single node single drive configuration

## Current Behavior
The operator allows a single server, with single volume to be created
I am not sure if this is intended or supported. I also notice that certain features like bucket versioning advertised to only work for standalone minio also work on this minio. I can't tell if this minio considers itself standalone or distributed.

## Possible Solution
I don't know.

## Steps to Reproduce (for bugs)

1. Create following config(dummy creds):
```
apiVersion: v1
data:
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj1taW5pbwpleHBvcnQgTUlOSU9fUk9PVF9QQVNTV09SRD0ib3pqRTlDTmpTQlVVNjY4WHlsWUkzTFJtSCIK
immutable: false
kind: Secret
metadata:
  name: minio-creds
  namespace: tes
type: Opaque
```
2. Create tenant with the following spec:
```
  spec:
    buckets:
    - name: test
    configuration:
      name: minio-creds
    features:
      bucketDNS: false
      enableSFTP: false
    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
    imagePullPolicy: IfNotPresent
    mountPath: /export
    podManagementPolicy: Parallel
    pools:
    - containerSecurityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      name: pool-0
      resources:
        limits:
          cpu: 4
          memory: 10Gi
        requests:
          cpu: 0
          memory: 0
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      volumesPerServer: 1
    prometheusOperator: false
    requestAutoCert: true
    subPath: /data
```

## Regression
 (Possible)
