### ISSUE TITLE
MinIO Operator v7.0.0 doesn't inherit annotations from the Tenant resource to the created Pods

### ISSUE THREAD

**Issue by jorijn** [minio/operator#2393]
MinIO Operator v7 doesn't inherit annotations from the Tenant resource to the created Pods.

## Expected Behavior
In v6.0.4, the operator copies the labels and annotations from the Tenant resource to the created Pods.

## Current Behavior
From v7.0.0 this behavior is broken. The annotations are not added to the Pods.

## Context
We use Kyverno to mutate the Pod objects before they are created, based on the presence of certain annotations.

## Your Environment
* Version used (`minio-operator`): v7.0.0
* Environment name and version (e.g. kubernetes v1.17.2): v0.32.7
* Server type and version: Talos Linux

## Snippet from the Tenant
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio-tenant
  annotations:
    inject-certs: enabled
    inject-certs-path: /tmp/certs/CAs/ # https://github.com/minio/minio/blob/master/docs/tls/README.md#4-install-certificates-from-third-party-cas
```

**Comment by ramondeklein** [comment]
You should be able to use `.tenant.poolsMetadata.annotations` to set annotations on the statefulset, pods, ...

**Comment by jorijn** [comment]
Hi @ramondeklein - thanks. I didn't know this was bugged behavior, as I noticed this somewhere in the documentation as a feature.

Should anyone find this issue, the corrected spec should look like:

```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio-tenant
spec:
  # [...]
  poolsMetadata:
    annotations:
      inject-certs: enabled
      inject-certs-path: /tmp/certs/CAs/ # https://github.com/minio/minio/blob/master/docs/tls/README.md#4-install-certificates-from-third-party-cas
```
