### ISSUE TITLE
Unable to login to MinIO console due to network error

### ISSUE THREAD

**Issue by alita1991** [minio/operator#2420]
## Expected Behavior

`kubectl port-forward -n integration services/minio-multi-node-console 9090`

Authentication with username / password should be successful.

## Current Behavior

`unable to login due to network error`

## Possible Solution

After I delete the MinIO pods, I can access the MinIO console

## Steps to Reproduce (for bugs)

1. Deploy MinIO tenant
2. Create / Delete Buckets + Objects
3. Try to access the MinIO console

## Context

I want to access the MinIO console to verify the buckets

### Tenant config

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-multi-node
spec:
  image: "quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z"
  imagePullPolicy: Always
  requestAutoCert: false
  buckets:
    - name: bucket-one
  configuration:
    name: minio-tenant-config
  pools:
    - servers: 4
      name: pool
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 60Gi
```

## Your Environment
* Version used (`minio-operator`): v7.0.1
* Environment name and version (e.g. kubernetes v1.17.2): v1.30.10-eks-bc803b4
