### ISSUE TITLE
Tenant imagePullPolicy does not apply for default sidecar container and initContainer

### ISSUE THREAD

**Issue by alexifsp** [minio/operator#2434]
When setting imagePullPolicy: always on Tenant, the configuration is not applied to default `sidecar` container and `validate-arguments` initContainer created by default with minio pods.

## Expected Behavior

A tenant setting should apply to all default components created by the tenant/allow configuration of this components.

## Current Behavior

Although configured, some configurations do not propagate also to `sidecar` and `validate-arguments` default containers created:

```yaml
    apiVersion: minio.min.io/v2
    kind: Tenant
    metadata:
      name: minio-multi-node
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      imagePullPolicy: Always
      requestAutoCert: false
      configuration:
        name: minio-tenant-config
      imagePullSecret:
        name: minio-pull-secret
      pools:
        - servers: 3
          name: pool
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 500Mi
            limits:
              cpu: "400m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
          securityContext:
            runAsUser: 10001  
            fsGroup: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - ALL
          volumesPerServer: 2
          volumeClaimTemplate:
            metadata:
              name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 60Gi
```
