### ISSUE TITLE
Helm Tenant Template - Does not use Release.Namespace - Installs into Default namespace

### ISSUE THREAD

**Issue by ktersius** [minio/operator#2453]
This might be me just not knowing how to configure it correctly but following the helm install documentation does not result in the namespace being set correctly. This results in a tenant definition in the default namespace and the operator creating a tenant pods in the default namespace.

helm template --namespace 123-respect  --create-namespace tenant minio/tenant
```
...
---
# Source: tenant/templates/tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
spec:
...
```
Expected:
```
...
---
# Source: tenant/templates/tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  namespace: 123-respect
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
spec:
...
```
