### ISSUE TITLE
Changing metrics endpoint to public does not trigger update from operator

### ISSUE THREAD

**Issue by alexifsp** [minio/operator#2455]
When trying to add public endpoint on a pre-existing tenant with:

```yaml
      env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
```

Operator does not trigger an update and endpoint remains still with authentication.

## Expected Behavior

Updating Tenant configuration should trigger operator updates.

## Current Behavior

As explained above, when issuing an update on spec.env in a Tenant, the operator does not trigger any patches.
I have to delete the Tenant and recreate it to be able to make the metrics endpoint public.
Should mention, this process is performed via ArgoCD but in theory a helm update on the object should trigger same problem. (or a new kubectl apply of Tenant)
