### ISSUE TITLE
Tenant Helm chart does not inject `sideCars` configuration

### ISSUE THREAD

**Issue by ThoSap** [minio/operator#2465]
I installed the Helm `operator` 7.1.1 and just wanted to launch a `tenant` with our custom sidecar, but found out that the `operator` CRD supports `sideCars`, but the `tenant` Helm chart does not inject that YAML snippet.

See PR #2466
See the `minio.min.io/Tenant` CRD description: https://github.com/minio/operator/blob/60303adec7af7eb9426de8a53f2c538ae2d3dbc4/docs/tenant_crd.adoc#sidecars

## Expected Behavior

The Helm chart `tenant` should support `sideCars`.

## Current Behavior

The `values.yml` `sideCars` block is ignored when the `tenant` Helm chart is installed.

## Possible Solution

See PR https://github.com/minio/operator/pull/2466

## Steps to Reproduce (for bugs)

See also the PR #2466 `tenant` `values.yml` description example.

1. Add for example the following side car to the `tenant` chart `values.yml`
```yml
spec:
  # ... other configs omitted
  sideCars:
    containers:
      - name: minio-test-sidecar
        image: minio/mc:RELEASE.2025-05-21T01-59-54Z
        imagePullPolicy: IfNotPresent
        command: ["sleep"]
        args: ["infinity"]
        env:
          - name: MC_CONFIG_DIR
            value: /tmp/.mc
          - name: MC_HOST_k8slocal
            value: http://your_root_user:your_root_password@your-minio-tenant-hl.your-minio-ns.svc.cluster.local:9000
```

2. Install the chart and the resulting `minio.min.io/Tenant` instance yaml will not include the sidecar

## Context

I created my custom sidecar that gets a config from a secret that reconciliates the service accounts using the MinIO Console `mc`.
When I manually add the `sideCars` block to the resulting `minio.min.io/Tenant` instance yaml spec, the sidecar just works fine.

## Your Environment

* Version used (`minio-operator`): 7.1.1
* Environment name and version (e.g. kubernetes v1.17.2): 1.32.5
* Server type and version: Rancher v2.11.1 + K3s v1.32.5+k3s1
* Operating System and version (`uname -a`): Linux app-6fccc6f7d5-l5cd6 6.8.0-60-generic 63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 Linux
