### ISSUE TITLE
More documentation on tenant expansion

### ISSUE THREAD

**Issue by Magoli1** [minio/operator#285]
**Is your feature request related to a problem? Please describe.**
When reading the documentation I came along the tenant expansion process described [here](https://github.com/minio/operator/blob/master/docs/expansion.md). I wonder if the described downtime is still happening, as #150 seems like a fix to that? If I understand correctly, the tenant expansion will add a new zone. How does this lead to a downtime?

**Describe the solution you'd like**
I would really appreciate if you could elaborate a little more on the provided questions/topics and or describe possible (manual) processes on how to get rid of the downtime.

Please let me know in case of any inconsistencies in my thinking. 👍 
If you have more info, I would also be open to opening a PR for enhancing the documentation based on you answer.

Let me know your thoughts 🚀 

Best Regards
Robert

**Comment by dvaldivia** [comment]
We do have a new hot expansion feature that adds the new zone with almost zero downtime, we may need to update the documentation to reflect that, please do give it a try and observe how the pods MinIO process restart without actually killing the pod after a zone has been added

**Comment by tobernguyen** [comment]
> We do have a new hot expansion feature that adds the new zone with almost zero downtime, we may need to update the documentation to reflect that, please do give it a try and observe how the pods MinIO process restart without actually killing the pod after a zone has been added

I'm seeing a new Statefulset is created for the new zone, and then the rolling update happens for the existing zone. There is still a considerable amount of downtime from what I'm seeing. My setup is a tenant with 4 servers, 1 disk each server then I added a new zone with the exact same config (4 servers, 1 disk each server). The method of adding a new zone is to modify the existing Tenant CR and deploy it. I believe the `kubectl minio` does the same (patching the CR).

**Comment by harshavardhana** [comment]
> I'm seeing a new Statefulset is created for the new zone, and then the rolling update happens for the existing zone. There is still a considerable amount of downtime from what I'm seeing. My setup is a tenant with 4 servers, 1 disk each server then I added a new zone with the exact same config (4 servers, 1 disk each server). The method of adding a new zone is to modify the existing Tenant CR and deploy it. I believe the `kubectl minio` does the same (patching the CR).

Using statefulset outisde of operator is doesn't support hot expansion @tobernguyen

**Comment by tobernguyen** [comment]
> > I'm seeing a new Statefulset is created for the new zone, and then the rolling update happens for the existing zone. There is still a considerable amount of downtime from what I'm seeing. My setup is a tenant with 4 servers, 1 disk each server then I added a new zone with the exact same config (4 servers, 1 disk each server). The method of adding a new zone is to modify the existing Tenant CR and deploy it. I believe the `kubectl minio` does the same (patching the CR).
> 
> Using statefulset outisde of operator is doesn't support hot expansion @tobernguyen

Sorry if I didn't state it clearly but I'm not using anything outside the operator. I just changed the Tenant CR definition. Here are the steps:

1. Deploy a new MinIO Tenant with just one zone of 4 servers, 1 disk each server
  ```yaml
  apiVersion: minio.min.io/v1
  kind: Tenant
  ...
  spec:
    zones:
      - servers: 4
        volumesPerServer: 1
        volumeClaimTemplate:
          metadata:
            name: minio-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
  ...
  ```
2. Create a small program to constantly write new files to bucket and run it
  ```zsh
  while :; do
    random_file=$(mktemp)
    head -c 1000000 /dev/urandom > $random_file
    mc cp $random_file cluster/bucket2
    sleep 0.1
  done
  ```
3. Modify the CR to add a new zone with exactly same config
  ```yaml
  apiVersion: minio.min.io/v1
  kind: Tenant
  ...
  spec:
    zones:
      - servers: 4
        volumesPerServer: 1
        volumeClaimTemplate:
          metadata:
            name: minio-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
      - servers: 4
        volumesPerServer: 1
        volumeClaimTemplate:
          metadata:
            name: minio-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
  ...
  ```
4. Deploy the CR with `kubectl apply -f cr.yaml`
5. The operator started to do its things from adding a new statefulset, and rolling update the existing statefulset. 
6. I noticed the write to bucket get interrupted with error like this
```
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.EOdKIO`. Insufficient permissions to access this file `http://minio-simple-cluster/bucket2/tmp.EOdKIO`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 536.54 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.CMBCNH` -> `cluster/bucket2/tmp.CMBCNH`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.CMBCNH`. 503 Service Unavailable
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.ejoKFG` -> `cluster/bucket2/tmp.ejoKFG`
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.ejoKFG`. 503 Service Unavailable
```
7. Take about 2-3 mins for the program to be able to write new files again.

**Comment by harshavardhana** [comment]
> ```
> minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.EOdKIO`. Insufficient permissions to access this file `http://minio-simple-cluster/bucket2/tmp.EOdKIO`
> minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 536.54 KiB/s
> minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.CMBCNH` -> `cluster/bucket2/tmp.CMBCNH`
> minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
> minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.CMBCNH`. 503 Service Unavailable
> minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.ejoKFG` -> `cluster/bucket2/tmp.ejoKFG`
> minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.ejoKFG`. 503 Service Unavailable
> ```
> 
> 
> 
> 1. Take about 2-3 mins for the program to be able to write new files again.

I don't think this makes sense @tobernguyen so looks like there is some other setup issue here.

**Comment by tobernguyen** [comment]
> > ```
> > minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.EOdKIO`. Insufficient permissions to access this file `http://minio-simple-cluster/bucket2/tmp.EOdKIO`
> > minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 536.54 KiB/s
> > minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.CMBCNH` -> `cluster/bucket2/tmp.CMBCNH`
> > minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
> > minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.CMBCNH`. 503 Service Unavailable
> > minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.ejoKFG` -> `cluster/bucket2/tmp.ejoKFG`
> > minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.ejoKFG`. 503 Service Unavailable
> > ```
> > 
> > 
> > 
> > 1. Take about 2-3 mins for the program to be able to write new files again.
> 
> I don't think this makes sense @tobernguyen so looks like there is some other setup issue here.

What doesn't make sense?

Here is my full Tenant configuration
```yaml
```

**Comment by tobernguyen** [comment]
> > ```
> > minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.EOdKIO`. Insufficient permissions to access this file `http://minio-simple-cluster/bucket2/tmp.EOdKIO`
> > minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 536.54 KiB/s
> > minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.CMBCNH` -> `cluster/bucket2/tmp.CMBCNH`
> > minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
> > minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.CMBCNH`. 503 Service Unavailable
> > minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.ejoKFG` -> `cluster/bucket2/tmp.ejoKFG`
> > minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.ejoKFG`. 503 Service Unavailable
> > ```
> > 
> > 
> > 
> > 1. Take about 2-3 mins for the program to be able to write new files again.
> 
> I don't think this makes sense @tobernguyen so looks like there is some other setup issue here.

What doesn't make sense?

Here is my full Tenant configuration
```yaml
## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'minio' | base64)
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'minio123' | base64)
  secretkey: bWluaW8xMjM=
---
## MinIO Tenant Definition
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio-simple-cluster
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio-simple-cluster
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"

## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
## If not specified, the Tenant pods will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler

spec:
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2020-09-23T19-18-30Z
  imagePullPolicy: IfNotPresent

  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio-creds-secret

  ## Specification for MinIO Zone(s) in this Tenant.
  zones:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this zone.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 4

      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      ## Total cluster capacity is numberOfVolumes * volumeSize
      volumesPerServer: 1

      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this 
      ## Zone.
      volumeClaimTemplate:
        metadata:
          name: minio-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi

    - servers: 4
      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      ## Total cluster capacity is numberOfVolumes * volumeSize
      volumesPerServer: 1

      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this 
      ## Zone.
      volumeClaimTemplate:
        metadata:
          name: minio-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
      
      ## Used to specify a toleration for a pod
      # tolerations:
      #  - effect: NoSchedule
      #    key: dedicated
      #    operator: Equal
      #    value: storage

      ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
      ## eligible to run on a node, the node must have each of the
      ## indicated key-value pairs as labels.
      ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      # nodeSelector:
      #   disktype: ssd

      ## Affinity settings for MinIO pods. Read more about affinity
      ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
      affinity:
        podAntiAffinity:
          # soft AZ-based anti-affinity
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - minio-simple-cluster
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100

      ## Configure resource requests and limits for MinIO containers
      # resources:
      #   requests:
      #     cpu: 250m
      #     memory: 16Gi
      #   limits:
      #     cpu: 500m
      #      memory: 16Gi

  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  ## Sub path inside Mount path where MinIO stores data.
  # subPath: /data

  ## Use this field to provide a Secret with external certificates. This can be used to to configure 
  ## TLS for MinIO Tenant pods. Create secrets as explained here: 
  ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  # name: tls-ssl-minio

  ## Enable automatic Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false

  ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName 
  ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is 
  ## not provided. DNS name format is *.minio.default.svc.cluster.local
  # certConfig:
  #   commonName: ""
  #   organizationName: []
  #   dnsNames: []

  ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details.
  # podManagementPolicy: Parallel

  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
  - name: MINIO_PROMETHEUS_AUTH_TYPE
    value: public
  # - name: MINIO_BROWSER
  #   value: "off" # to turn-off browser
  # - name: MINIO_STORAGE_CLASS_STANDARD
  #   value: "EC:2"

  ## Liveness probe detects situations where MinIO tenant
  ## is not working properly and needs restart. Kubernetes automatically
  ## restarts the pods if liveness checks fail.
  # liveness:
  #   initialDelaySeconds: 30
  #   periodSeconds: 10
  #   timeoutSeconds: 10

  ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
  ## This is applied to MinIO pods only.
  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  # priorityClassName: high-priority
```

And a bit more of the log from the program I wrote to constantly write new files

```zsh
# Around the moment I apply the new CR
...
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.DJmCgD` -> `cluster/bucket2/tmp.DJmCgD`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 433.93 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.KCpLPA` -> `cluster/bucket2/tmp.KCpLPA`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 420.62 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.jbKKKL` -> `cluster/bucket2/tmp.jbKKKL`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 423.31 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.Ecpkjb` -> `cluster/bucket2/tmp.Ecpkjb`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 410.56 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.EOdKIO` -> `cluster/bucket2/tmp.EOdKIO`
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.EOdKIO`. Insufficient permissions to access this file `http://minio-simple-cluster/bucket2/tmp.EOdKIO`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 536.54 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.CMBCNH` -> `cluster/bucket2/tmp.CMBCNH`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.CMBCNH`. 503 Service Unavailable
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.ejoKFG` -> `cluster/bucket2/tmp.ejoKFG`
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.ejoKFG`. 503 Service Unavailable
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
...
# after 2-3 mins
...
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.MmjBdJ` -> `cluster/bucket2/tmp.MmjBdJ`
minio-init-6f6dcf6f88-hwm8n minio-mc mc: <ERROR> Failed to copy `/tmp/tmp.MmjBdJ`. Server not initialized, please try again.
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 0 B, Speed: 0 B/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.ddJckM` -> `cluster/bucket2/tmp.ddJckM`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 30.10 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.laIdgB` -> `cluster/bucket2/tmp.laIdgB`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 102.65 KiB/s
minio-init-6f6dcf6f88-hwm8n minio-mc `/tmp/tmp.JJOlhO` -> `cluster/bucket2/tmp.JJOlhO`
minio-init-6f6dcf6f88-hwm8n minio-mc Total: 0 B, Transferred: 97.66 KiB, Speed: 116.79 KiB/s
...
```
