### ISSUE TITLE
Console deployment uses minio prometheus annotations

### ISSUE THREAD

**Issue by stefanhenseler** [minio/operator#303]
The console deployment seems to add the minio endpoint for the prometheus scrape config. Does the console have a prometheus metrics endpoint? I see lots of errors in prometheus trying to scrape this target.

```
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    generation: 1
    name: minio-console
    namespace: minio
    ownerReferences:
    - apiVersion: minio.min.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Tenant
      name: minio
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        v1.min.io/console: minio-console
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        **annotations:
          prometheus.io/path: /minio/prometheus/metrics
          prometheus.io/port: "9000"
          prometheus.io/scrape: "true"**
```

## Expected Behavior
prometheus is able to scrape the console metrics.

## Current Behavior
prometheus can't scrape metrics.

## Possible Solution
1. Fix the endpoint and port.
or:
2. Remove the annotation.

## Steps to Reproduce (for bugs)
1. Deploy the Operators
2. Deploy the example console tenant yaml
