### ISSUE TITLE
Cannot Enable Console

### ISSUE THREAD

**Issue by sstubbs** [minio/operator#317]
Enable console by adding:
```
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
type: Opaque
data:
  ## HMAC JWT Secret for Console, base64 encoded (echo -n 'YOURJWTSIGNINGSECRET' | base64)
  CONSOLE_HMAC_JWT_SECRET: WU9VUkpXVFNJR05JTkdTRUNSRVQ=
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
```
and
```
  console:
    image: minio/console:v0.3.26
    replicas: 2
    consoleSecret:
      name: console-secret
```

## Expected Behavior
Console deployment to be started. 

## Current Behavior
It was working but since updating to the latest version of the operator when I enable this the console deployment doesn't start and I get the following in the operator logs:
```
Operation cannot be fulfilled on tenants.minio.min.io "minio": the object has been modified; please apply your changes to the latest version and try again
```
When I remove the console part of the tenant and update the tenant this error disappears.

## Steps to Reproduce (for bugs)
Install operator and use the tenant example https://github.com/minio/operator/blob/master/examples/tenant.yaml

## Context
Operator version v3.0.24
Console version v0.3.26

## Your Environment

* Version used (`minio-operator`): v3.0.24
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.2
* Server type and version: v1.19.2
* Operating System and version (`uname -a`): ubuntu 20.04
* Link to your deployment file:

**Comment by nitisht** [comment]
can you confirm the MinIO version @sstubbs ? Also, is the liveness check working for the MinIO Cluster?

**Comment by sstubbs** [comment]
Hi @nitisht the same as the example
```
spec:
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2020-09-26T03-44-56Z
  imagePullPolicy: IfNotPresent
```
I don't any error events generated from the liveness check. Is there something else I should be checking?

I was using 
```
kubectl apply -k https://github.com/minio/operator
```
to install the operator before and it worked. I've reinstalled it 3 times over the last 3 months and it has always worked. I've now changed to using the kubectl plugin as having a proper release version of the operator is definitely preferable for future stability. KES and minio seem to work fine but it's just the console that doesn't seem to create the deployment. I've looked and it doesn't seem to create any error messages anywhere except for that one in the operator itself.

```
Operation cannot be fulfilled on tenants.minio.min.io "minio": the object has been modified; please apply your changes to the latest version and try again
```
