### ISSUE TITLE
Add ability to add Vault TLS key

### ISSUE THREAD

**Issue by jamie-34254** [minio/operator#348]
**Is your feature request related to a problem? Please describe.**
We have an external Vault cluster with a custom CA, currently the operator does not allow you to specify a custom secret/secret mount.

**Describe the solution you'd like**
The ability to provide a custom TLS key as a file from a secret into the KES Pod would be useful

**Describe alternatives you've considered**
I was able to add a custom secret using clientCertSecret, but unfortunately the operator doesn't mount it onto disk.

**Additional context**
N/A

**Comment by Alevsk** [comment]
> clientCertSecret

Hi @jamie-34254 you need to define the secret that has your tls public, private and ca.crt  via the `clientCertSecret` field, additionally in the `server-config.yaml` that you are passing via `kesSecret.name` make sure you are providing the file names `/tmp/kes/tls.cert`, `/tmp/kes/tls.key`, `/tmp/kes/ca.crt` under `tls` in vault configuration of your kes server: https://github.com/minio/kes/blob/master/server-config.yaml#L162

please post here your yaml definition of one of your KES pods so we can analyze further

**Comment by jamie-34254** [comment]
Hi @Alevsk, to be clear we're not trying to authenticate via TLS - just provide our certificate authority key to the KES pod, we still want the automatic TLS stuff for the rest of the MinIO cluster - but want a way to add our CA file into the KES pod so that we can set it in the KES Config.

**Comment by harshavardhana** [comment]
> Hi @Alevsk, to be clear we're not trying to authenticate via TLS - just provide our certificate authority key to the KES pod, we still want the automatic TLS stuff for the rest of the MinIO cluster - but want a way to add our CA file into the KES pod so that we can set it in the KES Config.

what is the limitation of using automatic TLS for kes?

**Comment by jamie-34254** [comment]
> > Hi @Alevsk, to be clear we're not trying to authenticate via TLS - just provide our certificate authority key to the KES pod, we still want the automatic TLS stuff for the rest of the MinIO cluster - but want a way to add our CA file into the KES pod so that we can set it in the KES Config.
> 
> what is the limitation of using automatic TLS for kes?

Our Vault cluster is using a different CA to MinIO, clientCertSecret is from my understanding for providing a CA alongside a TLS cert/key for Vault authentication, we just want to specify a CA.

**Comment by Alevsk** [comment]
> Hi @Alevsk, to be clear we're not trying to authenticate via TLS - just provide our certificate authority key to the KES pod, we still want the automatic TLS stuff for the rest of the MinIO cluster - but want a way to add our CA file into the KES pod so that we can set it in the KES Config.

You can do that via the ClientCertSecret just on the kes-config do not provide any key or cert, just the ca field equals to the ca cert file name inside your secret, that way KES will know how to verify the connection with Vault

**Comment by Alevsk** [comment]
@jamie-34254 if you exec into the KES pod, do you see any certificates under /tmp or /tmp/kes?

**Comment by Alevsk** [comment]
Just did a quick test with a secret like this:

```
---
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV5VENDQXpHZ0F3SUJBZ0lSQU5aQzkzT0RMMnhaZC90bFpHdGZoakl3RFFZSktvWklodmNOQVFFTEJRQXcKZ2JVeEhqQWNCZ05WQkFvVEZXMXJZMlZ5ZENCa1pYWmxiRzl3YldWdWRDQkRRVEZGTUVNR0ExVUVDd3c4WVd4bApkbk5yUUV4bGJtbHVjeTFOWVdOQ2IyOXJMVkJ5Ynk1c2IyTmhiQ0FvVEdWdWFXNGdRV3hsZG5OcmFTQklkV1Z5CmRHRWdRWEpwWVhNcE1Vd3dTZ1lEVlFRRERFTnRhMk5sY25RZ1lXeGxkbk5yUUV4bGJtbHVjeTFOWVdOQ2IyOXIKTFZCeWJ5NXNiMk5oYkNBb1RHVnVhVzRnUVd4bGRuTnJhU0JJZFdWeWRHRWdRWEpwWVhNcE1CNFhEVEU1TURZdwpNVEF3TURBd01Gb1hEVE13TVRBd09UQTJNelkwTjFvd1lqRW5NQ1VHQTFVRUNoTWViV3RqWlhKMElHUmxkbVZzCmIzQnRaVzUwSUdObGNuUnBabWxqWVhSbE1UY3dOUVlEVlFRTERDNWhiR1YyYzJ0QWRHbG1ZUzVzYjJOaGJDQW8KVEdWdWFXNGdRV3hsZG5OcmFTQklkV1Z5ZEdFZ1FYSnBZWE1wTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBNEt2VFR4WGhtUHVoUTdpaytQNURjNjBvWDJoZXhsVWJXbTM2M2lFTnA0am5WSGMvCk56anlaNVNUNXhlTWxNbnI1dXlWd2hZUXFIeWZ4TXhLcWh3Tks3elBkWHBBdUxtTEZDSURyWUhHV1B3ZGVyYU8KYXQ4WG9LRy83dnM5THJmb3FmU2pqd0dNNnRodWdCYit4NklRb3ArYk9VUEluZTdjOWZQam9NRHlNY1pLS0pWUgorOUpIVHZ6WGladCtxWUFqZ2xKV2JmemZ0a1ZEVWdGUWFEcTJiR2RBSnJVTDVlbGVweWsvOVAxSDc1b2hubHpYCnpjck9oaFl5Vi92bzlhQXpRK3RnUWpwZ0R5bnpETDJWYmNqdFhRUUxzcmFzY0QwaXZDNjJreXEwdkUvZ0lsZ3gKb1h1TUJwaTNiOUhxTVVnMUZEcFk4LzBNZHRWVVJsVklmTGhXVlFJREFRQUJvNEdsTUlHaU1BNEdBMVVkRHdFQgovd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1COEdBMVVkCkl3UVlNQmFBRk9NZk9RZHNYbmd2T0R4cU4xbUZKZFEzcUgwRE1Fd0dBMVVkRVFSRk1FT0NRU291YldsdWFXOHQKWTNWemRHOXRMV05sY25RdFpXNWpjbmx3ZEdsdmJpMXRhVzVwYnkxb2JDNWtaV1poZFd4MExuTjJZeTVqYkhWegpkR1Z5TG14dlkyRnNNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJnUUNQU0w2Q0wya2RaazQ0aGNzK2VrTy93TWRWClY2c1E1amV5bHN0UCtQS01IZURLY0tVcHY3bkNCMkEyRFdHUStUOXY2c3ZKTFowcVhzejBQUWRZYUZxV1FrR2oKNmJMcGRFNlB2MXE4UEpxUEplWnZpZ01sQmRTNVA3UUNEMVBJczREOEE0eDNWd0RrL2ZJSkZyOW0wckNCaUk5agpPbHlCTnVxLzJJdHh0dmdSYm5tSG8rbHp2ZUxGZ05GNGJhejFqY3cxRzFQZzcyUC8rWnNrbS9QQTJoQ3FnOVRpClVaOU9Nd3ZvcFN6RkppMlJ2UjFPMWhhL1hzZ1VmK1pxWXlVSTdrc3ZQYlRPNUY3dlFJaS9sanUvT0toVEhZRWIKT1ZsRFRoT0djRGV3ZFhncHhpdG1ZZitQd0Q1clhPMTJUR3pZUzR0eGxGQ0FNbmNHbU1YQ2hJQmZwamlNeFE2bwpPVVhTUnNwNjhsNFNsWWwrcmQzeUtDNitEekFpYS9EZTdCMVNDMDNPYk9kVXhMVkdPZGxNbFMxU2puK0tzUFNPCjBNcEIwc3VvRkhlUTBUTVNUL24ydUpuc0liWXUzZk5IN1NsSW5tazllMGNUTWVGWkt4ZzhWRlFJQUZ3allabk0KdGlZNjA4NEhxeG9Hb01ScmNrYzZiTFZBSFpZTU85cUl4SG5uU2lVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
kind: Secret
metadata:
  name: your-vault-ca-here
  namespace: default
```

then on your tenant deployment
```
  kes:
    image: minio/kes:v0.12.0
    replicas: 2
    clientCertSecret:
      name: your-vault-ca-here
    ...
...
```
Once deployed, the KES pod will have something like this:

```
      volumes:
      - name: minio-custom-cert-encryption-minio-kes
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: server-config.yaml
                path: server-config.yaml
              name: minio-custom-cert-encryption-kes-config
          - secret:
              items:
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
              name: minio-custom-cert-encryption-cluster-cert
          - secret:
              name: your-vault-ca-here
```

and the `ca.crt` will be mounted under `/tmp/kes/ca.crt`, you need to set that in your kes configuration
