### ISSUE TITLE
How to replace serviceName for multiple tenants

### ISSUE THREAD

**Issue by sylus** [minio/operator#357]
The service name is always set to Minio and the functionality to set it looks to be removed in:

https://github.com/minio/operator/commit/dda8cb78c64034f337f11da4ee212ac64c931062#diff-d5ca04858bbf8c9f7ce13215f121165e2c149339c3d9072e4810a8d8076314e9L259

## Expected Behavior

Ability to set the parameter and have it passed to be the operator.

## Current Behavior

No ability to set the parameter and have it passed to be the operator.

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

```
---
## MinIO Tenant Definition
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
## If specified, Tenant pods will be dispatched by specified scheduler.
## If not specified, the pod will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler
spec:
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2020-10-18T21-54-12Z
  imagePullPolicy: IfNotPresent
  serviceName: test <--- can't set / override
```
