### ISSUE TITLE
Generating minio operator manifests results in unusable resources

### ISSUE THREAD

**Issue by rustysys-dev** [minio/operator#358]
## Expected Behavior
outputing the minio operator manifest should result in a usable manifest

## Current Behavior
api version and kind are missing for some of the output resources.

if I run the following command
```
kubectl minio init -o 
```

I get the following result
```
# every entry above the following contains their respective api version and kind.
---
metadata:
  creationTimestamp: null
  name: minio-operator
  namespace: default
---
metadata:
  creationTimestamp: null
  name: minio-operator-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-role
subjects:
- kind: ServiceAccount
  name: minio-operator
  namespace: default
---
metadata:
  creationTimestamp: null
  name: minio-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: minio-operator
    spec:
      containers:
      - env:
        - name: CLUSTER_DOMAIN
          value: cluster.local
        - name: WATCHED_NAMESPACE
        image: minio/k8s-operator:v3.0.26
        imagePullPolicy: IfNotPresent
        name: minio-operator
        resources: {}
      imagePullSecrets:
      - {}
      serviceAccountName: minio-operator
status: {}
---
```

## Steps to Reproduce (for bugs)
1. install latest kubectl
2. install latest krew
3. install latest minio
4. run `kubectl minio init -o`

## Context
I am creating a test environment for my platform and need manifests for my repository + deployment (Infrastructure as Code)

## Regression
I don't know its my first time using minio

## Your Environment
* Kubernetes Version: kubernetes v1.18.x
* Operating System and version: AmazonLinux2.0
