### ISSUE TITLE
Minio console and tenant doesn't support custom tolerations and nodeSelector

### ISSUE THREAD

**Issue by appunni-dishq** [minio/operator#360]
```
kind: Pod
apiVersion: v1
metadata:
  name: tenant-zone-0-0
  generateName: tenant-zone-0-
  namespace: minio
  selfLink: /api/v1/namespaces/minio/pods/tenant-zone-0-0
  creationTimestamp: '2020-11-20T08:17:40Z'
  labels:
    controller-revision-hash: tenant-zone-0-5c7b58f85b
    statefulset.kubernetes.io/pod-name: tenant-zone-0-0
    v1.min.io/tenant: tenant
    v1.min.io/version: v3.0.28
    v1.min.io/zone: zone-0
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"minio.min.io/v1","kind":"Tenant","metadata":{"annotations":{},"creationTimestamp":null,"name":"tenant","namespace":"minio"},"scheduler":{"name":""},"spec":{"certConfig":{},"console":{"consoleSecret":{"name":"minio-secret-console"},"image":"minio/console:v0.4.4","metadata":{"creationTimestamp":null,"name":"tenant"},"nodeSelector":{"intended-user":"internal-tools","use-case":"application"},"replicas":2,"resources":{"limits":{"cpu":"100m","memory":"500Mi"},"requests":{"cpu":"100m","memory":"500Mi"}},"tolerations":[{"effect":"NoSchedule","key":"use-case","value":"application"},{"effect":"NoSchedule","key":"environment","value":"production"},{"effect":"PreferNoSchedule","key":"spec","value":"med-cpu-med-mem"}]},"credsSecret":{"name":"minio-secret"},"image":"minio/minio:RELEASE.2020-09-26T03-44-56Z","imagePullSecret":{},"liveness":{"initialDelaySeconds":10,"periodSeconds":1,"timeoutSeconds":1},"mountPath":"/export","nodeSelector":{"intended-user":"internal-tools","use-case":"application"},"requestAutoCert":false,"serviceName":"tenant-internal-service","tolerations":[{"effect":"NoSchedule","key":"use-case","value":"application"},{"effect":"NoSchedule","key":"environment","value":"production"},{"effect":"PreferNoSchedule","key":"spec","value":"med-cpu-med-mem"}],"zones":[{"resources":{"limits":{"cpu":"1200m","memory":"6Gi"},"requests":{"cpu":"1200m","memory":"6Gi"}},"servers":4,"volumeClaimTemplate":{"apiVersion":"v1","kind":"persistentvolumeclaims","metadata":{"creationTimestamp":null},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"512Gi"}}},"status":{}},"volumesPerServer":4}]},"status":{"availableReplicas":0,"currentState":""}}
  ownerReferences:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: tenant-zone-0
      controller: true
      blockOwnerDeletion: true
spec:
  volumes:
    - name: '1'
      persistentVolumeClaim:
        claimName: 1-tenant-zone-0-0
    - name: '2'
      persistentVolumeClaim:
        claimName: 2-tenant-zone-0-0
    - name: '3'
      persistentVolumeClaim:
        claimName: 3-tenant-zone-0-0
    - name: '0'
      persistentVolumeClaim:
        claimName: 0-tenant-zone-0-0
    - name: default-token-sm7xh
      secret:
        secretName: default-token-sm7xh
        defaultMode: 420
  containers:
    - name: minio
      image: 'minio/minio:RELEASE.2020-09-26T03-44-56Z'
      args:
        - server
        - '--certs-dir'
        - /tmp/certs
      ports:
        - containerPort: 9000
          protocol: TCP
      env:
        - name: MINIO_UPDATE
          value: 'on'
        - name: MINIO_UPDATE_MINISIGN_PUBKEY
          value: 
        - name: MINIO_ARGS
          valueFrom:
            secretKeyRef:
              name: operator-webhook-secret
              key: MINIO_ARGS
        - name: MINIO_ENDPOINTS
          value: >-
            http://tenant-zone-0-{0...3}.tenant-hl.minio.svc.cluster.local/export{0...3}
        - name: MINIO_OPERATOR_VERSION
          value: v3.0.28
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secretkey
      resources:
        limits:
          cpu: 1200m
          memory: 6Gi
        requests:
          cpu: 1200m
          memory: 6Gi
      volumeMounts:
        - name: '0'
          mountPath: /export0
        - name: '1'
          mountPath: /export1
        - name: '2'
          mountPath: /export2
        - name: '3'
          mountPath: /export3
        - name: default-token-sm7xh
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  securityContext: {}
  hostname: tenant-zone-0-0
  subdomain: tenant-hl
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-11-20T08:17:40Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-11-20T08:17:53Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-11-20T08:17:53Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-11-20T08:17:40Z'
  startTime: '2020-11-20T08:17:40Z'
  containerStatuses:
    - name: minio
      state:
        running:
          startedAt: '2020-11-20T08:17:52Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: 'minio/minio:RELEASE.2020-09-26T03-44-56Z'
      imageID: >-
        docker-pullable://minio/minio@sha256:9377fd142e5e9b129449ca2247be6924b23b5227d31eca8236f1c6951226e233
      started: true
  qosClass: Guaranteed
```

As you can see last applied configuration has tolerations and nodeSelector but current pod is not getting updated with the same, when I patched the stateful set it got reverted by minio operator meaning it's not supported by minio operator for some reason
