### ISSUE TITLE
Incorrect Usage: flag provided but not defined: -certs-dir

### ISSUE THREAD

**Issue by mostafa8026** [minio/operator#373]
When create the console pods, We have a CrashLoopBackOff status, and after checking the log of the console pod, I found this message:

```
Incorrect Usage: flag provided but not defined: -certs-dir

NAME:
  console server - starts Console server

USAGE:
  console server [command options] [arguments...]

FLAGS:
  --host value             HTTP server hostname (default: "0.0.0.0")
  --port value             HTTP Server port (default: 9090)
  --tls-host value         HTTPS server hostname (default: "0.0.0.0")
  --tls-port value         HTTPS server port (default: 9443)
  --tls-certificate value  filename of public cert
  --tls-key value          filename of private key
  --help, -h               show help

```
## Expected Behavior

Console pod come available without any problem.

## Current Behavior

encountered an error: `Incorrect Usage: flag provided but not defined: -certs-dir`

## Possible Solution

Maybe it is my bad config,  could anyone take a look at my config:
```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: tenant-min3
  namespace: min3
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: tenant-min3-console-secret
    image: minio/console:v0.3.14
    metadata:
      creationTimestamp: null
      name: tenant-min3
    replicas: 2
    resources: {}
  credsSecret:
    name: tenant-min3-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: tenant-min3-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: default
      status: {}
    volumesPerServer: 4
status:
  availableReplicas: 0
  currentState: ""

---
apiVersion: v1
data:
  accesskey: ZTZkMDk3MD....jZiMzQ2Yzc1
  secretkey: MDQ1ZmNjNzUt...TMtMGQwMzA3NDUyZmM5
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant-min3-creds-secret
  namespace: min3

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: Mzg3YmI4...I5MDQtOGE3OGFjNjU3Zjgx
  CONSOLE_HMAC_JWT_SECRET: ZjA4ZDQ5ZjMtZm....0Njdk
  CONSOLE_PBKDF_PASSPHRASE: OT....DU4ZGVj
  CONSOLE_PBKDF_SALT: OGMzMjA1Nzgt.....zVh
  CONSOLE_SECRET_KEY: ZjFjNTBiY....MyZjQw
kind: Secret
metadata:
  creationTimestamp: null
  name: tenant-min3-console-secret
  namespace: min3

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv6-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv7-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv8-minio
  namespace: min3
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  local:
    path: /export4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker03

```

## Steps to Reproduce (for bugs)

1. I was mentioned my config earlier. juse run kubectl apply -f $(myconfig)

## Context

I want to bring up a distributed erasure minio with k8s. (2 server and 4 drives each one)

## Your Environment

* Version used (`minio-operator`): krew    v0.4.0 / minio   v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
* Server type and version:  virtual machine (using kubeadm)
* Operating System and version (`uname -a`): Linux ubuntu-g1-medium1-su-1 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:
