### ISSUE TITLE
Problem with inner network

### ISSUE THREAD

**Issue by mostafa8026** [minio/operator#375]
I get this error when trying to start the pods:
```
API: SYSTEM()
Time: 12:35:41 UTC 12/01/2020
Error: lookup storage1-zone-0-1.storage1-hl.min3.svc.cluster.local on 10.96.0.10:53: read udp 10.244.196.70:35743->10.96.0.10:53: i/o timeout (*net.DNSError)
       host=storage1-zone-0-1.storage1-hl.min3.svc.cluster.local, elapsedTime=3 minutes elapsed
       5: cmd/endpoint.go:447:cmd.Endpoints.UpdateIsLocal()
       4: cmd/endpoint.go:631:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:372:cmd.createServerEndpoints()
       2: cmd/server-main.go:139:cmd.serverHandleCmdArgs()
       1: cmd/server-main.go:378:cmd.serverMain()
```
and after some time:

```
Marking https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export1/v22 temporary offline; caused by Post "https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export1/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup storage1-zone-0-1.storage1-hl.min3.svc.cluster.local on 10.96.0.10:53: read udp 10.244.196.70:58375->10.96.0.10:53: i/o timeout
Marking https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export3/v22 temporary offline; caused by Post "https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export3/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup storage1-zone-0-1.storage1-hl.min3.svc.cluster.local on 10.96.0.10:53: read udp 10.244.196.70:60839->10.96.0.10:53: i/o timeout
Marking https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export2/v22 temporary offline; caused by Post "https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export2/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup storage1-zone-0-1.storage1-hl.min3.svc.cluster.local on 10.96.0.10:53: read udp 10.244.196.70:49508->10.96.0.10:53: i/o timeout
Marking https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export0/v22 temporary offline; caused by Post "https://storage1-zone-0-1.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export0/v22/readall?disk-id=&file-path=format.json&volume=.minio.sys": lookup storage1-zone-0-1.storage1-hl.min3.svc.cluster.local on 10.96.0.10:53: read udp 10.244.196.70:51911->10.96.0.10:53: i/o timeout
Disk `/export0` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Disk `/export1` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Disk `/export2` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Disk `/export3` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.

```

## Expected Behavior

The inner network connect the pods to gether.

## Steps to Reproduce (for bugs)

1. Install CALICO cni plugin
2. Install minio with local storage class
3. and the problem appear.

## Your Environment

* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): 1.19.4
* Server type and version: baremeta ubuntu
* Operating System and version (`uname -a`):  Linux master 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your deployment file:

```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: storage1
  namespace: min3
scheduler:
  name: ""
spec:
  certConfig: {}
  #externalCertSecret:
  #- name: minio-tls
  #  type: kubernetes.io/tls
  #- name: minio-console-tls
  #  type: kubernetes.io/tls
  console:
    consoleSecret:
      name: storage1-console-secret
    image: minio/console:v0.4.6
    metadata:
      creationTimestamp: null
      name: storage1
    replicas: 2
    resources: {}
  credsSecret:
    name: storage1-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: storage1-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-storage
      status: {}
    volumesPerServer: 4
status:
  availableReplicas: 0
  currentState: ""


```
