### ISSUE TITLE
Create cluster zone filed with "Unable to attach or mount volumes"

### ISSUE THREAD

**Issue by jaggerwang** [minio/operator#421]
Workload:
![image](https://user-images.githubusercontent.com/1255011/104436920-273c9000-55c9-11eb-9975-bb08d54a8368.png)
![image](https://user-images.githubusercontent.com/1255011/104436971-36234280-55c9-11eb-9ca7-525e5e2e3de2.png)

Pod:
![image](https://user-images.githubusercontent.com/1255011/104437023-44715e80-55c9-11eb-8bfa-d68c8d29696d.png)

PV:
![image](https://user-images.githubusercontent.com/1255011/104437769-2a844b80-55ca-11eb-89c3-d8a0daa0ed1e.png)
![image](https://user-images.githubusercontent.com/1255011/104437805-36700d80-55ca-11eb-9bb6-d13afb1a9e09.png)

## Steps to Reproduce (for bugs)
1. Install minio plugin.
2. Init minio plugin.
3. Create a tenant.

```bash
kubectl krew update
kubectl krew install minio

kubectl minio init

kubectl minio tenant create                \
    --name minio-cluster                   \
    --servers 4                            \
    --volumes 4                            \
    --capacity 12Ti                        \
    --storage-class local-storage
```

StorageClass:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

PersistentVolumes:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode1-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode2-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode2
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode3-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-kubenode4-data2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3.7Ti
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dev-kubenode4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
```

## Your Environment
* Version used (`minio-operator`): v3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): v1.18.14 managed by Rancher
* Server type and version: CentOS Linux release 8.3.2011
* Operating System and version (`uname -a`): Linux dev-kubenode1 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lptarik** [comment]
Maybe this can help you 
[https://github.com/minio/operator/issues/395#issuecomment-748650296](url)

**Comment by jaggerwang** [comment]
> Maybe this can help you
> [https://github.com/minio/operator/issues/395#issuecomment-748650296](url)

Thanks，but these two are not the same problem.

**Comment by nitisht** [comment]
Is this still a problem @jaggerwang ? Can you paste the output `kubectl describe pod <minio-pod-name>`

**Comment by oiar** [comment]
I encountered the same problem, have you found a solution? Thank you very much if you can get your help.

**Comment by oiar** [comment]
> Is this still a problem @jaggerwang ? Can you paste the output `kubectl describe pod <minio-pod-name>`

hi! Hope to get your help, thank you very much.
`kubectl describe pod minio-tenant-1-zone-0-0`
`Error from server (NotFound): pods "minio-tenant-1-zone-0-0" not found`
and
`kubectl get events -n minio`
`LAST SEEN   TYPE      REASON        OBJECT                        MESSAGE
8s          Warning   FailedMount   pod/minio-tenant-1-zone-0-0   MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found
6m40s       Warning   FailedMount   pod/minio-tenant-1-zone-0-0   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[0 minio-tenant-1-tls default-token-qk29w]: timed out waiting for the condition
11m         Warning   FailedMount   pod/minio-tenant-1-zone-0-0   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[minio-tenant-1-tls default-token-qk29w 0]: timed out waiting for the condition
2m10s       Warning   FailedMount   pod/minio-tenant-1-zone-0-1   MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found
8m48s       Warning   FailedMount   pod/minio-tenant-1-zone-0-1   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[0 minio-tenant-1-tls default-token-qk29w]: timed out waiting for the condition
58m         Warning   FailedMount   pod/minio-tenant-1-zone-0-1   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[default-token-qk29w 0 minio-tenant-1-tls]: timed out waiting for the condition
8s          Warning   FailedMount   pod/minio-tenant-1-zone-0-2   MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found
56m         Warning   FailedMount   pod/minio-tenant-1-zone-0-2   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[default-token-qk29w 0 minio-tenant-1-tls]: timed out waiting for the condition
11m         Warning   FailedMount   pod/minio-tenant-1-zone-0-2   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[0 minio-tenant-1-tls default-token-qk29w]: timed out waiting for the condition
6m36s       Warning   FailedMount   pod/minio-tenant-1-zone-0-2   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[minio-tenant-1-tls default-token-qk29w 0]: timed out waiting for the condition
6s          Warning   FailedMount   pod/minio-tenant-1-zone-0-3   MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found
20m         Warning   FailedMount   pod/minio-tenant-1-zone-0-3   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[0 minio-tenant-1-tls default-token-qk29w]: timed out waiting for the condition
11m         Warning   FailedMount   pod/minio-tenant-1-zone-0-3   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[default-token-qk29w 0 minio-tenant-1-tls]: timed out waiting for the condition
6m52s       Warning   FailedMount   pod/minio-tenant-1-zone-0-3   Unable to attach or mount volumes: unmounted volumes=[minio-tenant-1-tls], unattached volumes=[minio-tenant-1-tls default-token-qk29w 0]: timed out waiting for the condition`

**Comment by nitisht** [comment]
> MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found

Do you have this secret? Please create a fresh issue with details. You may or many not be hitting the same issue.

**Comment by jaggerwang** [comment]
> Is this still a problem @jaggerwang ? Can you paste the output `kubectl describe pod <minio-pod-name>`

```console
$ kubectl describe pod minio-zone-0-0 -n minio
Name:           minio-zone-0-0
Namespace:      minio
Priority:       0
Node:           dev-kubenode4/10.28.113.14
Start Time:     Fri, 05 Feb 2021 14:23:16 +0800
Labels:         controller-revision-hash=minio-zone-0-68d5b8db6f
                statefulset.kubernetes.io/pod-name=minio-zone-0-0
                v1.min.io/tenant=minio
                v1.min.io/version=v3.0.29
                v1.min.io/zone=zone-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/minio-zone-0
Containers:
  minio:
    Container ID:
    Image:         minio/minio:RELEASE.2020-11-19T23-48-16Z
    Image ID:
    Port:          9000/TCP
    Host Port:     0/TCP
    Args:
      server
      --certs-dir
      /tmp/certs
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      MINIO_UPDATE:                  on
      MINIO_UPDATE_MINISIGN_PUBKEY:  RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav
      MINIO_ARGS:                    <set to the key 'MINIO_ARGS' in secret 'operator-webhook-secret'>  Optional: false
      MINIO_ENDPOINTS:               https://minio-zone-0-{0...3}.minio-hl.minio.svc.cluster.local/export
      MINIO_OPERATOR_VERSION:        v3.0.29
      MINIO_ACCESS_KEY:              <set to the key 'accesskey' in secret 'minio-creds-secret'>  Optional: false
      MINIO_SECRET_KEY:              <set to the key 'secretkey' in secret 'minio-creds-secret'>  Optional: false
    Mounts:
      /export from 0 (rw)
      /tmp/certs from minio-tls (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9cz7m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  0:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  0-minio-zone-0-0
    ReadOnly:   false
  minio-tls:
    Type:                Projected (a volume that contains injected data from multiple sources)
    SecretName:          minio-tls
    SecretOptionalName:  <nil>
  default-token-9cz7m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-9cz7m
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m23s                default-scheduler  Successfully assigned minio/minio-zone-0-0 to dev-kubenode4
  Warning  FailedMount  21s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[0], unattached volumes=[0 minio-tls default-token-9cz7m]: timed out waiting for the condition
  Warning  FailedMount  16s (x9 over 2m23s)  kubelet            MountVolume.NewMounter initialization failed for volume "minio-kubenode4-data2" : path "/data2" does not exist
```

And the secrets:

![image](https://user-images.githubusercontent.com/1255011/106997684-42f91780-67be-11eb-95ab-34f3102c387e.png)

**Comment by oiar** [comment]
> > MountVolume.SetUp failed for volume "minio-tenant-1-tls" : secret "minio-tenant-1-tls" not found
> 
> Do you have this secret? Please create a fresh issue with details. You may or many not be hitting the same issue.

```
kubectl get secrets -n minio
NAME                            TYPE                                  DATA   AGE
default-token-qk29w             kubernetes.io/service-account-token   3      43h
minio-operator-token-tn8j5      kubernetes.io/service-account-token   3      38h
minio-tenant-1-console-secret   Opaque                                5      22h
minio-tenant-1-creds-secret     Opaque                                2      22h
operator-webhook-secret         Opaque                                3      22h
```

**Comment by oiar** [comment]
Hi! I solved this problem. I found I can't creates TLS certificates automatically using the Kubernetes cluster root Certificate Authority (CA) to establish trust, and `requestAutoCert` field in the config file is true. But I create a self-signed certificate and use a Kubernetes Secret resource to store this information, and then the problem goes away.

```bash
$ kubectl get all -n minio
NAME                                  READY   STATUS              RESTARTS   AGE
pod/minio-operator-6f5b8cdcff-d4s7l   1/1     Running             0          42h
pod/minio-tenant-1-zone-0-0           0/1     ContainerCreating   0          26h
pod/minio-tenant-1-zone-0-1           0/1     ContainerCreating   0          26h
pod/minio-tenant-1-zone-0-2           0/1     ContainerCreating   0          26h
pod/minio-tenant-1-zone-0-3           0/1     ContainerCreating   0          26h

NAME                        TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
service/minio               ClusterIP   10.43.20.232   <none>        443/TCP    26h
service/minio-tenant-1-hl   ClusterIP   None           <none>        9000/TCP   26h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/minio-operator   1/1     1            1           42h

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/minio-operator-6f5b8cdcff   1         1         1       42h

NAME                                     READY   AGE
statefulset.apps/minio-tenant-1-zone-0   0/4     26h

$ kubectl create secret generic minio-tenant-1-tls --from-file=/root/minio/certs/private.key --from-file=/root/minio/certs/public.crt
secret/minio-tenant-1-tls created

$ kubectl get secrets
NAME                  TYPE                                  DATA   AGE
default-token-htvs2   kubernetes.io/service-account-token   3      30d
minio-tenant-1-tls    Opaque                                2      10s
```

**Comment by harshavardhana** [comment]
v4.0.0 released closing - please re-open if seen again

**Comment by jaggerwang** [comment]
Still not working~

![image](https://user-images.githubusercontent.com/1255011/109096748-126f2280-7759-11eb-85d9-a895b1b2e78c.png)
```
I0225 02:55:18.516575       1 main.go:72] Starting MinIO Operator
I0225 02:55:18.866751       1 main.go:139] caBundle on CRD updated
I0225 02:55:18.867331       1 main-controller.go:250] Setting up event handlers
I0225 02:55:18.867787       1 main-controller.go:634] Starting Tenant controller
I0225 02:55:18.867808       1 main-controller.go:637] Waiting for informer caches to sync
I0225 02:55:18.885559       1 main-controller.go:598] operator TLS secret not found%!(EXTRA string=secrets "operator-tls" not found)
I0225 02:55:18.912356       1 csr.go:217] Start polling for certificate of csr/operator-minio-csr, every 5s, timeout after 20m0s
I0225 02:55:19.168152       1 main-controller.go:642] Starting workers
I0225 02:55:23.916355       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
I0225 02:55:23.922182       1 main-controller.go:601] Waiting for the operator certificates to be issued waiting for Operator cert
I0225 02:55:33.926111       1 main-controller.go:625] Starting api server
I0225 02:56:10.574991       1 main-controller.go:967] Deploying pool ss-0
I0225 02:56:11.633767       1 main-controller.go:972] Deploying pool failed ss-0
E0225 02:56:11.633853       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
I0225 02:56:20.523698       1 main-controller.go:967] Deploying pool ss-0
I0225 02:56:20.534207       1 csr.go:73] Generating private key
I0225 02:56:20.534320       1 csr.go:86] Generating CSR with CN=*.minio-hl.minio.svc.cluster.local
I0225 02:56:20.543886       1 csr.go:217] Start polling for certificate of csr/minio-minio-csr, every 5s, timeout after 20m0s
I0225 02:56:25.547914       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0225 02:56:25.553823       1 main-controller.go:720] error syncing 'minio/minio': waiting for minio cert
I0225 02:57:20.550228       1 main-controller.go:967] Deploying pool ss-0
I0225 02:57:20.571487       1 csr.go:217] Start polling for certificate of csr/minio-console-minio-csr, every 5s, timeout after 20m0s
I0225 02:57:25.575419       1 csr.go:242] Certificate successfully fetched, creating secret with Private key and Certificate
E0225 02:57:25.581003       1 main-controller.go:720] error syncing 'minio/minio': waiting for console cert
I0225 02:58:20.580339       1 main-controller.go:967] Deploying pool ss-0
E0225 02:58:21.691524       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
E0225 02:59:21.660232       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
E0225 03:00:22.705820       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
E0225 03:01:23.761745       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
E0225 03:02:24.818903       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
E0225 03:03:25.873881       1 main-controller.go:720] error syncing 'minio/minio': MinIO is not ready
```

![image](https://user-images.githubusercontent.com/1255011/109096719-02574300-7759-11eb-902b-b929c3d2c87f.png)
```
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[0], unattached volumes=[minio-tls default-token-kdqqh 0]: timed out waiting for the condition | a few seconds ago
-- | -- | -- | --
Warning | FailedMount | MountVolume.NewMounter initialization failed for volume "minio-kubenode2-data2" : path "/data2" does not exist | a minute ago
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[0], unattached volumes=[0 minio-tls default-token-kdqqh]: timed out waiting for the condition | 3 minutes ago
Warning | FailedMount | Unable to attach or mount volumes: unmounted volumes=[0 minio-tls default-token-zgn67], unattached volumes=[0 minio-tls default-token-zgn67]: timed out waiting for the condition | 11 minutes ago
Normal | Scheduled | Successfully assigned minio/minio-ss-0-0 to dev-kubenode2 | Invalid date


```

**Comment by bmoqimi** [comment]
I have the exact same issue. Let me know what extra input I can provide and I would be more than happy to oblige. My logs are frighteningly similar so I thought there is no point in spamming the thread. 
@jaggerwang did you find any temporary workaround ?

**Comment by jaggerwang** [comment]
@bmoqimi No, still waiting~

**Comment by bmoqimi** [comment]
Just tested this on 2.5.8-rc1 with latest k8s and it works fine.

**Comment by jaggerwang** [comment]
Finally I got the reason. In a kubernetes cluster created by rancher, kubelet is running in a container, so it can not access host's filesystem. You need to add the following extra args for kubelet in cluster yaml.

```yaml
    kubelet:
      extra_binds:
        - '/data1:/data1'
        - '/data2:/data2'
        - '/data3:/data3'
```

More on rancher's doc https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/#extra-binds.
