### ISSUE TITLE
MinIO Operator to create buckets

### ISSUE THREAD

**Issue by Mercbot7** [minio/operator#427]
**Is your feature request related to a problem? Please describe.**
Relative to the Helm chart, per the [docs](https://github.com/minio/charts/blob/master/README.md) the Operator is to supercede/replace the chart, the Operator does not create the default or other buckets through configuration.

**Describe the solution you'd like**
As part of Tenant creation it would be good to be able to list a default and list of buckets to be created after the tenant has been created.
It would be good to be able to declaratively configure, through yaml files, tenants and buckets. As with the imperative method, if properties or values are not provided the Operator will provide required resources, i.e., secrets, certs, bucket settings and options.

**Describe alternatives you've considered**
I have reverse engineered the chart job to create buckets to create a default bucket. It works at a very rudimentary level but is not resilient or intuitive.

**Additional context**
Being able to deploy Minio using the operator needs to have the option to deploy declaratively so gitops and other automated methods can be used more effectively.

**Comment by nitisht** [comment]
This is not on the roadmap as of now @Mercbot7 . We may consider this in future.

**Comment by harshavardhana** [comment]
> This is not on the roadmap as of now @Mercbot7 . We may consider this in future.

Let's reopen in future if there are plans.

**Comment by Mercbot7** [comment]
That would be awesome! In the mean time could Minio Provide a best practice to automagically create buckets? Perhaps a n official job or something like that? maybe something like this?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-{{ .Release.Name }}-make-bucket-job
  labels:
    app: minio-{{ .Release.Name }}-make-bucket-job
spec:
  template:
    metadata:
      labels:
        app: minio-{{ .Release.Name }}-make-bucket-job
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: minio-mc
        image: minio/mc:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-tenant-{{ .Release.Name }}-creds-secret
              key: accesskey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-tenant-{{ .Release.Name }}-creds-secret
              key: secretkey
        - name: MINIO_ENDPOINT
          value: https://minio.minio-tenant-{{ .Release.Name }}.svc.cluster.local
        - name: MINIO_PORT
          value: "443"
        - name: BUCKET
          value: "bucket-1 bucket-2 bucket-3"
        command: ["/bin/bash", "-ce"]
        args:
        - | 
          checkBucketExists() {
            ebucket=$1
            CMD=$(${MC} ls myminio | grep "\s$ebucket/$" > /dev/null 2>&1)
            return $?
          }
          MC="mc --insecure"
          ${MC} config host add myminio $MINIO_ENDPOINT:$MINIO_PORT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          # Create the bucket if it does not exist
          for iBUCKET in $BUCKET
          do
            if ! checkBucketExists $iBUCKET; then
              echo "Creating bucket $iBUCKET"
              ${MC} mb myminio/$iBUCKET
            else
              echo "Bucket $iBUCKET already exists."
            fi
          done

```
