### ISSUE TITLE
minio-console:9090 redirects to 0.0.0.0:9443

### ISSUE THREAD

**Issue by mfbrj** [minio/operator#428]
I installed a minio tenant using the following yml:
```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
  namespace: mynamespace
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.4.6
    metadata:
      creationTimestamp: null
      name: minio
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: minio-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2560Mi
        storageClassName: wffc
      status: {}
    volumesPerServer: 2
status:
  availableReplicas: 0
  currentState: ""

---
apiVersion: v1
data:
  accesskey: my-accesskey
  secretkey: my-secretkey
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: mynamespace

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: myCONSOLE_ACCESS_KEY
  CONSOLE_HMAC_JWT_SECRET: myCONSOLE_HMAC_JWT_SECRET
  CONSOLE_PBKDF_PASSPHRASE: myCONSOLE_PBKDF_PASSPHRASE
  CONSOLE_PBKDF_SALT: myCONSOLE_PBKDF_SALT
  CONSOLE_SECRET_KEY: myCONSOLE_SECRET_KEY
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-console-secret
  namespace: mynamespace

```
When I try to access the gui minio-console:9090 it redirects to 0.0.0.0:9443

Someone reported the same problem at [stackoverflow](https://stackoverflow.com/questions/64827502/kubernetes-minio-tenant-ui-redirects-to-0-0-0-09443), unfortunally with no answers.

## Expected Behavior

Minio Console gui should be displayed.

## Current Behavior

Connection is redirected to 0.0.0.0:9443 returning a blank page.

## Steps to Reproduce (for bugs)

1. Install a minio tenant with the config above.
2. To avoid the complexity in configure a ingress, just try to access the minio-console:9090 from any pod in the same namespace using curl:
```
root@ubuntu-79969d4b85-s7mtj:/# curl minio-console:9090
<a href="https://0.0.0.0:9443/">Moved Permanently</a>.
```

## Your Environment

* Version used (`minio-operator`):
```
kubectl krew list
PLUGIN  VERSION
krew    v0.4.0
minio   v3.0.29

```
* Environment name and version (e.g. kubernetes v1.17.2):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```
* Server type and version:
* Operating System and version (`uname -a`):
```
uname -a
Linux myhost 5.8.0-38-generic #43-Ubuntu SMP Tue Jan 12 12:42:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your deployment file:
