### ISSUE TITLE
Minio Operator TLS with cert-manager is not working

### ISSUE THREAD

**Issue by smartservice-energy** [minio/operator#446]
Minio Operator searches for public.crt, cert-manager although could not be configured to name the crt and key files other than ca.crt, tls.crt and tls.key.

**Comment by Alevsk** [comment]
@smartservice-energy when attaching secrets in your tenant CRD please make sure the secret type is `kubernetes.io/tls` ie:
```
  externalCertSecret:
    - name: minio-custom-cert-no-encryption-cluster-cert
      type: kubernetes.io/tls
    - name: minio-custom-cert-no-encryption-buckets-cert
      type: kubernetes.io/tls
    - name: minio-custom-cert-no-encryption-hl-cert
      type: kubernetes.io/tls
```

Operator has logic to look for the `tls.crt` field if the secret type is `kubernetes.io/tls` or `cert-manager.io/v1alpha2`, otherwise the secret must content the `public.crt` field.
