### ISSUE TITLE
Minio Tenant with single PVC fails to create.

### ISSUE THREAD

**Issue by upodroid** [minio/operator#457]
## Expected Behavior

I'm using TrueNAS to mount an nfs share provisioned via democratic-csi driver and minio is forcing me to create 4 disks per server. The data redundancy is already provided via ZFS and I don't want to do it via Minio

https://docs.min.io/docs/minio-gateway-for-nas.html This config doesn't seem to be supported by the operator yet.

## Current Behavior

Error

```
 mahamed  MCW0CDP3YY  ~  Desktop  Git  home  kubernetes   master  1✎  $   k describe tenant
Name:         dev
Namespace:    minio
Labels:       <none>
Annotations:  API Version:  minio.min.io/v1
Kind:         Tenant
Metadata:
  Creation Timestamp:  2021-02-03T23:34:51Z
  Generation:          1
    Manager:         minio-operator
    Operation:       Update
    Time:            2021-02-03T23:34:56Z
  Resource Version:  16693692
  Self Link:         /apis/minio.min.io/v1/namespaces/minio/tenants/dev
  UID:               d8a41bb2-a0d8-43b6-8346-2dbd5c8a0b2a
Spec:
  Cert Config:
  Console:
    Console Secret:
      Name:  dev-console-secret
    Image:   minio/console:v0.4.6
    Metadata:
      Name:    dev
    Replicas:  2
    Resources:
  Creds Secret:
    Name:  dev-creds-secret
  Image:   minio/minio:RELEASE.2020-11-19T23-48-16Z
  Image Pull Secret:
  Kes:
    Image:  minio/kes:v0.13.3
    Kes Secret:
      Name:  kes-config
    Metadata:
      Labels:
        App:               kes
    Replicas:              2
    Service Account Name:  minio-kes
  Mount Path:              /export
  Request Auto Cert:       true
  Service Name:            dev-internal-service
  Zones:
    Resources:
    Servers:  1
    Volume Claim Template:
      API Version:  v1
      Kind:         persistentvolumeclaims
      Spec:
        Access Modes:
          ReadWriteOnce
        Resources:
          Requests:
            Storage:         25Gi
        Storage Class Name:  freenas-nfs-csi
      Status:
    Volumes Per Server:  1
Status:
  Available Replicas:  0
  Current State:       zone #0 setup must have a minimum of 4 volumes per server
Events:                <none>
```

## Your Environment
```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: dev
  namespace: minio
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: dev-console-secret
    image: minio/console:v0.4.6
    metadata:
      name: dev
    replicas: 2
    resources: {}
  credsSecret:
    name: dev-creds-secret
  image: minio/minio:RELEASE.2020-11-19T23-48-16Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: true
  serviceName: dev-internal-service
  zones:
  - resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
        storageClassName: freenas-nfs-csi
      status: {}
    volumesPerServer: 1
  kes:
    image: minio/kes:v0.13.3
    serviceAccountName: minio-kes
    replicas: 2
    kesSecret:
      name: kes-config
    metadata:
      labels:
        app: kes
```
