### ISSUE TITLE
minio tenant expand does not accept "--storage-class" parameter

### ISSUE THREAD

**Issue by celalsahin** [minio/operator#467]
First of all, with 3.0.29 I am using tenant expand (on contary to what is written in https://github.com/minio/operator/blob/v3.0.29/docs/expansion.md#getting-started) because there is no "volume" call in that version.

Unlike "tenant create", "tenant expand" does not have a parameter --storage-class. This is a problem when you use any storage class except default. This causes problems if you have a storage class specific for minios3 (having necessary volumeBindingMode & reclaimPolicy as required by the documentation).

It should be possible to pass --storage-class parameter to expand also.

## Expected Behavior

I expect expand to also have a "--storage-class" parameter so we can pass the storage class for new zones/PVC as well.

## Current Behavior

expand does not have a "--storage-class" parameter hence every extension will fallback to default storage class...

## Steps to Reproduce (for bugs)

1. Create storage class
2. Use that storage class to create your tenant (e.g. --storage-class)
3. Use expand to expand the tenant - observe that you cannot define --storage-class
4. PVC claims fall back to default, which either does not exist or not correct.

## Context

Having a special storage-class to fulfil the requirements of minio, I cannot attach this storage-class to expand.

## Your Environment

* Version used (`minio-operator`): 3.0.29
* Environment name and version (e.g. kubernetes v1.17.2): OCP 4.6.13
* See below snippet from expand yaml, initial zones have the storageclass defined but not the expansion.
```
  - resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: minios3-storageclass
      status: {}
    volumesPerServer: 4
  - resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      status: {}
    volumesPerServer: 1
```
