### ISSUE TITLE
Minio cluster fails to initialize

### ISSUE THREAD

**Issue by frezbo** [minio/operator#529]
Minio cluster fails to initialize on Kubernetes 

## Expected Behavior
Minio cluster should be up and running

## Current Behavior
The minio pod logs shows just this:

```shell
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
```

## Steps to Reproduce (for bugs)
Install `minio-operator` using helm

```shell
helm repo add minio https://operator.min.io/
helm install --namespace minio-operator --create-namespace minio-operatorminio/minio-operator
```
Running helm chart version `4.0.2`

Apply the below manifest:

```yaml
## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'minio' | base64)
  accesskey: bWluaW8=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'minio123' | base64)
  secretkey: bWluaW8xMjM=
---
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
type: Opaque
data:
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
## MinIO Tenant Definition
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  image: minio/minio:RELEASE.2021-03-01T04-20-55Z 
  imagePullPolicy: Always

  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio-creds-secret

  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 4

      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 1

      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this
      ## Pool.
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
        limits:
          cpu: 500m
          memory: 100Mi

      ## Configure security context 
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true

  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  requestAutoCert: true
  s3:
    ## This feature is turned off by default
    bucketDNS: false
  podManagementPolicy: Parallel

  ## serviceMetadata allows passing additional labels and annotations to MinIO and Console specific 
  ## services created by the operator.
  serviceMetadata:
    minioServiceLabels:
      label: minio-svc
    minioServiceAnnotations:
      v2.min.io: minio-svc
    consoleServiceLabels:
      label: console-svc
    consoleServiceAnnotations:
      v2.min.io: console-svc
  console:
    image: minio/console:v0.6.3
    replicas: 2
    consoleSecret:
      name: console-secret
    securityContext:
      runAsUser: 1000
      runAsGroup: 2000
      runAsNonRoot: true
```

The `minio-operator` continuously logs this:

```shell
2021/03/10 16:59:52 http: TLS handshake error from 10.42.1.0:28511: remote error: tls: bad certificate
2021/03/10 16:59:52 http: TLS handshake error from 10.42.2.1:61377: remote error: tls: bad certificate
2021/03/10 16:59:53 http: TLS handshake error from 10.42.0.0:58342: remote error: tls: bad certificate
2021/03/10 16:59:53 http: TLS handshake error from 10.42.1.0:3610: remote error: tls: bad certificate
2021/03/10 16:59:53 http: TLS handshake error from 10.42.2.1:1881: remote error: tls: bad certificate
2021/03/10 16:59:54 http: TLS handshake error from 10.42.0.0:7701: remote error: tls: bad certificate
2021/03/10 16:59:54 http: TLS handshake error from 10.42.1.0:45388: remote error: tls: bad certificate
2021/03/10 16:59:55 http: TLS handshake error from 10.42.2.1:41296: remote error: tls: bad certificate
2021/03/10 16:59:55 http: TLS handshake error from 10.42.0.0:5688: remote error: tls: bad certificate
2021/03/10 16:59:55 http: TLS handshake error from 10.42.1.0:16085: remote error: tls: bad certificate
2021/03/10 16:59:56 http: TLS handshake error from 10.42.2.1:42341: remote error: tls: bad certificate
2021/03/10 16:59:56 http: TLS handshake error from 10.42.0.0:40339: remote error: tls: bad certificate
2021/03/10 16:59:56 http: TLS handshake error from 10.42.1.0:48383: remote error: tls: bad certificate
```

I have ignored the above since the certificate request is successful

```shell
☸ frezbo (minio-operator) in personal/kubernetes/mattermost ❯ kubectl get csr
NAME                           AGE   SIGNERNAME                     REQUESTOR                                             CONDITION
minio-console-mattermost-csr   36s   kubernetes.io/legacy-unknown   system:serviceaccount:minio-operator:minio-operator   Approved,Issued
minio-mattermost-csr           97s   kubernetes.io/legacy-unknown   system:serviceaccount:minio-operator:minio-operator   Approved,Issued
```

The pods shows as running:

```shell
☸ frezbo (minio-operator) in personal/kubernetes/mattermost ❯ kubectl get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
mattermost-mattermost-team-edition-7f9d6c4c79-zj5xf   1/1     Running   0          27h
minio-ss-0-0                                          1/1     Running   0          119m
minio-ss-0-1                                          1/1     Running   0          119m
minio-ss-0-2                                          1/1     Running   0          119m
minio-ss-0-3                                          1/1     Running   1          119m
```

The operator logs says the cluster is not ready:

```shell
☸ frezbo (minio-operator) in personal/kubernetes/mattermost ❯ kubectl logs --since=5m -f minio-operator-66c7c4dbb8-nhkgd 
2021/03/10 17:03:34 http: TLS handshake error from 10.42.0.0:58095: remote error: tls: bad certificate
2021/03/10 17:03:34 http: TLS handshake error from 10.42.1.0:17046: remote error: tls: bad certificate
2021/03/10 17:03:34 http: TLS handshake error from 10.42.2.1:16877: remote error: tls: bad certificate
E0310 17:03:35.309958       1 main-controller.go:721] error syncing 'mattermost/minio': MinIO is not ready
2021/03/10 17:03:35 http: TLS handshake error from 10.42.0.0:46946: remote error: tls: bad certificate
2021/03/10 17:03:35 http: TLS handshake error from 10.42.1.0:54510: remote error: tls: bad certificate
2021/03/10 17:03:35 http: TLS handshake error from 10.42.2.1:33597: remote error: tls: bad certificate
2021/03/10 17:03:36 http: TLS handshake error from 10.42.0.0:64129: remote error: tls: bad certificate
2021/03/10 17:03:36 http: TLS handshake error from 10.42.1.0:46283: remote error: tls: bad certificate
```

and the minio console pod is also not created

## Context
Deploy a minio cluster using `minio-operator`

## Your Environment

* Minio operator helm chart `4.0.2`
* Server setup and configuration:
* Flatcar Linux running k3s version `v1.20.4+k3s1`
