### ISSUE TITLE
example tenant.yaml: ERROR Unable to initialize backend: Unable to write to the backend (operator chart version 4.0.2)

### ISSUE THREAD

**Issue by Mierpo** [minio/operator#534]
I'm running the following versions:

```
Chart: 4.0.2
Image: minio/minio:RELEASE.2021-03-12T00-00-47Z
```

However, I'm running into the following problem when using the example tenant.yaml:

```
API: SYSTEM()
Time: 06:25:58 UTC 03/16/2021
Error: disk returned an unexpected error at https://minio-ss-0-0.minio-hl.minio.svc.cluster.local:9000/export0, please investigate - disk will be offline (*errors.errorString)
       5: cmd/storage-rest-server.go:982:cmd.logFatalErrs()
       4: cmd/storage-rest-server.go:1000:cmd.registerStorageRESTHandlers()
       3: cmd/routers.go:28:cmd.registerDistErasureRouters()
       2: cmd/routers.go:93:cmd.configureServerHandler()
       1: cmd/server-main.go:464:cmd.serverMain()

API: SYSTEM()
Time: 06:25:58 UTC 03/16/2021
Error: disk returned an unexpected error at https://minio-ss-0-0.minio-hl.minio.svc.cluster.local:9000/export1, please investigate - disk will be offline (*errors.errorString)
       5: cmd/storage-rest-server.go:982:cmd.logFatalErrs()
       4: cmd/storage-rest-server.go:1000:cmd.registerStorageRESTHandlers()
       3: cmd/routers.go:28:cmd.registerDistErasureRouters()
       2: cmd/routers.go:93:cmd.configureServerHandler()
       1: cmd/server-main.go:464:cmd.serverMain()
ERROR Unable to initialize backend: Unable to write to the backend
      > Please ensure MinIO binary has write permissions for the backend
      HINT:
        Run the following command to add write permissions: `sudo chown -R nonroot. <path> && sudo chmod u+rxw <path>`
```

I have modified the tenant.yaml to only have 2 servers and 2 discs per server.

I'm been trying to google the reason and I am unsure if this is the reason:

```
            securityContext:
              enabled: true
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
```

Essentially there is no user with UID 1000, or a group with GID 1000 inside the minio image, so why does minio tenant.yaml example contain these? There's been a long discussion on issues related to access rights to the data directory from the current user, so what is the actual proper way of running as non-root user, using the operator and tenant deployment method?

My actual installation is done like this (redacted the secrets creation part):
(note: This is helm k8s module syntax, the "spec" part is what is interesting here):

```
- name: Install minio tenant
  k8s:
    state: present
    definition:
      apiVersion: minio.min.io/v2
      kind: Tenant
      metadata:
        name: minio
        namespace: minio
        labels:
          app: minio
      spec:
        image: "{{ minio_image }}"
        imagePullPolicy: IfNotPresent
        credsSecret:
          name: minio-creds-secret
        pools:
          - servers: 2
            volumesPerServer: 2
            volumeClaimTemplate:
              metadata:
                name: data
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 25Gi
            securityContext:
              enabled: true
              runAsUser: 1000
              runAsGroup: 1000
              runAsNonRoot: true
        mountPath: /export
        requestAutoCert: true
        s3:
          bucketDNS: false
        certConfig:
          commonName: ""
          organizationName: []
          dnsNames: []
        podManagementPolicy: Parallel
        serviceMetadata:
          minioServiceLabels:
            label: minio-svc
          minioServiceAnnotations:
            v2.min.io: minio-svc
          consoleServiceLabels:
            label: console-svc
          consoleServiceAnnotations:
            v2.min.io: console-svc
        console:
          image: minio/console:v0.6.3
          replicas: 2
          consoleSecret:
            name: console-secret
          securityContext:
            enabled: true
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
```

**Comment by mattlqx** [comment]
I've yet to get this operator to completely work. For what it looks like, it's being refactored I guess. But to get around this specific problem with using PVCs, I specified a sideCar in the tenant:

```
  sideCars:
    volumes:
    - name: minio-data0
      persistentVolumeClaim:
        claimName: minio-data0-minio-ss-0-0
    - name: minio-data1
      persistentVolumeClaim:
        claimName: minio-data1-minio-ss-0-0
    - name: minio-data2
      persistentVolumeClaim:
        claimName: minio-data2-minio-ss-0-0
    - name: minio-data3
      persistentVolumeClaim:
        claimName: minio-data3-minio-ss-0-0
    containers:
      # ensure correct ownership on pvc volumes. unfortunately has to be persistent as operator
      # doesn't support initContainers.
      - name: chown
        image: busybox
        command:
          - /bin/sh
        args:
          - -c
          - chown 1000:2000 /export* && (while true; do sleep 86400; done)
        volumeMounts:
          - mountPath: /export0
            name: minio-data0
          - mountPath: /export1
            name: minio-data1
          - mountPath: /export2
            name: minio-data2
          - mountPath: /export3
            name: minio-data3
```

Not the greatest thing in the world, but it fixed up permissions on the created PVCs and got me a little further.
