### ISSUE TITLE
Ingress TLS Setup

### ISSUE THREAD

**Issue by toabi** [minio/operator#536]
I noticed that a setup with a ingress causes unwanted redirects which some clients cannot handle.

I deployed a tenant with the Operator 4.0.1 and create an Ingress using ingress-nginx.
The ingress will get lets-encrypt certificates and forces TLS.

I noticed the issue while using a tool (https://github.com/aminueza/terraform-provider-minio) which itself uses minio-go to create users/policies. minio-go uses the madmin package from this repository.

It can create buckets and files without problems, but when it wants to interact with users/policies it fails.

The responsible code here is probably https://github.com/minio/minio/blob/master/pkg/madmin/user-commands.go#L223-L224

There it receives an HTTP 308 with the default nginx redirect HTML. This causes a JSON parse error which bubbles up.

When I set `"nginx.ingress.kubernetes.io/ssl-redirect" = "false"` on the ingress it is reachable without TLS which is not what I want but the provider can create the users.

To test it I can do for example `curl -X PUT "http://minio.stage.my.domain/minio/admin/v3/add-user?accessKey=minio_user2"`

When the redirect is true (the default) it returns a HTTP 308 to the https URL. Without it I get a direct response from the minio api.

## My questions

- How to configure it correctly so the minio client doesn't do a http request?
- Should redirects be handled here?

## Your Environment
* Version used (`minio-operator`): 4.0.1
* Environment name and version (e.g. kubernetes v1.17.2): 1.20.4
* Server type and version: Rancher RKE + ingress-nginx

## Configuration

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: cdn
  namespace: minio
spec:
  rules:
  - host: minio.stage.my.domain
    http:
      paths:
      - backend:
          service:
            name: minio
            port:
              number: 9000
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - minio.stage.my.domain
    secretName: cdn-ingress
```

and 

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
  labels:
    app: minio
  name: cdn
  namespace: minio
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: cdn-console-secret
    image: minio/console:v0.6.3
    replicas: 2
    securityContext:
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
  credsSecret:
    name: cdn-credentials
  externalCertSecret:
  - name: tls-cdn
    type: kubernetes.io/tls
  image: minio/minio:RELEASE.2021-03-17T02-33-02Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: OrderedReady
  pools:
  - servers: 4
    volumeClaimTemplate:
      metadata:
        name: cdn
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
    volumesPerServer: 1
  requestAutoCert: true
  s3:
    bucketDNS: false
  serviceMetadata:
    consoleServiceAnnotations:
      v2.min.io: console-svc
    consoleServiceLabels:
      label: console-svc
    minioServiceAnnotations:
      v2.min.io: minio-svc
    minioServiceLabels:
      label: minio-svc
status:
  availableReplicas: 4
  certificates:
    autoCertEnabled: false
  currentState: Updating Console
  pools:
  - ssName: cdn-ss-0
    state: PoolInitialized
  revision: 0
  syncVersion: ""
```
