### ISSUE TITLE
Krew override TLS

### ISSUE THREAD

**Issue by pixie79** [minio/operator#542]
Hi,

I have reinstalled krew and Minio via Krew yesterday, then followed the README guide on this site however, I do not see anywhere to override the CRD (or where the sample is). I would like to by default use my internal Cert-Manager as the signing authority for all certs.
Can someone please point out the step i am missing?

Thanks

Mark

**Comment by nitisht** [comment]
Please use the `-o` flag in krew plugin to generate the yaml (instead of directly applying it), edit the yaml with relevant fields and apply the yaml using `kubectl apply -f <file.yaml>`

**Comment by pixie79** [comment]
Minio does not seem to have a "-o" plugin. 
```
 kubectl minio --help
Usage of /Users/markolliver/.krew/bin/kubectl-minio:
  -add_dir_header
    	If true, adds the file directory to the header of the log messages
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -log_file string
    	If non-empty, use this log file
  -log_file_max_size uint
    	Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
    	log to standard error instead of files (default true)
  -one_output
    	If true, only write logs to their native severity level (vs also writing to each lower severity level
  -skip_headers
    	If true, avoid header prefixes in the log messages
  -skip_log_headers
    	If true, avoid headers when opening log files
  -stderrthreshold value
    	logs at or above this threshold go to stderr (default 2)
  -v value
    	number for the log level verbosity
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```


I also tried the following which seems to be what you suggest:
```
kubectl minio tenant create tenant1 --servers 3 --volumes 12 --capacity 3G --namespace minio --storage-class longhorn -o out.yaml
```
Error: create command requires specifying the tenant name as an argument, e.g. 'kubectl minio tenant create tenant1'

**Comment by nitisht** [comment]
Please try `kubectl minio tenant create tenant1 --servers 3 --volumes 12 --capacity 3G --namespace minio --storage-class longhorn -o > out.yaml`

**Comment by pixie79** [comment]
I have tried that now - with the following yaml:

```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
  namespace: minio
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.6.3
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-creds-secret
  externalCertSecret:
    - name: tls-minio
      type: kubernetes.io/tls
  image: minio/minio:RELEASE.2021-03-01T04-20-55Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - resources: {}
    servers: 3
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 250M
        storageClassName: longhorn
      status: {}
    volumesPerServer: 4
  requestAutoCert: true
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
```

```
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-minio
  namespace: minio
spec:
  secretName: tls-minio
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  usages:
    - server auth
    - client auth
  commonName: "*.minio-hl.minio.svc.cluster.local"
  dnsNames:
    - minio-ss-0-0
    - minio-ss-0-1
    - minio-ss-0-2
    - minio-ss-0-0.minio-hl
    - minio-ss-0-1.minio-hl
    - minio-ss-0-2.minio-hl
    - minio-ss-0-0.minio-hl.minio
    - minio-ss-0-1.minio-hl.minio
    - minio-ss-0-2.minio-hl.minio
    - minio-ss-0-0.minio-hl.minio.svc.cluster.local
    - minio-ss-0-1.minio-hl.minio.svc.cluster.local
    - minio-ss-0-2.minio-hl.minio.svc.cluster.local
    - minio.minio.svc.cluster.local
    - "*.minio-hl.minio.svc.cluster.local"
    - "*.minio.svc.cluster.local"
```


Looking at the secrets deployed it would appear the standard TLS certs are also created and upon testing these appear to be the ones in use rather than my custom TLS which is signed by our CA.

 kubectl -n minio get secrets
NAME                      TYPE                                  DATA   AGE
default-token-9spgn       kubernetes.io/service-account-token   3      19h
minio-console-secret      Opaque                                4      7m14s
minio-console-tls         Opaque                                2      5m53s
minio-creds-secret        Opaque                                2      7m14s
minio-tls                 Opaque                                2      6m54s
operator-tls              Opaque                                1      7m9s
operator-webhook-secret   Opaque                                3      7m9s
tls-minio                 kubernetes.io/tls                     3      7m23s

kubectl -n minio get certs
NAME        READY   SECRET      AGE
tls-minio   True    tls-minio   9m53s
