### ISSUE TITLE
Can't login to MinIO console with admin account or self created account.

### ISSUE THREAD

**Issue by jaggerwang** [minio/operator#555]
## Expected Behavior
Login to MinIO console. 

## Current Behavior
It always stay in login page after enter access key(admin) and secret key which are created when creating cluster.

![image](https://user-images.githubusercontent.com/1255011/112408008-fc518380-8d51-11eb-8cea-d77248ff3b83.png)
![image](https://user-images.githubusercontent.com/1255011/112408024-02dffb00-8d52-11eb-8bd2-9c59fde13ae5.png)
![image](https://user-images.githubusercontent.com/1255011/112408957-9fef6380-8d53-11eb-9999-9f03c571653d.png)

But I can login to the embedded console of MinIO with admin account.
![image](https://user-images.githubusercontent.com/1255011/112408799-64ed3000-8d53-11eb-97c9-ebf78f6ff37b.png)

## Possible Solution
Tried to create another admin account, but got the same result.

```
mc admin user add kuangsha-minio-cluster/
mc admin policy add kuangsha-minio-cluster consoleAdmin minio/consoleAdmin.json
mc admin policy set kuangsha-minio-cluster/ consoleAdmin user=console
```
minio/consoleAdmin.json:
```json
{
    "Version": "2012-10-17",
    "Statement": [{
            "Action": [
                "admin:*"
            ],
            "Effect": "Allow",
            "Sid": ""
        },
        {
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::*"
            ],
            "Sid": ""
        }
    ]
}
```

## Context
MinIO console log:
```
2021-03-24 10:02:12.557783 I | 2021/03/24 10:02:12 server.go:129: Serving console at http://[::]:9090
2021-03-24 10:02:12.558641 I | 2021/03/24 10:02:12 server.go:129: Serving console at https://[::]:9443
```

MinIO Ingress:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  name: minio-cluster-console
spec:
  rules:
  - host: minio-cluster-console.dev.bbdops.com
    http:
      paths:
      - backend:
          serviceName: minio-cluster-console
          servicePort: https-console
        path: /
        pathType: ImplementationSpecific
```

## Your Environment

* Version used (`minio-operator`): v4.0.2
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes v1.18.14 created by Rancher RKE
* Server type and version: CentOS Linux release 8.3.2011
* Operating System and version (`uname -a`): Linux dev-kubenode1 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
