### ISSUE TITLE
Configuring MINIO login with Keycloak

### ISSUE THREAD

**Issue by jgato** [minio/operator#603]
I think I have mostly everything done following your tutorial. But after been redirected, and a correct login with keycloak, I receive a 502 bad gateway :(

## Current Behavior
Login page of Minio.
Click on login with OpenID
Login into Keycloak
When redirected to minio callback I receive the 502 bad gateway

## Context
This is how I have configured the tenant env variables:

For the tenant
```
  env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://keycloak.foo.bar/auth/realms/minio-realm/.well-known/openid-configuration" # Your external identity provide configuration
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "account"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "email openid"
```
For the MINIO Console:

```
    env:
      - name: CONSOLE_IDP_URL
        value: "https://keycloak.foo.bar" # Your external identity provide URL
      - name: CONSOLE_IDP_CLIENT_ID
        value: "account"
      - name: CONSOLE_IDP_SECRET
        value: "XXXXXXXXXXXXXXXXXXx"
      - name: CONSOLE_IDP_CALLBACK
        value: "https://minio.foo.bar/oauth_callback" 
```
I think the problem is the callback, not sure if correct. But https://minio.foo.bar point to the ingress that access to Minio Console.
Actually, I can make login with Keycloak, and I am pretty sure that login was correct. Actually, If I press F5 when the message of "502 bad gateway", I see again a Keycloack screen telling me you are already log in.

Any tip I would follow? :(

**Comment by dvaldivia** [comment]
I think the `MINIO_IDENTITY_OPENID_SCOPES` should be comma separated but I could be wrong, perhaps @Alevsk can clarify.

Do you get the 502 from Console side or from Keycloak SSO screen?

Do you see any logs on Console you can share?

**Comment by Alevsk** [comment]
> comma sep

Correct, scopes should be comma separated

**Comment by Alevsk** [comment]
> I think I have mostly everything done following your tutorial. But after been redirected, and a correct login with keycloak, I receive a 502 bad gateway :(
> 
> ## Current Behavior
> Login page of Minio.
> Click on login with OpenID
> Login into Keycloak
> When redirected to minio callback I receive the 502 bad gateway
> 
> ## Context
> This is how I have configured the tenant env variables:
> 
> For the tenant
> 
> ```
>   env:
>     - name: MINIO_IDENTITY_OPENID_CONFIG_URL
>       value: "https://keycloak.foo.bar/auth/realms/minio-realm/.well-known/openid-configuration" # Your external identity provide configuration
>     - name: MINIO_IDENTITY_OPENID_CLIENT_ID
>       value: "account"
>     - name: MINIO_IDENTITY_OPENID_SCOPES
>       value: "email openid"
> ```
> 
> For the MINIO Console:
> 
> ```
>     env:
>       - name: CONSOLE_IDP_URL
>         value: "https://keycloak.foo.bar" # Your external identity provide URL
>       - name: CONSOLE_IDP_CLIENT_ID
>         value: "account"
>       - name: CONSOLE_IDP_SECRET
>         value: "XXXXXXXXXXXXXXXXXXx"
>       - name: CONSOLE_IDP_CALLBACK
>         value: "https://minio.foo.bar/oauth_callback" 
> ```
> 
> I think the problem is the callback, not sure if correct. But https://minio.foo.bar point to the ingress that access to Minio Console.
> Actually, I can make login with Keycloak, and I am pretty sure that login was correct. Actually, If I press F5 when the message of "502 bad gateway", I see again a Keycloack screen telling me you are already log in.
> 
> Any tip I would follow? :(

If you go to `https://minio.foo.bar/` are you able to see console and authenticate it?

**Comment by jgato** [comment]
Hi,
Let me add more details. I think 502 bad gateway cames from tne Kubernete Ingress controler, or... because I am not sure if Minio Console service is working. But... there are no logs about the error in the Minio Tenant logs.

The login screen with the URL I am using for the CONSOLE_IDP_CALLBACK

![image](https://user-images.githubusercontent.com/3435696/115514672-a276a780-a284-11eb-8b4c-6d26b9572f14.png)

Then I make the login in Keycloak
![image](https://user-images.githubusercontent.com/3435696/115515235-39436400-a285-11eb-916c-5b3d1b7a82ee.png)

Login is oka and I am redirected

![image](https://user-images.githubusercontent.com/3435696/115515396-6132c780-a285-11eb-8e1f-18c13aa4ea16.png)

I think login was success because if I press F5

![image](https://user-images.githubusercontent.com/3435696/115515484-76a7f180-a285-11eb-967c-e308122e1b55.png)

by the way, I changed the Scope to comma separated. I guess this is ok, because if I put other values I receive errors about the scope.

**Comment by jgato** [comment]
Some extra info I have from my ingress-controller:

![image](https://user-images.githubusercontent.com/3435696/115516172-254c3200-a286-11eb-9812-331665fe3472.png)

I am not sure why?? I see the service is there, But it is true that something is going wrong with the https access. Using lens, If I try to forrward the service to access from local I cannot, I receive an 
```
An error occurred during a connection to localhost:44847. Peer reports it experienced an internal error.

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT
```

If instead of that, I use my ingress (that uses HTTPS also), which points to the service, it works...

**Comment by Alevsk** [comment]
> Hi,
> Let me add more details. I think 502 bad gateway cames from tne Kubernete Ingress controler, or... because I am not sure if > Minio Console service is working. But... there are no logs about the error in the Minio Tenant logs.

Seems console is not even receiving the request,  yeah this looks very likely to be an issue with the ingress controller configuration

> Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

This TLS error means the ingress could not verify the self-signed certificate of your console, depending on your ingress controller you will have to mount the public.key used by minio or the ca.crt used to generate the certificate for your ingress to verify the connection.

**Comment by Alevsk** [comment]
can you try all of this first without TLS? (AutoCert: false) so we confirm this is a TLS issue between your ingress controller and the minio services

**Comment by jgato** [comment]
ok, with all in HTTP only I have no SSL ERRORS, nor the not active endpoints. 
But it seems the same 502 bad gateway, but now I dont see any error: neither in Keycloak logs, nor ingress controlers. 
Pod is not login any error neither. Maybe I can increase the log info in the MInio Pod, any suggestion?

**Comment by jgato** [comment]
I am trying to guess what is failing but I cannot find any error log anywhere :( 
could be the IDP call back?
``` 
      - name: CONSOLE_IDP_CALLBACK
        value: "https://minio.foo.bar/oauth_callback" 
```

where should I point it?

**Comment by dvaldivia** [comment]
that looks correct, the `oauth_callback` is the right location
```
CONSOLE_IDP_URL=https://blahbla-minio.auth0.com/
CONSOLE_IDP_CALLBACK=http://localhost:5000/oauth_callback
```

**Comment by jgato** [comment]
yes, but If i have this running with Kuberentes, the IDP callback has to be the external IP/Donmain? or the name of the Kubernetes service? I am using an Ingress to make the Minio Service accessible from outside the cluster, do I have to configure something special in the Ingresss?

**Comment by jgato** [comment]
Would it be the authenticatio method of keycloak? I am not very experimented with that. I am using the accunt client but I guess I could use any other. How could I test with a command line request, if the authentication method is working as minio expects?

**Comment by jgato** [comment]
Ok, now I have found something. Following your example about configuring an IDP:
```
    env:
      - name: CONSOLE_IDP_URL
        value: "https://your-extenal-idp.com/" # Your external identity provide URL
      - name: CONSOLE_IDP_CLIENT_ID
        value: "IDP CLIENT ID"
      - name: CONSOLE_IDP_SECRET
        value: "IDP SECRET TOKEN"
      - name: CONSOLE_IDP_CALLBACK
        value: "https://your-console-service:9443/oauth_callback" # Callback URL for users to authenticate with Console, this is your console service exposes outisde of the cluster

```
I have done the same, but this env variables are not inside the Minio pod:
```
bash-4.4$ env | grep IDP

```

But there exists the ones about:
```
  env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: "https://your-extenal-idp.com/.well-known/openid-configuration" # Your external identity provide configuration
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: "OPENID CLIENT ID"
    - name: MINIO_IDENTITY_OPENID_SCOPES
      value: "openid,profile,email"
    - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
      value: "https://min.io/policy"
```
So it is normal it is not working. Why to include the env values inside the console minio especification?
