### ISSUE TITLE
Enable metrics but disable service monitor

### ISSUE THREAD

**Issue by solyard** [minio/operator#608]
**Is your feature request related to a problem? Please describe.**
I want to be able to enable metrics endpoint and creating a `bearer` for accessing it but not create ServiceMonitor for Prometheus cause I have a custom monitoring system and automation task always crashing while trying to deploy CRD (ServiceMonitor) into a cluster

**Describe the solution you'd like**
Additional option
```yaml
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
```

**Describe alternatives you've considered**
I'm actually disabled consistency check for Minio helm-chart but this is unclean feature and in production it will cause some problems

**Current problem logs from my GitOps tool**

```log
ts=2021-04-26T12:01:10.829551785Z caller=release.go:294 component=release release=s3 targetNamespace=k8s-staging resource=k8s-staging:helmrelease/s3 helmVersion=v3 error="dry-run upgrade for comparison failed: unable to recognize \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1\"" phase=dry-run-compare
```

**Comment by nitisht** [comment]
@solyard there is no metrics field in Operator CRD. To enable only Prometheus and not the Service monitor, you can do something like this in the tenant.yaml file

```yaml
  ## Prometheus setup for MinIO Tenant. 
  prometheus:
    image: "prom/prometheus"
    sidecarimage: "alpine"
    initimage: "busybox"
    diskCapacityGB: 5
```
