### ISSUE TITLE
unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext

### ISSUE THREAD

**Issue by Hokwang** [minio/operator#612]
Hi,

I am trying to install minio operator using helm on kubernetes.

I didn't not write `fsGroup:` in my-values.yaml

error message : 
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext`

Please check k8s version.

My k8s version : 1.17.17

**Comment by juliohm1978** [comment]
Same problem here.

K8s 1.19.5.

**Comment by juliohm1978** [comment]
I just tested locally. The issue relates to the helm template [operator-deployment.yaml](https://github.com/minio/operator/blob/master/helm/minio-operator/templates/operator-deployment.yaml).

Should be an easy fix. The `securityContext` declaration does not have `fsGroup` at the container level. The problem is easily fixed by moving the securityContext to the pod level of the spec.

Omitting `fsGroup` from a custom values file does not work. The default from the chart is always used. I can't see a workaround other than cloning the repo and using the a patched version of the chart with the Yaml below. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "minio-operator"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.operator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: minio-operator
      securityContext:
        {{- toYaml .Values.operator.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          {{- if or .Values.operator.clusterDomain .Values.operator.nsToWatch }}
          env:
            {{- if .Values.operator.clusterDomain }}
            - name: CLUSTER_DOMAIN
              value: {{ .Values.operator.clusterDomain }}
            {{- end }}
            {{- if .Values.operator.nsToWatch }}
            - name: WATCHED_NAMESPACE
              value: {{ .Values.operator.nsToWatch }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
```
