### ISSUE TITLE
Tenant spec.users doesn't work properly

### ISSUE THREAD

**Issue by dnskr** [minio/operator#615]
Tenant **spec.users** doesn't work properly and probably contains a bug.
1. I have created Secret object as described in the [doc](https://github.com/minio/operator/blob/master/docs/crd.adoc#tenantspec)
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: admin123
  CONSOLE_SECRET_KEY: admin123admin123
```
2. I have added **users** field to Tenant definition:
```yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: mytenant
spec:
 ...
  users:
    - name: test
  ...
```
3. I can access object storage and console with access and secret keys from **test** Secret but `Account`, `Users`, `Groups` and `IAM Policies` tabs in console don't show any info (they show 'Loading...' progress bar) and there are some errors in the console log
```
API: SYSTEM
Time: 15:14:33:0
DeploymentID: fb24742c-e51c-4b9a-8e23-50230d5011bc
Error: Unable to initialize config, some features may be missing Invalid credentials (*fmt.wrapError)
cmd/server-main.go:385:cmd.initAllSubsystems()
cmd/server-main.go:317:cmd.initServer()
cmd/server-main.go:524:cmd.serverMain()
Status: 4 Online, 0 Offline.
Endpoint: http://172.17.0.10:9000 http://127.0.0.1:9000
Browser Access:
http://172.17.0.10:9000 http://127.0.0.1:9000
Object API (Amazon S3 compatible):
Go: https://docs.min.io/docs/golang-client-quickstart-guide
Java: https://docs.min.io/docs/java-client-quickstart-guide
Python: https://docs.min.io/docs/python-client-quickstart-guide
JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
.NET: https://docs.min.io/docs/dotnet-client-quickstart-guide

API: SYSTEM
Time: 15:14:33:0
DeploymentID: fb24742c-e51c-4b9a-8e23-50230d5011bc
Error: Unable to migrate IAM users and policies to new format: sio: data is not authentic (*fmt.wrapError)
cmd/iam.go:617:cmd.(*IAMSys).Init()

API: SYSTEM
Time: 15:14:33:0
DeploymentID: fb24742c-e51c-4b9a-8e23-50230d5011bc
Error: IAM sub-system is partially initialized, some users may not be available (*errors.errorString)
cmd/iam.go:618:cmd.(*IAMSys).Init()
```

## Your Environment
Operator version: 4.0.8
Console version: v0.6.8
MinIO version: RELEASE.2021-04-22T15-44-28Z
