### ISSUE TITLE
Tenants created with `kubectl apply -f` don't get found by `kubectl minio` plugin

### ISSUE THREAD

**Issue by arianvp** [minio/operator#619]
## Expected Behavior
I created a tenant using `kubectl apply -f` and it shows up with `kubectl get tenant minio`
```
$ kubectl get tenant minio
NAME    STATE         AGE
minio   Initialized   6d14h
```
and it should be picked up by `kubectl minio tenant info minio` as well:
```
$ kubectl minio tenant info minio
```

## Current Behavior
The minio plugin can't find the tenant:
```
$ kubectl minio tenant info minio
Error: tenants.minio.min.io "minio" not found
```

## Steps to Reproduce (for bugs)
```yaml
# tenant.yaml
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  credsSecret:
    name: minio-creds-secret
  console:
    consoleSecret:
      name: console-secret
  pools:
    - servers: 4
      volumesPerServer: 1
      nodeSelector:
        node.kubernetes.io/instance-type: i3.large
      volumeClaimTemplate:
        metadata:
          name: storage
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: openebs-device
          resources:
            requests:
              storage: 400Gi
```

```
$ kubectl apply -f tenant.yaml
$ kubectl get tenant minio
NAME    STATE         AGE
minio   Initialized   6d14h
$  kubectl minio tenant info minio
Error: tenants.minio.min.io "minio" not found
```

## Regression
No

## Your Environment

* Version used (`minio-operator`): 4.0.8
* Environment name and version (e.g. kubernetes v1.17.2): Kubernetes 1.19.8
* Server type and version:
* Operating System and version (`uname -a`): Linux t490s 5.4.112 #1-NixOS SMP Wed Apr 14 06:24:19 UTC 2021 x86_64 GNU/Linux
* Link to your deployment file:
