### ISSUE TITLE
Create users with non-consoleAdmin policies during tenant provisioning

### ISSUE THREAD

**Issue by dnskr** [minio/operator#629]
**Is your feature request related to a problem? Please describe.**
The Operator creates a user with `consoleAdmin` policy by default when `tenant.spec.users` is used, see [users in the doc](https://github.com/minio/operator/blob/master/docs/crd.adoc#tenantspec).
It would be great to have posibility to create users with other policies.

**Describe the solution you'd like**
I would like to use optional `CONSOLE_POLICY` field in user secret to specify the policy.
For example:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myuser
type: Opaque
stringData :
  CONSOLE_ACCESS_KEY: minio
  CONSOLE_SECRET_KEY: miniominio
  CONSOLE_POLICY: read_only
```

**Additional context**
It is not clear for me why `CONSOLE_` prefix is used,  so it might be a good idea to remove it:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myuser
type: Opaque
stringData :
  ACCESS_KEY: minio
  SECRET_KEY: miniominio
  POLICY: read_only
```

**Comment by dnskr** [comment]
Still relevant enhancement

**Comment by dnskr** [comment]
@Alevsk Hi! Are there any plans to implement this feature or a reason why it will never be implemented?

**Comment by harshavardhana** [comment]
> @Alevsk Hi! Are there any plans to implement this feature or a reason why it will never be implemented?

We will take a look soon.

**Comment by dnskr** [comment]
Still relevant enhancement

**Comment by dnskr** [comment]
Still good to have :)

**Comment by jessebot** [comment]
> > @Alevsk Hi! Are there any plans to implement this feature or a reason why it will never be implemented?
> 
> We will take a look soon.

Was this looked at? I see #1359 was opened and then closed, but I haven't see any movement since last year.

As @dnskr mentioned, I think this would make a lot of sense:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myuser
type: Opaque
stringData :
  ACCESS_KEY: minio
  SECRET_KEY: miniominio
  POLICY: read_only
```

It would also be great to have a policies field to create policies at tenant setup time as well.

If all that needs to be done is search and replace on @drivebyer's code in #1359 for CONSOLE_POLICY to POLICY and changing CONSOLE_ACCESS_KEY to ACCESS_KEY/changing CONSOLE_SECRET_KEY to SECRET_KEY, I can do that.

This would make it so that I don't need any extra custom init scripts, which would be really nice.
