### ISSUE TITLE
Gateway Support

### ISSUE THREAD

**Issue by adrianord** [minio/operator#653]
I understand that Gateway mode is not supported in the operator by design, referencing issue #606, however https://github.com/minio/charts is now in archive mode and says that this chart is now the direct replacement. Is there any other officially supported charts that support Gateway mode or can the MinIO team re-evaluate implementing Gateway mode in the operator since the old repository says this repository now replaces it?

**Comment by harshavardhana** [comment]
Gateway won't be supported in operator - we may support helm charts for gateway as it moves to a new repo `https://github.com/minio/ming` - but this operator won't support it.

**Comment by adrianord** [comment]
@harshavardhana Thank you for the link to the new repository. Is https://github.com/minio/charts still stable and up to date enough to use until the new ming repository is ready to be used in production?

**Comment by jrefi** [comment]
@harshavardhana Is the gateway feature being deprecated? How are we supposed to deploy gateways if the operator does not support them and you are no longer maintaining the Helm charts?

**Comment by harshavardhana** [comment]
> @harshavardhana Thank you for the link to the new repository. Is https://github.com/minio/charts still stable and up to date enough to use until the new ming repository is ready to be used in production?

You can use it if it works for you. We are not taking any more changes to that repo.

> @harshavardhana Is the gateway feature being deprecated? How are we supposed to deploy gateways if the operator does not support them and you are no longer maintaining the Helm charts?

Are you saying that this is hard? 

```yaml
## Run minio gateway azure deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-gateway-s3-prod
  labels:
    app: minio-gateway-s3-prod
spec:
  selector:
    matchLabels:
      app: minio-gateway-s3-prod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio-gateway-s3-prod
    spec:
      containers:
      - name: minio-gateway-s3-prod
        image: minio/minio:latest
        imagePullPolicy: Always
        args:
        - gateway
        - s3
        - https://s3.amazonaws.com
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
            ephemeral-storage: 1024Mi
        ports:
        - containerPort: 9000
```
