### ISSUE TITLE
minIO Tenant Specification does not supported documented field: serviceName.

### ISSUE THREAD

**Issue by jdelreal** [minio/operator#661]
## Expected Behavior

As per the documentation [here](https://docs.min.io/minio/k8s/reference/minio-operator-reference.html#minio-tenant-object) - the field: `serviceName` in the following provided documentation code-block for `kind: Tenant` should work, and be supported . . .

---
```
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio-tenant-1
  namespace: minio-tenant-1
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-tenant-1-console-secret
    image: minio/console:v0.3.14
    metadata:
      creationTimestamp: null
      name: minio-tenant-1
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-tenant-1-creds-secret
  image: minio/minio:RELEASE.2020-09-26T03-44-56Z
  imagePullSecret: {}
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 1
    timeoutSeconds: 1
  mountPath: /export
  requestAutoCert: true
  serviceName: minio-tenant-1-internal-service
  zones:
  - resources: {}
    servers: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        storage-class: local-storage
        resources:
          requests:
            storage: 10Gi
      status: {}
    volumesPerServer: 4
```
## Current Behavior

```
error: error validating "STDIN": error validating data: ValidationError(Tenant.spec): unknown field "serviceName" in io.min.minio.v2.Tenant.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
## Possible Solution

Add this Field to be supported in the minIO Tenant `customResourceDefinition`.

## Steps to Reproduce (for bugs)

1. `kubectl minio init -o > /tmp/manifests.yaml`
2. `kubectl minio tenant create minio-tenant-1 --storage-class standard --servers 2 --volumes 4 --capacity 16Gi --namespace minio-tenant-1 -o >> /tmp/manifests.yaml`
3. `kubectl create ns minio-tenant-1`
4. `sed  -i.bak 's/mountPath\:\ \/export/mountPath\:\ \/export\n\ \ serviceName\:\ minio-tenant-1-internal-service/' /tmp/manifests.yaml`
5. `kubectl apply -f /tmp/manifests.yaml`
```
namespace/minio-operator unchanged
serviceaccount/minio-operator unchanged
clusterrole.rbac.authorization.k8s.io/minio-operator-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/minio-operator-binding unchanged
customresourcedefinition.apiextensions.k8s.io/tenants.minio.min.io configured
service/operator unchanged
deployment.apps/minio-operator unchanged
serviceaccount/console-sa unchanged
clusterrole.rbac.authorization.k8s.io/console-sa-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/console-sa-binding unchanged
configmap/console-env unchanged
service/console unchanged
error: error validating "/tmp/manifests.yaml": error validating data: ValidationError(Tenant.spec): unknown field "serviceName" in io.min.minio.v2.Tenant.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
## Context

minIO Operator does not honor field - `serviceName` as per documentation [here](https://docs.min.io/minio/k8s/reference/minio-operator-reference.html#minio-tenant-object):
![image](https://user-images.githubusercontent.com/6455506/120193688-b2ba6480-c1ea-11eb-948e-1df2d27405d9.png)

## Regression

No

## Your Environment

* Version used (`minio-operator`): `minio/operator:v4.0.5`
* Environment name and version (e.g. kubernetes v1.17.2): `kubernetes v1.19.7`
* Server type and version:
```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Operating System and version (`uname -a`): `Darwin HOSTNAME.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`
* Link to your deployment file: `N/A`
