### ISSUE TITLE
Add affinity support for Tenant console

### ISSUE THREAD

**Issue by dnskr** [minio/operator#672]
Cannot set `affinity` for Tenant console but  it's possible to set `nodeSelector` and `tolerations` so looks like `affinity` was just missed in CRD

## Expected Behavior
Be able to set  `affinity` for Tenant console similar to `nodeSelector` and `tolerations`

## Possible Solution
Add `affinity` field to Tenant CRD implementation

## Steps to Reproduce (for bugs)
Create Tenant by manifest with the following config
```yaml
## MinIO Tenant Definition
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  ...
  console:
    image: minio/console:v0.7.4
    nodeSelector: {}
    tolerations: []
    affinity: {}
```

## Context
Missing this field prevents from more granular workloads management
