### ISSUE TITLE
no service for bucket gets created

### ISSUE THREAD

**Issue by dakky** [minio/operator#679]
## Expected Behavior
As soon as there is a bucket created in minio, i'd expected the operator to create a matching service.
i.E.:
Bucket: test => service test.minio-hl.namespace.cluster.svc.local

## Current Behavior
* kubectl get svc:
```
service/gitlab-s3-console                         ClusterIP      10.100.200.16    <none>          9443/TCP                                  37m
service/gitlab-s3-hl                              ClusterIP      None             <none>          9000/TCP                                  39m
```
* create bucket via mc/webinterface
* check service
```
service/gitlab-s3-console                         ClusterIP      10.100.200.16    <none>          9443/TCP                                  37m
service/gitlab-s3-hl                              ClusterIP      None             <none>          9000/TCP                                  39m
```
* nothing happens, no new services, no log entries in operator log

## Possible Solution
none

## Steps to Reproduce (for bugs)
```yaml
tenants:
  - name: gitlab-s3
    namespace: gitlab
    image:
      repository: minio/minio
      tag: "RELEASE.2021-04-06T23-11-00Z"
      pullPolicy: IfNotPresent
    imagePullSecret: {}
    scheduler: {}
    pools:
      - servers: 4
        volumesPerServer: 2
        size: 15Gi
        storageClassName: local-path
        tolerations: {}
        nodeSelector: {}
        affinity: {}
        resources: {}
        securityContext: {}
    mountPath: /export
    subPath: /data
    secrets:
      enabled: true
      name: gitlab-secret
      accessKey: xxxx
      secretKey: xxx
    metrics:
      enabled: false
      port: 9000
    certificate:
      requestAutoCert: true
      certConfig:
        commonName: gitlab-s3.gitlab.svc.cluster.local
        dnsNames:
          - 'gitlab-registry-storage.gitlab-s3-hl.gitlab.svc.cluster.local'
          - 'gitlab-lfs-storage.gitlab-s3-hl.gitlab.svc.cluster.local'
          - 'gitlab-artifacts-storage.gitlab-s3-hl.gitlab.svc.cluster.local'
          - 'gitlab-uploads-storage.gitlab-s3-hl.gitlab.svc.cluster.local'
          - 'gitlab-packages-storage.gitlab-s3-hl.gitlab.svc.cluster.local'
          - 'gitlab-backup-storage.gitlab-s3-hl.gitlab.svc.cluster.local'
    s3:
      bucketDNS: true
    podManagementPolicy: Parallel
    console:
      image:
        repository: minio/console
        tag: v0.6.8
        pullPolicy: IfNotPresent
      replicaCount: 1
      secrets:
        enabled: true
        name: console-secret
        passphrase: xxx
        salt: xxxx
        accessKey: xxxxx
        secretKey: xxxxx
```

operator and tenant created via:
```
helm secrets upgrade --install --create-namespace -n minio-operator \
		-f secrets.yaml \
		minio minio/minio-operator
```
## Context
I'd like to create a minio instance for gitlab

## Regression
?

## Your Environment

* Version used (`minio-operator`): 4.1.1
* Environment name and version (e.g. kubernetes v1.17.2): v1.19.10+vmware.1

**Comment by harshavardhana** [comment]
> Bucket: test => service test.minio-hl.namespace.cluster.svc.local

We do not create another headless service instead a service is created called `bucket.namespace.svc.cluster.local` - this is only created if we can create a `minio.namespace.svc.cluster.local`  looks like you do not have that ClusterIP service. 

You should look at if the Tenant is provided properly if Tenant is not provisioned yet then it won't create the relevant services.

Also, verify if the services are created in the `minio-operator` namespace.

**Comment by dakky** [comment]
Hello

The tenant look fine IMHO?
```
❯ kubectl get tenants.minio.min.io
NAME        STATE         AGE
gitlab-s3   Initialized   21h
```
detailed status from `kubectl get tenants.minio.min.io -o yaml`:
```yaml
  status:
    availableReplicas: 4
    certificates:
      autoCertEnabled: true
    currentState: Initialized
    drivesOnline: 8
    healthStatus: green
    pools:
    - ssName: gitlab-s3-ss-0
      state: PoolInitialized
    revision: 0
    syncVersion: ""
    writeQuorum: 5
```

Services after deploying the tentant:
```
❯ kgs
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE 
gitlab-s3-console   ClusterIP   10.100.200.169   <none>        9443/TCP   5m8s
gitlab-s3-hl        ClusterIP   None             <none>        9000/TCP   7m18s
minio               ClusterIP   10.100.200.175   <none>        443/TCP    7m18s
```

Services after adding some buckets:
```
❯ kgs
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE 
gitlab-s3-console   ClusterIP   10.100.200.169   <none>        9443/TCP   6m4s
gitlab-s3-hl        ClusterIP   None             <none>        9000/TCP   8m14s
minio               ClusterIP   10.100.200.175   <none>        443/TCP    8m14s
```

The services in the `minio-operator` namespace:
```
❯ kgs -n minio-operator
NAME       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
console    ClusterIP   10.100.200.15    <none>        9090/TCP,9443/TCP   23h
operator   ClusterIP   10.100.200.144   <none>        4222/TCP,4233/TCP   23h
```
