### ISSUE TITLE
TLS handshake error after adding new pool

### ISSUE THREAD

**Issue by mostafa8026** [minio/operator#693]
After I add a new pool to the tenant, I get a TLS handshake problem:

error in old pool (storage1-ss-0-0)
```
{"level":"INFO","errKind":"","time":"2021-06-26T13:30:41.678685948Z","message":"Unable to read 'format.json' from https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/export0: Post \"https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export0/v37/readall?disk-id=\u0026file-path=format.json\u0026volume=.minio.sys\": x509: certificate is valid for storage1-ss-0-0.storage1-hl.min3.svc.cluster.local, minio.min3.svc.cluster.local, minio.min3, minio.min3.svc, *., *.min3.svc.cluster.local, not storage1-ss-1-0.storage1-hl.min3.svc.cluster.local\n"}
{"level":"INFO","errKind":"","time":"2021-06-26T13:30:41.678721352Z","message":"Unable to read 'format.json' from https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/export1: Post \"https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export1/v37/readall?disk-id=\u0026file-path=format.json\u0026volume=.minio.sys\": x509: certificate is valid for storage1-ss-0-0.storage1-hl.min3.svc.cluster.local, minio.min3.svc.cluster.local, minio.min3, minio.min3.svc, *., *.min3.svc.cluster.local, not storage1-ss-1-0.storage1-hl.min3.svc.cluster.local\n"}
{"level":"INFO","errKind":"","time":"2021-06-26T13:30:41.678735919Z","message":"Unable to read 'format.json' from https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/export2: Post \"https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export2/v37/readall?disk-id=\u0026file-path=format.json\u0026volume=.minio.sys\": x509: certificate is valid for storage1-ss-0-0.storage1-hl.min3.svc.cluster.local, minio.min3.svc.cluster.local, minio.min3, minio.min3.svc, *., *.min3.svc.cluster.local, not storage1-ss-1-0.storage1-hl.min3.svc.cluster.local\n"}
{"level":"INFO","errKind":"","time":"2021-06-26T13:30:41.678750647Z","message":"Unable to read 'format.json' from https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/export3: Post \"https://storage1-ss-1-0.storage1-hl.min3.svc.cluster.local:9000/minio/storage/export3/v37/readall?disk-id=\u0026file-path=format.json\u0026volume=.minio.sys\": x509: certificate is valid for storage1-ss-0-0.storage1-hl.min3.svc.cluster.local, minio.min3.svc.cluster.local, minio.min3, minio.min3.svc, *., *.min3.svc.cluster.local, not storage1-ss-1-0.storage1-hl.min3.svc.cluster.local\n"}
{"level":"ERROR","errKind":"MINIO","time":"2021-06-26T13:30:41.67881858Z","api":{"name":"SYSTEM","args":{"bucket":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","object":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5"}},"remotehost":"5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5","error":{"message":"*errors.errorString","source":["cmd/prepare-storage.go:268:cmd.connectLoadInitFormats()","cmd/prepare-storage.go:317:cmd.waitForFormatErasure()","cmd/erasure-server-pool.go:91:cmd.newErasureServerPools()","cmd/server-main.go:592:cmd.newObjectLayer()","cmd/server-main.go:521:cmd.serverMain()"]}}
{"level":"INFO","errKind":"","time":"2021-06-26T13:30:41.678841888Z","message":"Waiting for a minimum of 2 disks to come online (elapsed 4m21s)\n"}
```

error in new one (storage1-ss-1-0):
```
...
2021/06/26 13:31:26 http: TLS handshake error from 192.168.231.76:38492: remote error: tls: bad certificate
2021/06/26 13:31:26 http: TLS handshake error from 192.168.231.76:38498: remote error: tls: bad certificate
2021/06/26 13:31:26 http: TLS handshake error from 192.168.231.76:38496: remote error: tls: bad certificate
2021/06/26 13:31:26 http: TLS handshake error from 192.168.231.76:38490: remote error: tls: bad certificate
...
```
I use autocert.

## Expected Behavior
adding the new pool without problem

## Current Behavior
get a TLS problem

## Possible Solution
I add the dnsNames to the certConfig, but error insists

## Steps to Reproduce (for bugs)
1. create a new tenant using create command and save the output as yaml file
2. apply the generated above yaml file
3. edit the yaml file and add a new pool
4. apply the new yaml and error happens.

## Context
k8s

## Your Environment

* Version used (`minio-operator`): 4.1.2
* Environment name and version (e.g. kubernetes v1.17.2):  k8s: 1.20.1
* Server type and version: ubuntu 20.04
* Operating System and version (`uname -a`): 
```
Linux Ubuntu-2004-focal-64-minimal 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your deployment file:
deployment file before adding new pool
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: storage1
  namespace: min3
scheduler:
  name: ""
spec:
  certConfig:
    dnsNames:
      - '*.storage1-hl.min3.svc.cluster.local'
  console:
    consoleSecret:
      name: storage1-console-secret
    image: minio/console:v0.7.4
    replicas: 2
    resources: {}
  credsSecret:
    name: storage1-creds-secret
  image: minio/minio:RELEASE.2021-06-17T00-10-46Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 0.9Ti
        storageClassName: local-storage
        selector:
          matchLabels:
            storage-tier: server1
      status: {}
    volumesPerServer: 4
  requestAutoCert: true
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
```
deployment file afteradding new pool
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: storage1
  namespace: min3
scheduler:
  name: ""
spec:
  certConfig:
    dnsNames:
      - '*.storage1-hl.min3.svc.cluster.local'
  console:
    consoleSecret:
      name: storage1-console-secret
    image: minio/console:v0.7.4
    replicas: 2
    resources: {}
  credsSecret:
    name: storage1-creds-secret
  image: minio/minio:RELEASE.2021-06-17T00-10-46Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 0.9Ti
        storageClassName: local-storage
        selector:
          matchLabels:
            storage-tier: server1
      status: {}
    volumesPerServer: 4
  - resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 0.9Ti
        storageClassName: local-storage
        selector:
          matchLabels:
            storage-tier: server2
      status: {}
    volumesPerServer: 4
  requestAutoCert: true
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
```
