### ISSUE TITLE
Operator v4.1.3 continuously updates tenant state from "Initialized" to "Provisioning Console Deployment" and back

### ISSUE THREAD

**Issue by dnskr** [minio/operator#715]
Tenant state continuously changes from "Initialized" to "Provisioning Console Deployment" and back if Operator v4.1.3 and minio-operator:4.1.7 chart is used

## Expected Behavior
"Provisioning Console Deployment" -> "Initialized"

## Current Behavior
"Provisioning Console Deployment" -> "Initialized" -> "Provisioning Console Deployment" -> "Initialized" -> ...

## Steps to Reproduce (for bugs)
**Install operator v4.1.3 by minio-operator 4.1.7 chart**
1. install helm chart minio-operator:4.1.7 - issue occurs

**Upgrading operator v4.1.2 to v4.1.3 by upgrading chart minio-operator 4.1.6 to 4.1.7**
1. install helm chart minio-operator:4.1.6 - no issue
2. upgrade helm chart to minio-operator:4.1.7 - issue occurs
3. set version back to minio-operator:4.1.6 - no issue

Tenant manifest with state
```yaml
  apiVersion: minio.min.io/v2
  kind: Tenant
  metadata:
    name: minio
    namespace: minio-tenant
  spec:
    console:
      image: minio/console:v0.7.5
      replicas: 1
      resources: {}
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    imagePullPolicy: IfNotPresent
    mountPath: /export
    podManagementPolicy: Parallel
    pools:
    - affinity: {}
      nodeSelector: {}
      resources: {}
      servers: 1
      tolerations: []
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
          storageClassName: standard
      volumesPerServer: 4
  status:
    availableReplicas: 1
    certificates:
      autoCertEnabled: false
    currentState: Provisioning Console Deployment
    drivesOnline: 4
    healthStatus: green
    pools:
    - ssName: minio-ss-0
      state: PoolInitialized
    revision: 0
    syncVersion: ""
    writeQuorum: 3
```
