### ISSUE TITLE
Support Sealed-Secrets for Admin credentials by using existingSecret 

### ISSUE THREAD

**Issue by haim-ari** [minio/operator#718]
Unlike in the [old helm chart](https://github.com/minio/charts), there is no option to use Sealed Secrets in order to generate the Admin User and Password during installation

(there is no option to simply use `existingSecret` and map `accesskey` & `secretkey` from a `secret` name) 

When using Flux, having `Sealed Secrets` supported in the Helm Chart of the operator will make installation much less complex than using SOAPS and not less secure.

See the complexity of using M SOPS with [Flux](https://fluxcd.io/docs/guides/mozilla-sops/)
See the simplicity of using Sealed-Secrets with [Flux](https://fluxcd.io/docs/guides/sealed-secrets/)

It would be nice to have Sealed-Secrets supported as well, and also allow to create Buckets with default credentials specified from an  `secret` name.

**Comment by aavbsouza** [comment]
Would be great to have an option to support using a preexistent secret for GitOps

**Comment by aavbsouza** [comment]
Hello, for anyone using Flux 2 a possible workaround the issue is to use Helm Release [postRenderers](https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers). For instance:

```yaml
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: minio.min.io/v2
            kind: Tenant
            metadata:
              name: my-tenant
              namespace: my-tenant-ns
            spec:
              credsSecret:
                name: my-new-secret
```

The secret `my-new-secret` could be encrypted using SOPS, for instance
