### ISSUE TITLE
Minio-operator Tenant Service Issue

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#723]
I have deployed minio tenant and console using the minio operator.
I have few questions regarding this.....
1. I havent configured or seen anywhere the service files related to  minio Tenant and console.
2. I wont be able to change the default ports for minio tenant and console services, because of this I am not able to access the UI's externally.
3.  How to connect minio client to the minio tenant as tls is enabled by default.

Help is really appreciated.

**Comment by mjschmidt** [comment]
1. The operator makes the service files for you as ClusterIP services. You could expose these services via an ingress
2. You shouldn't care about the ports so long as you can expose the service via an ingress controller
3. Once the tenant is exposed external to the cluster via an ingress, you can connect from external to the cluster via the ingress address.

I am not on the minio team, but I have been using K8s for a while. Hopefully this has been helpful. For more info on Kubernetes ingress, read up here:
https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

**Comment by Vineeth-varma** [comment]
You said operator makes the service files right where we can see those files in the operator deployment.

**Comment by mjschmidt** [comment]
To get operator services:
```kubectl get svc -n minio-operator```

To get your tenant's services
```kubectl -n your-tenant-namespace get svc```

**Comment by Vineeth-varma** [comment]
Sorry, you didnt get my question I guess.
Actually the operator will provision services for both minio Tenant and minio tenant console. So how actually that is provisioning are there mentioned somewhere in deployment files of the operator ?
Why I want is whenever I am changing the defaults ports to Loadbalancer port when pod restart happens it is again coming to default ports, I want to control this behaviour.

**Comment by Vineeth-varma** [comment]
In my case I am using metalLB, IP is fixed and port also needs to be fixed (30001), I am not sure where I need to mention this fixed port for minio service. Please just which field I need to edit to make the port permanant instead of 443.

**Comment by dvaldivia** [comment]
@Vineeth-varma in your case, it might be better to copy the selector from the minio service and create another cluster IP with the needed port since we don't expose changing the core service port, this is by design.

**Comment by Vineeth-varma** [comment]
Thanks for your quick response on that service part. one more thing..,
How to deploy minio client for this operator mode of deployment as tls in enabled by default, I am facing issues while creating the 
 minio client alias.

**Comment by Vineeth-varma** [comment]
Can anyone guide me to install minio client for the minio operator

**Comment by mjschmidt** [comment]
@dvaldivia I wanted to let you know that I didn't think that this mattered, but I had a minio helm chart deployment in the same namespace, you may need to restrict to one minio deployment per namespace. The console has not appeared after the helm chart deplyoed minio (bitnami) was removed from the namespace.

**Comment by mjschmidt** [comment]
I cannot close the issue, but this could be considered resolved at this point.

**Comment by rchouhan170590** [comment]
hey when I am running 
kubectl proxy-forward svc/minio  9000:443 -n minio-tenant-1

then after running this command I am not able to access the tenant UI at 
my_public_ip:9000

**Comment by rchouhan170590** [comment]
```
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: myingress
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "false"
spec:
  tls:
  - hosts:
    - myhost.com
    secretName: secrete-1
  rules:
  - host: myhost.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 443
  defaultBackend:
    service:
      name: minio-tenant-1-console
      port:
        number: 9443

```

I am using above ingress yaml file, but not able to connect to minio service (on  https://myhost.com/ )

it returns : 
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>16BFA6DE163CC645</RequestId><HostId>adc40609-3150-475b-a3cb-4140b8f396fe</HostId></Error>

```
