### ISSUE TITLE
Operator service port 4223 seems redundant, 4222 listens on HTTPS

### ISSUE THREAD

**Issue by funkypenguin** [minio/operator#749]
I've been trying to get the latest minio-operator working in an istio-enabled cluster. Minio-operator is deployed (via the latest helm chart) into a namespace with mTLS enabled, and (as expected) kube-apiserver can't talk to https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion?timeout=30s, since it's not "in" the Istio mesh.

The workaround is simply to tell Istio to DISABLE mTLS on port 4222, which I've done:

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: permissive-mtls-for-operator-4222
  namespace: minio-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
  mtls:
    mode: UNSET
  portLevelMtls:
    "4222":
      mode: DISABLE
```

What's strange is that after doing this, kube-apiserver now logs:

```
cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list minio.min.io/v1, Kind=Tenant: conversion 
webhook for minio.min.io/v2, Kind=Tenant failed: Post "https://operator.minio-operator.svc:4222/webhook/v1/crd-conversion?
timeout=30s": http: server gave HTTP response to HTTPS client; reinitializing
```

The operator exposes has 2 ports:

```
  ports:
  - name: http
    port: 4222
    protocol: TCP
    targetPort: 4222
  - name: https
    port: 4233
    protocol: TCP
    targetPort: 4233
```

Now, Istio does do some funky protocol-detection stuff based on service names, so when a service is named `http`, it's going to proxy through that traffic as HTTP. But in our case, it seems minio-operator actually listens on HTTPS on port 4222.

Further, from a quick search of the source, I don't see that port 4233 is used anywhere (anymore?).

Changing the port names like this, fix my immediate istio problem:

```
  ports:
  - name: https
    port: 4222
    protocol: TCP
    targetPort: 4222
  - name: https2
    port: 4233
    protocol: TCP
    targetPort: 4233
```

And kube-apiserver is happy.

If port 4233 is no longer required, I'm happy to submit a PR to have it removed from the chart, and to have port 4222 renamed to `https` to make us Istio-ers happ(ier) ;)

Cheers!
D
