### ISSUE TITLE
[Helm] tenant creation issue

### ISSUE THREAD

**Issue by jr0dd** [minio/operator#757]
I'm trying to deploy this chart while merging only what I want to change in the values.yaml. The tenant template is expecting all of those values that I'm not touching. The template needs adjusting so you can run `helm install minio-operator minio/minio-operator -f values.yaml` 

helm template:
```
Error: template: minio-operator/templates/tenant.yaml:18:18: executing "minio-operator/templates/tenant.yaml" at <.scheduler.name>: nil pointer evaluating interface {}.name
helm.go:88: [debug] template: minio-operator/templates/tenant.yaml:18:18: executing "minio-operator/templates/tenant.yaml" at <.scheduler.name>: nil pointer evaluating interface {}.name
```

values.yaml
```
console:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    host: "minio.${SECRET_DOMAIN}"
    tls:
      - secretName: minio-tls
        hosts:
          - "minio.${SECRET_DOMAIN}"
tenants:
  - name: minio
    namespace: minio
    pools:
      - servers: 1
        volumesPerServer: 4
        size: 10Gi
        storageClassName: openebs-zfspv
    secrets:
      enabled: true
      name: minio-secret
      accessKey: "${SECRET_MINIO_ACCESSKEY}"
      secretKey: "${SECRET_MINIO_SECRETKEY}"
    metrics:
      enabled: true
      port: 9000
    s3:
      bucketDNS: true
    console:
      secrets:
        enabled: true
        name: console-secret
        passphrase: "${SECRET_MINIO_PASSPHRASE}"
        salt: "${SECRET_MINIO_SALT}"
        accessKey: "${SECRET_MINIO_ACCESSKEY}"
        secretKey: "${SECRET_MINIO_SECRETKEY}"
```
