### ISSUE TITLE
MINIO_SERVER_URL env variable ignored

### ISSUE THREAD

**Issue by AlDemion** [minio/operator#790]
Looks like MINIO_SERVER_URL is hardcoded while deploying minio with the operator, so setting this value from tenant config is silently ignored. 
https://github.com/dvaldivia/operator/blob/master/pkg/resources/statefulsets/minio-statefulset.go#L37-L38

## Expected Behavior
MINIO_SERVER_URL must be changed

## Current Behavior
MINIO_SERVER_URL env variable ignored

## Context
That's causes problems with signed URL sharing, because MINIO_SERVER_URL is set to <svc_name>.<ns_name>.svc.cluster.local

**Comment by reddymh** [comment]
@harshavardhana  after changing the environment value for MINIO_SERVER_URL to ingress url but still ingress url  for minio browser with port 443 is redirecting to 9443 in the browser.
Is there any issue opening minio svc url in browser ?

**Comment by harshavardhana** [comment]
> @harshavardhana after changing the environment value for MINIO_SERVER_URL to ingress url but still ingress url for minio browser with port 443 is redirecting to 9443 in the browser.

It is not yet honored in operator correctly @reddymh

**Comment by reddymh** [comment]
@harshavardhana  is there any fix for this issue ?
was using v4.0.3 MinIO Browser was working expected with ingress and now upgrade to latest have issues with MinIO Browser.

**Comment by harshavardhana** [comment]
> @harshavardhana is there any fix for this issue ?
> was using v4.0.3 MinIO Browser was working expected with ingress and now upgrade to latest have issues with MinIO Browser.

There is no fix yet.

**Comment by fcomte** [comment]
I have exactly the same need

**Comment by harshavardhana** [comment]
You can fix this by setting up a secret 

```yaml
apiVersion: v1
data:
  ## Tenant credentials, base64 encoded (cat config.env | base64)
  ##  export MINIO_ROOT_USER="minio"
  ##  export MINIO_ROOT_PASSWORD="minio123"
  ##  export MINIO_STORAGE_CLASS_STANDARD="EC:2"
  ##  export MINIO_BROWSER="on"
  config.env: ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0ibWluaW8iCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJtaW5pbzEyMyIKZXhwb3J0IE1JTklPX1NUT1JBR0VfQ0xBU1NfU1RBTkRBUk
Q9IkVDOjIiCmV4cG9ydCBNSU5JT19CUk9XU0VSPSJvbiI=
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-tenant
type: Opaque
```

```
echo "ZXhwb3J0IE1JTklPX1JPT1RfVVNFUj0ibWluaW8iCmV4cG9ydCBNSU5JT19ST09UX1BBU1NXT1JEPSJtaW5pbzEyMyIKZXhwb3J0IE1JTklPX1NUT1JBR0VfQ0xBU1NfU1RBTkRBUk
Q9IkVDOjIiCmV4cG9ydCBNSU5JT19CUk9XU0VSPSJvbiI=" | base64 --decode
```

```
export MINIO_ROOT_USER="minio"
export MINIO_ROOT_PASSWORD="minio123"
export MINIO_STORAGE_CLASS_STANDARD="EC:2"
export MINIO_BROWSER="on"
```

Then use this secret as part of the `tenant.spec.configuration` 

```yml
  ## Secret with credentials and configurations to be used by MinIO Tenant.
  configuration:
    name: storage-configuration
```

This would override any settings that you may have.
