### ISSUE TITLE
[Bug] parse error at (minio-operator/templates/tenant.yaml:11): function "dig" not defined

### ISSUE THREAD

**Issue by PatrickHuetter** [minio/operator#802]
Dear minio team,

we wanted to deploy the minio-operator using your helm chart and [rancher fleet](https://github.com/rancher/fleet). Fleet internally uses helm.
This is our fleet.yaml:
```
defaultNamespace: minio-operator

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: minio-operator

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: "minio-operator"

  repo: "https://operator.min.io"

  version: "4.2.3"

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 0

  # Custom values that will be passed as values.yaml to the installation
  values:
```

As you can see we don't provide any values.yaml and also if we provide some, we always get the following exception from helm (called by fleet):
```
parse error at (minio-operator/templates/tenant.yaml:11): function "dig" not defined
```

What could be the cause for that? We aren't sure wether it's a fleet or MinIO operator chart bug. Or do we miss something?
