### ISSUE TITLE
tenant fails creation with RELEASE.2021-09-03T03-56-13Z

### ISSUE THREAD

**Issue by jr0dd** [minio/operator#803]
The operator and operator console load up fine on 4.2.4. But there is an issue when creating the tenant after updating to RELEASE.2021-09-03T03-56-13Z. Rolling back to RELEASE.2021-08-31T05-46-54Z got everything back up and running again.

```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://Mg8Cc4bzEdqMOddlnSL7:o1vjIbF6RCHySn3cM5CVAllejppL7K1BHRPK0PCm@operator.minio.svc.cluster.local:4222/webhook/v1/getenv/minio/tenant0: Get "https://operator.minio.svc.cluster.local:4222/webhook/v1/getenv/minio/tenant0?key=MINIO_ARGS": dial tcp 172.17.100.186:4222: connect: connection refused
```

**Comment by dshuvar** [comment]
same case

**Comment by harshavardhana** [comment]
> The operator and operator console load up fine on 4.2.4. But there is an issue when creating the tenant after updating to RELEASE.2021-09-03T03-56-13Z. Rolling back to RELEASE.2021-08-31T05-46-54Z got everything back up and running again.
> 
> ```
> ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://Mg8Cc4bzEdqMOddlnSL7:o1vjIbF6RCHySn3cM5CVAllejppL7K1BHRPK0PCm@operator.minio.svc.cluster.local:4222/webhook/v1/getenv/minio/tenant0: Get "https://operator.minio.svc.cluster.local:4222/webhook/v1/getenv/minio/tenant0?key=MINIO_ARGS": dial tcp 172.17.100.186:4222: connect: connection refused
> ```

This error is correct it shows that operator should have the webhook running and it's not running.

**Comment by harshavardhana** [comment]
Do you have network policies that restrict access for MinIO tenant pods to talk to operator namespace? @jr0dd @dshuvar

**Comment by jr0dd** [comment]
> Do you have network policies that restrict access for MinIO tenant pods to talk to operator namespace? @jr0dd @dshuvar

No I do not. Rolling back to RELEASE.2021-08-31T05-46-54Z fixed it for now. Any attempt to update today's build gives that error.

**Comment by harshavardhana** [comment]
> No I do not. Rolling back to RELEASE.2021-08-31T05-46-54Z fixed it for now. Any attempt to update today's build gives that error.

That rollback is not right @jr0dd the issue is very clear operator webhook is not reachable. 

The upgrade is showing an existing problem in our operator since it was using a fallback hack previously that is removed in the latest releases.

**Comment by harshavardhana** [comment]
Please share the operator logs @jr0dd

**Comment by jr0dd** [comment]
```
I0903 17:48:34.764102       1 main-controller.go:700] minio/tenant0 Detected we are adding a new pool
I0903 17:48:34.771123       1 main-controller.go:841] 'minio/tenant0' Error waiting for pool to be ready: Get "https://tenant0-ss-0-0.tenant0-hl.minio.svc.cluster.local:9000/minio/admin/v3/info": dial tcp 172.16.0.180:9000: connect: connection refused
E0903 17:48:34.771214       1 main-controller.go:461] error syncing 'minio/tenant0': Waiting for all pools to initialize
I0903 17:48:34.959925       1 monitoring.go:106] 'minio/tenant0' no pool is initialized
I0903 17:48:35.750272       1 monitoring.go:106] 'minio/tenant0' no pool is initialized
```

**Comment by harshavardhana** [comment]
> I0903 17:48:34.764102       1 main-controller.go:700] minio/tenant0 Detected we are adding a new pool
> I0903 17:48:34.771123       1 main-controller.go:841] 'minio/tenant0' Error waiting for pool to be ready: Get "https://tenant0-ss-0-0.tenant0-hl.minio.svc.cluster.local:9000/minio/admin/v3/info": dial tcp 172.16.0.180:9000: connect: connection refused
> E0903 17:48:34.771214       1 main-controller.go:461] error syncing 'minio/tenant0': Waiting for all pools to initialize
> I0903 17:48:34.959925       1 monitoring.go:106] 'minio/tenant0' no pool is initialized
> I0903 17:48:35.750272       1 monitoring.go:106] 'minio/tenant0' no pool is initialized

can you start a ubuntu container and then try to reach out to `curl https://operator.minio.svc.cluster.local:4222 --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

**Comment by harshavardhana** [comment]
@jr0dd also can you list out the steps properly here what you did here?

**Comment by jr0dd** [comment]
> > I0903 17:48:34.764102       1 main-controller.go:700] minio/tenant0 Detected we are adding a new pool
> > I0903 17:48:34.771123       1 main-controller.go:841] 'minio/tenant0' Error waiting for pool to be ready: Get "https://tenant0-ss-0-0.tenant0-hl.minio.svc.cluster.local:9000/minio/admin/v3/info": dial tcp 172.16.0.180:9000: connect: connection refused
> > E0903 17:48:34.771214       1 main-controller.go:461] error syncing 'minio/tenant0': Waiting for all pools to initialize
> > I0903 17:48:34.959925       1 monitoring.go:106] 'minio/tenant0' no pool is initialized
> > I0903 17:48:35.750272       1 monitoring.go:106] 'minio/tenant0' no pool is initialized
> 
> can you start a ubuntu container and then try to reach out to `curl https://operator.minio.svc.cluster.local:4222 --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt`

```
*   Trying 172.17.173.3:4222...
* TCP_NODELAY set
* connect to 172.17.173.3 port 4222 failed: Connection refused
* Failed to connect to operator.minio.svc.cluster.local port 4222: Connection refused
* Closing connection 0
curl: (7) Failed to connect to operator.minio.svc.cluster.local port 4222: Connection refused
```

**Comment by jr0dd** [comment]
> @jr0dd also can you list out the steps properly here what you did here?

all i did was change the image to the new release. nothing else

**Comment by jr0dd** [comment]
@harshavardhana 
```
operator:
  image:
    repository: quay.io/minio/operator
    tag: v4.2.4
console:
  image:
    repository: quay.io/minio/console
    tag: v0.9.6
  ingress:
    enabled: true
    ingressClass: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    host: "minio.${SECRET_DOMAIN}"
    path: /
    tls:
      - secretName: minio-tls
        hosts:
          - "minio.${SECRET_DOMAIN}"
tenants:
  - name: tenant0
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2021-08-31T05-46-54Z
    namespace: minio
    pools:
      - servers: 4
        volumesPerServer: 1
        size: 20Gi
        storageClassName: openebs-zfspv
    secrets:
      enabled: true
      name: minio-creds
      accessKey: "${MINIO_ACCESS_KEY}"
      secretKey: "${MINIO_SECRET_KEY}"
    metrics:
      enabled: true
      port: 9000
    certificate:
      requestAutoCert: true
    env:
      - name: MINIO_BROWSER_REDIRECT_URL
        value: "https://minio.${SECRET_DOMAIN}"
```
