### ISSUE TITLE
Support http/tls-disabled tenant

### ISSUE THREAD

**Issue by Roshick** [minio/operator#816]
**Is your feature request related to a problem? Please describe.**
I'm currently facing the issue that there is (appearently ?) no way to create a tenant whose service is accessible via http. As we use self-signed certificates within our company, which are unsupported by many tools (e.g. argo workflows or reportportal in our case), we have to access the minio service via http and therefore had to use the legacy helm chart. As the old helm chart is unsupported now, it would be nice to use the operator for our use case.

**Describe the solution you'd like**
I want to be able to access the minio service created by a tenant with tls disabled (configurable by a flag, default set to false).

**Describe alternatives you've considered**
I thought about creating an issue at argo-workflows to support a way of mounting the certificates to their container, but this would only solve it for this one case and won't work in other cases.

**Comment by dnskr** [comment]
I'm not sure I understand your issue correctly, but you can disable TLS for [Tenant](https://github.com/minio/operator/blob/master/examples/tenant-tiny.yaml#L121)
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  ...
spec:
  requestAutoCert: false
  ...
```
Also you can do the same with minio-operator helm [chart](https://github.com/minio/operator/blob/master/helm/minio-operator/values.yaml#L129) in `values.yaml`
```
operator:
  ...
console:
  ..
tenants:
  - name: minio1
    ...
    certificate:
      externalCaCertSecret: {}
      externalCertSecret: {}
      requestAutoCert: false
      certConfig: {}
```
Does it solve your issue?
