### ISSUE TITLE
Cannot see metrics in minio operator console

### ISSUE THREAD

**Issue by pratikbalar** [minio/operator#822]
## Current Behavior

Cannot see metrics in operator, log says 
```
...
E: 2021/09/10 06:30:30 Unable to fetch labels from prometheus http://improwised-prometheus-hl-svc.minio:9090/api/v1/query_range?query=time%28%29+-+max%28minio_node_process_starttime_seconds%7Bjob%3D%22minio-job%22%7D%29&start=1631254530&end=1631255430&step=60, Get "http://improwised-prometheus-hl-svc.minio:9090/api/v1/query_range?query=time%28%29+-+max%28minio_node_process_starttime_seconds%7Bjob%3D%22minio-job%22%7D%29&start=1631254530&end=1631255430&step=60": dial tcp: lookup improwised-prometheus-hl-svc.minio on 10.245.0.10:53: no such host
E: 2021/09/10 06:30:30 Unable to fetch labels from prometheus http://improwised-prometheus-hl-svc.minio:9090/api/v1/query_range?query=topk%281%2C+sum%28minio_cluster_capacity_usable_free_bytes%7Bjob%3D%22minio-job%22%7D%29+by+%28instance%29%29&start=1631254530&end=1631255430&step=300, Get "http://improwised-prometheus-hl-svc.minio:9090/api/v1/query_range?query=topk%281%2C+sum%28minio_cluster_capacity_usable_free_bytes%7Bjob%3D%22minio-job%22%7D%29+by+%28instance%29%29&start=1631254530&end=1631255430&step=300": dial tcp: lookup improwised-prometheus-hl-svc.minio on 10.245.0.10:53: no such host
...
```
and I can't see `improwised-prometheus-hl-svc` service 

![minio](https://user-images.githubusercontent.com/68642400/132809912-c2fedc1f-9dac-441d-86e4-02f53819345b.gif)

## Steps to Reproduce (for bugs)

1. Deployed minio helm operator helm chart version 4.1.7 and created tenant form values
  ```yaml
# Default values for minio-operator.

operator:
  env:
    - name: TZ
      value: "UTC"
  image:
    repository: minio/operator
    tag: v4.1.3
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  initcontainers: []
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

console:
  image:
    repository: minio/console
    tag: v0.7.5
    pullPolicy: IfNotPresent
  imagePullSecrets: []
  initcontainers: []
  replicaCount: 1
  nodeSelector: {}
  affinity: {}
  tolerations: []
  resources: {}
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  ingress:
    enabled: false
    # path: /
## MinIO Tenant Definition
tenants:
  - name: xxx
    image:
      repository: minio/minio
      tag: RELEASE.2021-08-17T20-53-08Z
      pullPolicy: IfNotPresent
    namespace: minio
    imagePullSecret: {}
    scheduler: {}
    pools:
      - servers: 2
        volumesPerServer: 2
        size: 100Gi
        storageClassName: xxx
        tolerations: {}
        nodeSelector: {}
        affinity: {}
        resources:
          requests:
            memory: 200Mi
            cpu: 80m
          limits:
            memory: 500Mi
            cpu: 200m
        securityContext: {}
    mountPath: /export
    subPath: /data
    secrets:
      enabled: true
      name: xxx
      accessKey: xxx
      secretKey: xxx
    metrics:
      enabled: true
      port: 9000
    certificate:
      externalCaCertSecret: {}
      externalCertSecret: {}
      requestAutoCert: true
      certConfig: {}
    s3:
      bucketDNS: false
    podManagementPolicy: Parallel
    serviceMetadata: {}
    env:
      - name: TZ
        value: "UTC"
    priorityClassName: ""
    console:
      image:
        repository: minio/console
        tag: v0.7.5
        pullPolicy: IfNotPresent
      replicaCount: 1
      secrets:
        enabled: true
        name: console-secret
        passphrase: SECRET
        salt: SECRET
        accessKey: xxx
        secretKey: xxx
      tolerations: []
      nodeSelector: {}
      affinity: {}
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
          cpu: 200m
      securityContext: {}
      env:
        - name: TZ
          value: "UTC"
      externalCaCertSecret: {}
      externalCertSecret: {}
  ```

## Your Environment

* Version used (`minio-operator`): 4.1.7
* Environment name and version (e.g. kubernetes v1.17.2): k8s v1.20.2 
* Server type and version: 
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by harshavardhana** [comment]
You need to have `prometheus` running properly for the metrics to work.

**Comment by pratikbalar** [comment]
Prometheus is running with operator.

**Comment by pratikbalar** [comment]
Don't you think operator should create `xxx-prometheus-hl-svc` ?

**Comment by jr0dd** [comment]
> Don't you think operator should create `xxx-prometheus-hl-svc` ?

you need to add the prometheus spec to your tenant. Since the chart does not support yet I just use kustomize to patch for me.

```
spec:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.29.2
    sidecarimage: alpine
    initimage: busybox
    diskCapacityGB: 5
  prometheusOperator:
    labels:
      app: tenant0
```

**Comment by dvaldivia** [comment]
@pratikbalar it should be created

**Comment by pratikbalar** [comment]
@jr0dd thanks snippet, @dvaldivia I followed this <https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/minio-metrics-and-alerts.html> and added `CONSOLE_PROMETHEUS_URL` in minio console, now I can see metrics in tenants console but still not in operator console.

**Comment by dvaldivia** [comment]
@pratikbalar you mean inside the tenant details and then metrics tab?

Did you install this tenant with helm?

I noticed an issue today where we don't create the service for Prometheus if it's configured after the tenant starts so I think I have to fix that

**Comment by dvaldivia** [comment]
@pratikbalar have you upgraded to the latest `v4.2.7` ? I cannot reproduce this problem on that release

**Comment by jr0dd** [comment]
> @pratikbalar have you upgraded to the latest `v4.2.7` ? I cannot reproduce this problem on that release

Weird all my metrics data is empty in the console today. Everything is in grafana though. Is it absolutely necessary to use the Prometheus sidecar if you already have a Prometheus server? Any thoughts on adding a service monitor to the chart?

**Comment by pratikbalar** [comment]
No @jr0dd , i think I'll upgrade if it's necessary, right now, i can see metrics in tenant's console after setting env var in console for our main Prometheus.

@dvaldivia yes i installed tenant with helm

**Comment by jr0dd** [comment]
> No @jr0dd, I think I'll upgrade unless it's necessary. right now, I can see metrics in tenant's console after setting env var in console for our main Prometheus.
> 
> > Did you install this tenant with helm?
> 
> @dvaldivia yes I installed tenant with helm

I got it working with a manually deployed servicemonitor and some extra env vars.

```
        env:
          - name: MINIO_PROMETHEUS_AUTH_TYPE
            value: "public"
          - name: MINIO_PROMETHEUS_JOB_ID
            value: "minio"
          - name: MINIO_PROMETHEUS_URL
            value: "http://prometheus-prometheus.monitoring:9090"
          - name: CONSOLE_PROMETHEUS_URL
            value: "http://prometheus-prometheus.monitoring:9090"
```
```
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  labels:
    v1.min.io/tenant: tenant0
spec:
  jobLabel: minio
  selector:
    matchLabels:
      v1.min.io/tenant: tenant0
  namespaceSelector:
    matchNames:
      - minio
  endpoints:
    - port: https-minio
      interval: 30s
      scrapeTimeout: 10s
      path: /minio/v2/metrics/cluster
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
    - port: https-minio
      interval: 30s
      scrapeTimeout: 10s
      path: /minio/v2/metrics/node
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
```
