### ISSUE TITLE
Failed to deploy MinIO if cluster has domain name

### ISSUE THREAD

**Issue by Hongbo-Miao** [minio/operator#836]
## Expected Behavior

My cluster has its own domain name. I am expecting MinIO can be successfully deployed by operator, 

## Current Behavior

However, it failed with error:

```sh
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://7xsmWekrUg3kF0kQQbjJ:XHPmZLeH0ChYnH8TkvtogNqUpTinbzxO3piR93wk@operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/tenant-tiny/storage-tiny: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/tenant-tiny/storage-tiny?key=MINIO_ARGS": dial tcp: lookup operator.minio-operator.svc.cluster.local on 10.43.0.10:53: no such host
```

## Possible Solution

One potential solution is similar to a Dgraph issue I met before https://github.com/dgraph-io/dgraph/pull/7976 by removing hardset `cluster.local` or allow us pass own domain name.

It would be great to support the cluster with domain name. Thanks! 😃

### Step 1 - create a cluster with a domain name

Assume cloned the project at `/Users/xxx/Downloads/operator`, create an empty `data` folder at `/Users/xxx/Downloads/operator/data`.

Create a `/Users/xxx/Downloads/operator/dev-cluster-config.yaml` file:

```yml
apiVersion: k3d.io/v1alpha2
kind: Simple
kubeAPI:
  host: "k8s-hongbomiao.com"
  hostIP: "127.0.0.1"
  hostPort: "6442"
network: hm-network
volumes:
  - volume: "/Users/xxx/Downloads/operator/data:/data"
ports:
  - port: 40002:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
      # without below line or change to "--cluster-domain=cluster.local", Yugabyte can be installed successfully
      - --cluster-domain=dev.k8s-hongbomiao.com
```

Then create a `dev` cluster by [k3d](https://k3d.io/v4.4.8/) if you are using macOS by

```sh
k3d cluster create dev --config=dev-cluster-config.yaml
```

### Step 2 - deploy MinIO

Create a `/Users/xxx/Downloads/operator/minio-pv.yaml` file with content

<details>
  <summary>Click to see yugabyte-pv.yaml content!</summary>

  ```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-tiny-prometheus-storage-tiny-prometheus-0-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/log
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-tiny-log-storage-tiny-log-0-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prometheus
    type: Directory
  ```
</details>

Then run

```sh
rm -rf data/log
rm -rf data/prometheus
mkdir data/log
mkdir data/prometheus

kubectl minio init
kubectl minio proxy --namespace=minio-operator &
kubectl apply --filename=minio-pv.yaml
kubectl apply --kustomize=examples/kustomization/tenant-tiny
```

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", 
  GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", 
  GoVersion:"go1.16.7", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10+k3s1", 
  GitCommit:"fedc68f73dc79f664f8149e93ac60694249b91c4", GitTreeState:"clean", BuildDate:"2021-08-20T07:14:07Z", 
  GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Server type and version:
* Operating System and version (`uname -a`):
  ```
  Darwin LCNC02F10MAMD6R 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
  ```
* Link to your deployment file:
