### ISSUE TITLE
Unable to read format.json after upgrading operator

### ISSUE THREAD

**Issue by haslersn** [minio/operator#851]
After updating the operator from `github.com/minio/operator?ref=v4.1.3` to `github.com/minio/operator?ref=v4.2.10`, my MinIO tenant wasn't accessible anymore. The pods showed the following error:

```
Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export0: file access denied

Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export0: file access denied

Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export0: file access denied

Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export1: file access denied

Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export1: file access denied

Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export1: file access denied

Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export2: file access denied

Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export2: file access denied

Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export2: file access denied

Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export3: file access denied

Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export3: file access denied

Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export3: file access denied
```

(I think the same happens with `v4.2.5` instead of `v4.2.10`.) I resolved this by rolling back the operator to `v4.1.3`.

## Expected Behavior

The MinIO tenant should continue working.

## Steps to Reproduce (for bugs)

1. Deploy `github.com/minio/operator?ref=v4.1.3`
2. Deploy the following tenant:
```
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  image: minio/minio:RELEASE.2021-09-18T18-09-59Z
  podManagementPolicy: Parallel
  credsSecret:
    name: minio-creds-secret
  requestAutoCert: true
  users: []
  pools:
    - servers: 3
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaim
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1863Gi
          storageClassName: s3-zone-0
      resources:
        limits:
          memory: 8Gi
    - servers: 3
      volumesPerServer: 4
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaim
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 14902Gi
          storageClassName: s3-zone-1
      resources:
        limits:
          memory: 64Gi
  console:
    image: minio/console:v0.10.0
    replicas: 2
    consoleSecret:
      name: minio-console-secret
  kes:
    image: minio/kes:v0.16.1
    replicas: 3
    kesSecret:
      name: minio-kes-config
```
3. Replace the operator deployment by `github.com/minio/operator?ref=v4.2.10`

## Your Environment

* Environment name and version: Kubernetes v1.19.15
* Server type and version: Debian 10
* Operating System and version (`uname -a`): Linux kube01 4.19.0-17-amd64 Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
> Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export0: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export0: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export0: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export1: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export1: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export1: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export2: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export2: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export2: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-0.minio-hl.s3.svc.cluster.local:9000/export3: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-1.minio-hl.s3.svc.cluster.local:9000/export3: file access denied
> 
> Unable to read 'format.json' from https://minio-ss-0-2.minio-hl.s3.svc.cluster.local:9000/export3: file access denied

you need to change your securityContext - by default Operator now runs with securityContext `on` by default.

**Comment by haslersn** [comment]
When adding the following to the pools, I get the same error on minio-operator `v4.1.3`.

```
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
```

**Comment by haslersn** [comment]
Or did you mean that I should change the permissions of the files within the exports?

**Comment by harshavardhana** [comment]
> Or did you mean that I should change the permissions of the files within the exports?

They need match your disk permissions, of course.

**Comment by haslersn** [comment]
This is now a documentation issue: The release notes should state that one needs to `chown -R 1000:1000` on the data before upgrading the operator.

**Comment by haslersn** [comment]
I just looked through related PRs and it seems like #799 (introduced in v4.2.4) was there to prevent the problem I had. However, apparently it didn't work when upgrading directly from v.4.1.3 to v4.2.10.

**Comment by harshavardhana** [comment]
> I just looked through related PRs and it seems like #799 (introduced in v4.2.4) was there to prevent the problem I had. However, apparently it didn't work when upgrading directly from v.4.1.3 to v4.2.10.
> 
> Maybe the fact is relevant, that I specify my Tenant declaratively. I'm not using the operator CLI.

@dvaldivia ^^

**Comment by harshavardhana** [comment]
> This is now a documentation issue: The release notes should state that one needs to `chown -R 1000:1000` on the data before upgrading the operator.

You do not need to do that just set the correct security context, i.e let it use root instead of 1000

**Comment by dvaldivia** [comment]
@haslersn the operator on the latest `v4.2.10` fixes this problem in an automated fashion, so I'd recommend to upgrade straight to that version.

We tried to document this change on [UPGRADE.md](https://github.com/minio/operator/blob/master/UPGRADE.md), I'm sorry that you found it.

Since your data is owned by root, you'll have to add a `securityContext` to your pools, more specifically:

```
securityContext:
  fsGroup: 0
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
```

This should fix your problem, let me know if it worked.
