### ISSUE TITLE
v4.2.8 credsSecret optional/required?

### ISSUE THREAD

**Issue by aceeric** [minio/operator#856]
According to the example - https://github.com/minio/operator/blob/v4.2.8/examples/kustomization/base/tenant.yaml:

```
spec:
  ...
  configuration:
    name: storage-configuration
  ## DEPRECATED: Secret with credentials to be used by MinIO Tenant.
  credsSecret:
    name: storage-creds-secret
  ...
```
credsSecret is deprecated but - if you omit it from the Tenant CR, then the Tenant never initializes. Status is always "please set credsSecret secret with credentials for Tenant". Sounds like: https://github.com/minio/operator/issues/614.

But that issue is closed. Can you please clarify if `spec.credsSecret` is optional/required in this/later release? Thank you.
