### ISSUE TITLE
How to provide volumes and volumeMounts  in tenant.yaml for keyclaok cert

### ISSUE THREAD

**Issue by Vineeth-varma** [minio/operator#870]
Hi Minio Team..,

I am working on the Minio Opertor for that I am integrating it with Keycloak. I am facing one issue with certificate as my keycloak is ssl protected.

I have two questions here
1.)  I need to provide keyclaok.pem certificate so in tenant.yaml where I can provide that.
       i.) If I can provide directly in the tenant.yaml what is the path?
       ii) Or Do I have to pass it as a secret file which path again.
2.) If it is through secret file then how to give volumes and volumeMounts as in tenant I am not able to pass?

Hope this can be answered atleast..,

**Comment by Alevsk** [comment]
Take a look at this documentation https://github.com/minio/operator/blob/master/examples/kustomization/base/tenant.yaml#L74

You have to use the `externalCaCertSecret` field on your tenant CRD, ie:

```
externalCaCertSecret:
  - name: ca-certificate-1
    type: Opaque
  - name: ca-certificate-2
    type: Opaque
  - name: ca-certificate-3
    type: Opaque
```

Create secrets as explained here:
https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
