### ISSUE TITLE
Operator Github DOCS are outdated

### ISSUE THREAD

**Issue by Mageswaran1989** [minio/operator#902]
## Expected Behavior

Create tenant by following the steps mentioned in the readme file @ https://github.com/minio/operator/blob/master/docs/kes.md#create-minio-tenant

## Current Behavior

Getting following file not found error:
```
kubectl create -f https://raw.githubusercontent.com/minio/operator/master/examples/console-secret.yaml --namespace tenant1-ns
error: unable to read URL "https://raw.githubusercontent.com/minio/operator/master/examples/console-secret.yaml", server reported 404 Not Found, status code=404
```

## Possible Solution
Readme needs to be updated 

## Steps to Reproduce (for bugs)
```
kubectl create -f https://raw.githubusercontent.com/minio/operator/master/examples/console-secret.yaml --namespace tenant1-ns
```

## Context
Wanted to create a local tenant for testing out MinIO on my minikube environment.

## Your Environment

* Version used (`minio-operator`):
* Environment name and version (e.g. kubernetes v1.17.2):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your deployment file:

**Comment by Mageswaran1989** [comment]
Similarly `kustomize` command needs build I guess  @ https://github.com/minio/operator/blob/master/docs/examples.md#minio-tenant-with-autocert-tls

`kustomize examples/kustomization/base | kubectl apply -f -` doesn't work.

`kustomize build examples/kustomization/base | kubectl apply -f -` works.

**Comment by Mageswaran1989** [comment]
Any help on setting up MinIO on local machine using minikube ? It was working couple of months back till the version v4.2.5. Today I resumed my hobby project and I tried all three ways Helm, Command Line and Kustomize. One or other error pops up and I couldn't make it to work.

**Comment by harshavardhana** [comment]
> Any help on setting up MinIO on local machine using minikube ? It was working couple of months back till the version v4.2.5. Today I resumed my hobby project and I tried all three ways Helm, Command Line and Kustomize. One or other error pops up and I couldn't make it to work.

Please use https://kind.sigs.k8s.io/ - much better `minikube` is just too heavy and has networking issues all the time.

**Comment by harshavardhana** [comment]
```
~ kind create cluster --config kind.yaml 
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦 📦 📦 📦 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Joining worker nodes 🚜 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊
```
```
~ kubectl minio init
namespace/minio-operator created
serviceaccount/minio-operator created
clusterrole.rbac.authorization.k8s.io/minio-operator-role created
clusterrolebinding.rbac.authorization.k8s.io/minio-operator-binding created
customresourcedefinition.apiextensions.k8s.io/tenants.minio.min.io created
service/operator created
deployment.apps/minio-operator created
serviceaccount/console-sa created
clusterrole.rbac.authorization.k8s.io/console-sa-role created
clusterrolebinding.rbac.authorization.k8s.io/console-sa-binding created
configmap/console-env created
service/console created
deployment.apps/console created
-----------------

To open Operator UI, start a port forward using this command:

kubectl minio proxy -n minio-operator 

-----------------
```

```
~  kubectl get pods -n minio-operator
NAME                              READY   STATUS    RESTARTS   AGE
console-c8d5595dd-szh8c           1/1     Running   0          22s
minio-operator-56fcf88cf6-9dfxd   1/1     Running   0          22s
minio-operator-56fcf88cf6-gpkbs   1/1     Running   0          22s
```

```
~ kubectl logs --tail=1  -n minio-operator minio-operator-56fcf88cf6-9dfxd 
I1113 19:34:47.061590       1 main-controller.go:398] Starting workers
```

**Comment by Mageswaran1989** [comment]
@harshavardhana How to create tenant ? Thanks.

**Comment by harshavardhana** [comment]
> @harshavardhana How to create tenant using YAML files ? Thanks.
> 

Just follow the docs `kubectl minio tenant create --help`

**Comment by Mageswaran1989** [comment]
```
kubectl krew install direct-csi
kubectl direct-csi install --crd
kubectl direct-csi drives ls
kubectl direct-csi drives format --drives  /dev/sda1 --nodes minikube --force
kubectl direct-csi info
```

```

 DRIVE      CAPACITY  ALLOCATED  FILESYSTEM  VOLUMES  NODE      ACCESS-TIER  STATUS        
 /dev/sda1  20 GiB    2.6 GiB    ext4        -        minikube  -            Available     
 /dev/sr0   229 MiB   229 MiB    -           -        minikube  -            Available 

 NODE        CAPACITY  ALLOCATED  VOLUMES  DRIVES 
 • minikube  -         -          -        -    
```

**Comment by Mageswaran1989** [comment]
I had good control on the credentials and storage with YAML. I am lost with the latest changes.
 
```yaml
## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: mozhi
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'mozhi' | base64)
  accesskey: bW96aGk=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'mozhi123' | base64)
  secretkey: bW96aGkxMjM=
---
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
  namespace: mozhi
type: Opaque
data:
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
## MinIO Tenant Definition
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minios3
  namespace: mozhi
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"

## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
## If not specified, the Tenant pods will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler

spec:
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2021-06-17T00-10-46Z
  imagePullPolicy: IfNotPresent

  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio-creds-secret

  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1

      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 4

      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this
      ## Pool.
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

      ## Used to specify a toleration for a pod
      # tolerations:
      #  - effect: NoSchedule
      #    key: dedicated
      #    operator: Equal
      #    value: storage

      ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
      ## eligible to run on a node, the node must have each of the
      ## indicated key-value pairs as labels.
      ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      # nodeSelector:
      #   disktype: ssd

      ## Affinity settings for MinIO pods. Read more about affinity
      ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - hostname1
      #           - hostname2

      ## Configure resource requests and limits for MinIO containers
      # resources:
      #   requests:
      #     cpu: 250m
      #     memory: 16Gi
      #   limits:
      #     cpu: 500m
      #      memory: 16Gi

      ## Configure security context
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000

  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  ## Sub path inside Mount path where MinIO stores data.
  # subPath: /data

  ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
  ## TLS for MinIO Tenant pods. Create secrets as explained here:
  ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  #   - name: tls-ssl-minio
  #     type: kubernetes.io/tls

  ## Enable automatic Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false

  ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
  ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
  s3:
    ## This feature is turned off by default
    bucketDNS: false

  ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
  ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
  ## not provided. DNS name format is *.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []

  ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details.
  podManagementPolicy: Parallel

  ## serviceMetadata allows passing additional labels and annotations to MinIO and Console specific
  ## services created by the operator.
  serviceMetadata:
    minioServiceLabels:
      label: minio-svc
    minioServiceAnnotations:
      v2.min.io: minio-svc
    consoleServiceLabels:
      label: console-svc
    consoleServiceAnnotations:
      v2.min.io: console-svc

  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  # env:
  # - name: MINIO_BROWSER
  #   value: "off" # to turn-off browser
  # - name: MINIO_STORAGE_CLASS_STANDARD
  #   value: "EC:2"

  ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
  ## This is applied to MinIO pods only.
  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  # priorityClassName: high-priority

  ## Define configuration for Console (Graphical user interface for MinIO)
  ## Refer https://github.com/minio/console
  # console:
  #   image: minio/console:v0.7.5
  #   replicas: 2
  #   consoleSecret:
  #     name: console-secret
  #   securityContext:
  #     runAsUser: 1000
  #     runAsGroup: 2000
  #     runAsNonRoot: true
  #     fsGroup: 2000
## Secret to be used as MinIO Root Credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: mozhi
type: Opaque
data:
  ## Access Key for MinIO Tenant, base64 encoded (echo -n 'mozhi' | base64)
  accesskey: bW96aGk=
  ## Secret Key for MinIO Tenant, base64 encoded (echo -n 'mozhi123' | base64)
  secretkey: bW96aGkxMjM=
---
## Secret to be used for MinIO Console
apiVersion: v1
kind: Secret
metadata:
  name: console-secret
  namespace: mozhi
type: Opaque
data:
  ## Passphrase to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_PASSPHRASE: U0VDUkVU
  ## Salt to encrypt jwt payload, base64 encoded (echo -n 'SECRET' | base64)
  CONSOLE_PBKDF_SALT: U0VDUkVU
  ## MinIO User Access Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLEACCESS' | base64)
  CONSOLE_ACCESS_KEY: WU9VUkNPTlNPTEVBQ0NFU1M=
  ## MinIO User Secret Key (used for Console Login), base64 encoded (echo -n 'YOURCONSOLESECRET' | base64)
  CONSOLE_SECRET_KEY: WU9VUkNPTlNPTEVTRUNSRVQ=
---
## MinIO Tenant Definition
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minios3
  namespace: mozhi
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"

## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
## If not specified, the Tenant pods will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler

spec:
  ## Registry location and Tag to download MinIO Server image
  image: minio/minio:RELEASE.2021-06-17T00-10-46Z
  imagePullPolicy: IfNotPresent

  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio-creds-secret

  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
      ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
      ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
      ## Note that the operator does not support upgrading from standalone to distributed mode.
    - servers: 1

      ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
      volumesPerServer: 4

      ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this
      ## Pool.
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

      ## Used to specify a toleration for a pod
      # tolerations:
      #  - effect: NoSchedule
      #    key: dedicated
      #    operator: Equal
      #    value: storage

      ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
      ## eligible to run on a node, the node must have each of the
      ## indicated key-value pairs as labels.
      ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      # nodeSelector:
      #   disktype: ssd

      ## Affinity settings for MinIO pods. Read more about affinity
      ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - hostname1
      #           - hostname2

      ## Configure resource requests and limits for MinIO containers
      # resources:
      #   requests:
      #     cpu: 250m
      #     memory: 16Gi
      #   limits:
      #     cpu: 500m
      #      memory: 16Gi

      ## Configure security context
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000

  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  ## Sub path inside Mount path where MinIO stores data.
  # subPath: /data

  ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
  ## TLS for MinIO Tenant pods. Create secrets as explained here:
  ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  #   - name: tls-ssl-minio
  #     type: kubernetes.io/tls

  ## Enable automatic Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false

  ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
  ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
  s3:
    ## This feature is turned off by default
    bucketDNS: false

  ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
  ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
  ## not provided. DNS name format is *.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []

  ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details.
  podManagementPolicy: Parallel

  ## serviceMetadata allows passing additional labels and annotations to MinIO and Console specific
  ## services created by the operator.
  serviceMetadata:
    minioServiceLabels:
      label: minio-svc
    minioServiceAnnotations:
      v2.min.io: minio-svc
    consoleServiceLabels:
      label: console-svc
    consoleServiceAnnotations:
      v2.min.io: console-svc

  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  # env:
  # - name: MINIO_BROWSER
  #   value: "off" # to turn-off browser
  # - name: MINIO_STORAGE_CLASS_STANDARD
  #   value: "EC:2"

  ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
  ## This is applied to MinIO pods only.
  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  # priorityClassName: high-priority

  ## Define configuration for Console (Graphical user interface for MinIO)
  ## Refer https://github.com/minio/console
  # console:
  #   image: minio/console:v0.7.5
  #   replicas: 2
  #   consoleSecret:
  #     name: console-secret
  #   securityContext:
  #     runAsUser: 1000
  #     runAsGroup: 2000
  #     runAsNonRoot: true
  #     fsGroup: 2000
```
