### ISSUE TITLE
The tenant state is swapping between 'Initialized' and 'Provisioning initial users'

### ISSUE THREAD

**Issue by mdekoster** [minio/operator#903]
## Expected Behavior
The tenant state is 'Initialized' after provisioning the MinIO cluster.

## Current Behavior
The tenant state is swapping between 'Initialized' and 'Provisioning initial users' in seconds. The operator log reports 'Hit conflict issue, getting latest version of tenant' every 10 seconds, but the tenant resource is not changed. 

## Steps to Reproduce (for bugs)
Used Tenant manifest:
```yaml
  kind: Tenant
  metadata:
    name: my-s3
    namespace: test-minio
  spec:
    credsSecret:
      name: my-s3-secret
    env:
    - name: MINIO_BROWSER
      value: "on"
    image: minio/minio:RELEASE.2021-10-27T16-29-42Z
    imagePullPolicy: IfNotPresent
    pools:
    - resources:
        limits:
          cpu: 500m
          memory: 1500Mi
        requests:
          cpu: 250m
          memory: 1Gi
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      servers: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      volumesPerServer: 1
    requestAutoCert: false
```

## Your Environment

* Version used (`minio-operator`): v4.3.4
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.20.6
* Operating System and version (`uname -a`): Flatcar Container Linux by Kinvolk 2765.2.5 (Oklo)   5.10.38-flatcar
