### ISSUE TITLE
Prometheus operator metrics scrape unauthorised

### ISSUE THREAD

**Issue by mpavlovicbb** [minio/operator#909]
Prometheus can't scrape metrics from minio pods.

## Expected Behavior
Metrics in prometheus

## Current Behavior

Error in prometheus is 
`server returned HTTP status 403 Forbidden`

In minio tehe is a log that says there are unauthorised requests.

## Possible Solution

Add in values option for variable MINIO_PROMETHEUS_AUTH_TYPE or,
Set variable to "public" by default.

## Steps to Reproduce (for bugs)

1. prometheus version 2.29.1 installed trough official helm with autodiscovery trough anotations on pods and services
2. minio operator and tenant installed with `values.tenant.metrics.enabled` set to true.

**Comment by anjalshireesh** [comment]
Have you set `MINIO_PROMETHEUS_AUTH_TYPE` to `"public"` in values yaml?
If yes, can you please share the yaml?

**Comment by mpavlovicbb** [comment]
Here it is:

```
tenants:
  - name: <tenant_name>
    namespace: <tenant_namespace>
    pools:
      - servers: 4
        volumesPerServer: 2
        size: 100Gi
        storageClassName: <sc_name>
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: v1.min.io/tenant
                    operator: In
                    values:
                    - <tenant_name>
                  - key: v1.min.io/pool
                    operator: In
                    values:
                    - ss-0
              topologyKey: kubernetes.io/hostname
        resources: {}
        securityContext: {}
    metrics:
      enabled: true
      port: 9000
    certificate:
      requestAutoCert: false
```

In what section `MINIO_PROMETHEUS_AUTH_TYPE` shoud be set?
