### ISSUE TITLE
Design Issue - CRD for Bucket before Tenant

### ISSUE THREAD

**Issue by abdennour** [minio/operator#914]
## Expected Behavior
I would expect to prioritize the design descired in possible solution over design described in the current behavior
## Current Behavior

Tenant CR will create new minIO app, with seperated set of buckets , and sepereated why of AuthN and AuthZ.
However, there is no way to create a Bucket inside this tenant with CR way .

## Possible Solution

```
apiVersion: min.minio/v1
kind: Bucket
spec:
  policyACL: ...
  staticWebsite: true

```
