### ISSUE TITLE
Kubernetes multi-master

### ISSUE THREAD

**Issue by JacopoOrlandini** [minio/operator#929]
## Expected Behavior

Expected to be able to deploy MinIO to Kubernetes Cluster with multi-master configuration. Multi-master configuration is formed by 2 master nodes and 2 worker nodes. Expecting to deploy one single tenant the following configuration: 2 MinIO server and 4 volumes (2x each server).

## Current Behavior

Currently the state of Minio is  `Waiting for MinIO TLS Certificate`

## Steps to Reproduce (for bugs)

1. kubectl minio init
2. kubectl create namespace minio-tenant-1
3. kubectl apply -f storage-class.yaml
4. kubectl apply -f storage-pv.yaml
5. kubectl minio tenant create minio-tenant-1  --servers 2 --volumes 4 --capacity 100Mi --storage-class minio-storage-class --namespace minio-tenant-1

## Context

In a first try, I successfully completed a MinIO kubernetes installation for 1 server only.
Minio-operator is running and healthy: `kubectl get all -n minio-operator`
```
NAME                                  READY   STATUS    RESTARTS   AGE
pod/console-c66f79f9f-v4wfk           1/1     Running   0          22h
pod/minio-operator-75bf6464db-pw9hb   1/1     Running   0          22h
pod/minio-operator-75bf6464db-zhd7z   1/1     Running   0          22h

NAME               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/console    ClusterIP   10.96.238.135    <none>        9090/TCP,9443/TCP   22h
service/operator   ClusterIP   10.106.126.182   <none>        4222/TCP            22h

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/console          1/1     1            1           22h
deployment.apps/minio-operator   2/2     2            2           22h

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/console-c66f79f9f           1         1         1       22h
replicaset.apps/minio-operator-75bf6464db   2         2         2       22h
```
## Your Environment

* Version used (`minio-operator`):
`minio-version` is 4.3.6. Downloaded binary file instead of installing with krew.
* Environment name and version (e.g. kubernetes v1.17.2):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
* Server type and version:
All VMs are provisioned using VMWare with 10Gi and 2-2 (cpu-ram)
* Operating System and version (`uname -a`):
`Linux [name_instance] 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

* storage-class-yaml: 
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
* storage-pv.yaml (ellised)
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: pv-1
spec:
   capacity:
      storage: 100Mi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: minio-storage-class
   local:
      path: /data/export-1
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - worker01
...
Here other duplicate k8s pv for different path and same object for worker02
```

**Comment by dvaldivia** [comment]
I don't think multi-master should affect the operator, if the state is waiting for TLS, the CSR is not getting fulfilled, check the logs of the operator to see if there's any errors, also share the output of `kubectl  get csr` to get a clear understanding of what your CSR are doing, we've seen setups where they don't get fulfilled

**Comment by JacopoOrlandini** [comment]
Seems related to a not found TLS resources for mutual authentication inside the cluster using the auto generated certificate. 
I already tried to edit some configuration but with no success.


Hello with `kubectl get csr`:
```
sysadm@signaler01:~/minio-k8s$ kubectl get csr
NAME                                AGE    SIGNERNAME                      REQUESTOR                                             REQUESTEDDURATION   CONDITION
minio-tenant-1-minio-tenant-1-csr   3m1s   kubernetes.io/kubelet-serving   system:serviceaccount:minio-operator:minio-operator   <none>              Approved,Issued
```

sysadm@signaler01:~/minio-k8s$ kubectl get all -n minio-tenant-1             
```                                                                                 
NAME                        READY   STATUS   RESTARTS      AGE                                                                                                
pod/minio-tenant-1-ss-0-0   0/1     Error    2 (33s ago)   98s                                                                                                
pod/minio-tenant-1-ss-0-1   0/1     Error    2 (36s ago)   98s                                                                                                
                                                                                                                                                              
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE                                                                    
service/minio                    ClusterIP   10.98.163.166    <none>        443/TCP    98s                                                                    
service/minio-tenant-1-console   ClusterIP   10.111.194.212   <none>        9443/TCP   98s                                                                    
service/minio-tenant-1-hl        ClusterIP   None             <none>        9000/TCP   98s                                                                    
                                                                                                                                                              
NAME                                   READY   AGE                                                                                                            
statefulset.apps/minio-tenant-1-ss-0   0/2     98s                                                                                                            
```

sysadm@signaler01:~/minio-k8s$ kubectl logs minio-tenant-1-ss-0-0 -n minio-tenant-1                                                                           
```
ERROR Unable to validate passed arguments in MINIO_ARGS:env+tls://9hsoQgcT7Mm4RDfD3Z2b:iBpwR0uvE9SC385492MfoznZqzoe9ligXFRRBbWL@operator.minio-operator.svc.cl
uster.local:4222/webhook/v1/getenv/minio-tenant-1/minio-tenant-1: Get "https://operator.minio-operator.svc.cluster.local:4222/webhook/v1/getenv/minio-tenant-1
/minio-tenant-1?key=MINIO_ARGS": context deadline exceeded                                                                                                    
```


PS: cluster-signing-cert-file and cluster-signing-key-file are both present in the controller manager.
kubectl get pod kube-controller-manager-signaler01 -n kube-system -o yaml
```
spec:                                  
  containers:                          
  - command:                           
    - kube-controller-manager                                                  
    - --allocate-node-cidrs=true                                               
    - --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf                                                                                     
    - --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf                                                                                      
    - --bind-address=127.0.0.1                                                 
    - --client-ca-file=/etc/kubernetes/pki/ca.crt                                                                                                             
    - --cluster-cidr=192.168.0.0/16                                            
    - --cluster-name=kubernetes                                                
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt                                                                                                  
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key                                                                                                   
    - --controllers=*,bootstrapsigner,tokencleaner                                                                                                            
    - --kubeconfig=/etc/kubernetes/controller-manager.conf                                                                                                    
    - --leader-elect=true                                                      
    - --port=0                         
    - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt                                                                                   
    - --root-ca-file=/etc/kubernetes/pki/ca.crt                                                                                                               
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key                                                                                           
    - --service-cluster-ip-range=10.96.0.0/12                                                                                                                 
    - --use-service-account-credentials=true            
 ```

How can I manage this situation?
If I can provide other documentation feel free to ask.
