### ISSUE TITLE
Remove hardcoded CAFile in prometheus scrape_configs to support custom certs

### ISSUE THREAD

**Issue by harshavardhana** [minio/operator#940]
## Expected Behavior
No hardcoded file instead the scrape_configs should be trusted using the CA trust file for the tenant if custom certs are deployed.

## Current Behavior
Prometheus will not work with custom certs

## Possible Solution
Fix it this line
```
~ git grep -n 'CAFile:'
pkg/resources/configmaps/prometheus.go:95:                                      CAFile: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
```

## Steps to Reproduce (for bugs)
Deploy tenant with a custom certificate managed externally.

## Context
Improve usability of the operator.

## Regression
Do not think so.

## Your Environment
Latest k8s, latest operator etc.

**Comment by harshavardhana** [comment]
This is still an issue.

**Comment by larssb** [comment]
I'm bumping head first into this. When configuring my `minio tenant` v6.0.3 deployed with the `operator` v6.0.3` and setting: `prometheusOperator: true` in the `Helm values` file I see:

- the additional scrape config being created in the _Prometheus_ `namespace` I point to with the `PROMETHEUS_NAMESPACE` env. var.
- however, because: `ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt` is set in the `additional scrape config` and this cert. is not the one to trust ... I use `cert-manager` with a custom CA and issuer.

---

## The end result

I see:

![image](https://github.com/user-attachments/assets/5154d4f8-ef4c-4693-bef0-ab9b5cdf849b)

---

I tried using:

```yaml
  # Configures a Prometheus-compatible scraping endpoint at the specified port.
  metrics:
    enabled: true
    port: 9000
    protocol: http
```

in the `tenant helm values`. This creates scrape annotations on the minio pool pod's. However, as the kube-prometheus-stack setup we use ... we've configured this to support additional scrape confs. or serviceMonitors. The annotations route won't work.

What can I do here?

---

## Tried

Manually manipulating the `additional scrape config` to:

```yaml
- job_name: minio-prod-minio-job
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets:
    - minio.minio-knl-tenant.svc.cluster.local
```

But, that results in:

![image](https://github.com/user-attachments/assets/a5d16d5c-0df4-4f8c-86cc-33deff30bb53)

Which, is fair. As the `MinIO tenant` seems to be configured to need access to metrics over `HTTPS`. I've set `requestAutoCert: false` and provided a cert. with the necessary endpoints on the cert.

---

Any advice here is highly appreciated.

Thank you very much.

**Comment by erhhung** [comment]
I've just hit the issue today and dismayed that no action has been taken to address this in many years.

The `TenantSpec.prometheusOperator` setting should change from being a `bool` to an `object` like this:

```yaml
prometheusOperator:
  enabled: true
  caCertFile: /path/inside/prometheus/container/ca.crt
  metricsPaths:
    - /minio/v2/metrics/cluster
    - /minio/v2/metrics/bucket
```

Which the MinIO Operator would render out into `minio-prom-additional-scrape-config` secret:

```yaml
prometheus-additional.yaml: |
  - job_name: tenant-minio-job-0
    bearer_token: eyJh...
    metrics_path: /minio/v2/metrics/cluster
    scheme: https
    tls_config:
      ca_file: /path/inside/prometheus/container/ca.crt
    static_configs:
      - targets:
          - tenant.minio.svc.cluster.local:443
  - job_name: tenant-minio-job-1
    bearer_token: eyJh...
    metrics_path: /minio/v2/metrics/bucket
    scheme: https
    tls_config:
      ca_file: /path/inside/prometheus/container/ca.crt
    static_configs:
      - targets:
          - tenant.minio.svc.cluster.local:443
```
