### ISSUE TITLE
console-deployment.yaml env indentation is wrong

### ISSUE THREAD

**Issue by frumpleswift** [minio/operator#943]
I believe the indentation in `helm/operator/templates/console-deployment.yaml` is incorrect.

## Current Behavior
The template currently has an indentation of 10

```
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          args:
            - server
          env:
            - name: CONSOLE_OPERATOR_MODE
              value: "on"
                {{- with .Values.console.env }}
                {{ toYaml . | nindent 10 }}
                {{- end }}
          resources:
```
This will render additional env variables at the `env:` level resulting in invalid yaml:

```
env: 
  - name: CONSOLE_OPERATOR_MODE
    value: "on"
- name: some_value
  value: some_value
```
This results in errors when deploying with custom env settings.

## Expected Behavior
The template should render valid yaml.

## Possible Solution
I believe the proper value is 12:

```
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          ports:
            - containerPort: 9090
              name: http
            - containerPort: 9443
              name: https
          args:
            - server
          env:
            - name: CONSOLE_OPERATOR_MODE
              value: "on"
                {{- with .Values.console.env }}
                {{ toYaml . | nindent 12 }}
                {{- end }}
          resources:
```

## Steps to Reproduce (for bugs)
1.  Attempt to deploy the minio operator via helm with the following values:
```
operator:
  image:
    repository: redacted
    tag: v4.3.8
console:
  image:
    repository: redacted
    tag: v0.13.1
  env:
    - name: MINIO_IDENTITY_OPENID_CONFIG_URL
      value: redacted
    - name: MINIO_IDENTITY_OPENID_CLIENT_ID
      value: minio-operator
    - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
      value: redacted
    - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
      value: redacted
```

## Context
I cannot provide custom environmental variables to the Minio Operator Console, which prevents SSO configurations.

## Your Environment
* Version used (`minio-operator`): 4.3.8
* Environment name and version (e.g. kubernetes v1.17.2): kubernetes v1.20.4
