### ISSUE TITLE
[v4.4.1] Operator deployment rendered incorrectly in helm chart

### ISSUE THREAD

**Issue by trexx** [minio/operator#960]
## Expected Behavior
Properly rendered helm chart

## Current Behavior
```
      containers:
        - name: operator
          image: "minio/operator:v4.4.1"
          imagePullPolicy: IfNotPresent
          env:

          Capabilities:
            APIVersions:
            - v1
            - admissionregistration.k8s.io/v1
            - admissionregistration.k8s.io/v1beta1
            - internal.apiserver.k8s.io/v1alpha1
            - apps/v1
            - apps/v1beta1
            - apps/v1beta2
            - authentication.k8s.io/v1
            - authentication.k8s.io/v1beta1
            - authorization.k8s.io/v1
            - authorization.k8s.io/v1beta1
            - autoscaling/v1
            - autoscaling/v2beta1
            - autoscaling/v2beta2
            - batch/v1
            - batch/v1beta1
            - certificates.k8s.io/v1
            - certificates.k8s.io/v1beta1
            - coordination.k8s.io/v1beta1
            - coordination.k8s.io/v1
            - discovery.k8s.io/v1
            - discovery.k8s.io/v1beta1
            - events.k8s.io/v1
            - events.k8s.io/v1beta1
            - extensions/v1beta1
            - flowcontrol.apiserver.k8s.io/v1alpha1
            - flowcontrol.apiserver.k8s.io/v1beta1
            - networking.k8s.io/v1
            - networking.k8s.io/v1beta1
            - node.k8s.io/v1
            - node.k8s.io/v1alpha1
            - node.k8s.io/v1beta1
            - policy/v1
            - policy/v1beta1
            - rbac.authorization.k8s.io/v1
            - rbac.authorization.k8s.io/v1beta1
            - rbac.authorization.k8s.io/v1alpha1
            - scheduling.k8s.io/v1alpha1
            - scheduling.k8s.io/v1beta1
            - scheduling.k8s.io/v1
            - storage.k8s.io/v1beta1
            - storage.k8s.io/v1
            - storage.k8s.io/v1alpha1
            - apiextensions.k8s.io/v1beta1
            - apiextensions.k8s.io/v1
            HelmVersion:
              git_commit: 663a896f4a815053445eec4153677ddc24a0a361
              git_tree_state: clean
              go_version: go1.16.10
              version: v3.7.2
            KubeVersion:
              Major: "1"
              Minor: "22"
              Version: v1.22.0
```

## Possible Solution
https://github.com/minio/operator/blob/v4.4.1/helm/operator/templates/operator-deployment.yaml#L47
`{{- if .Values.operator.env }}`
should be
`{{- with .Values.operator.env }}`

Due to the error its printing out chart root and not from .Values.operator.env

## Steps to Reproduce (for bugs)
My values.yaml
```
operator:
  env:
    - name: WATCHED_NAMESPACE
      value: "minio-infra"
```
` helm template .`

## Context
Unable to upgrade helm charts and likely others maybe unable to deploy it

## Regression
Don't think so

## Environment
Operator Helm Chart Version:  v4.4.1
