### ISSUE TITLE
Refactor tenant helm chart to deploy and manage only one tenant

### ISSUE THREAD

**Issue by dnskr** [minio/operator#981]
**Is your feature request related to a problem? Please describe.**
In release v4.3.8 `minio-operator` helm chart has been split into `operator` and `tenant` charts.
Current `tenant` chart implementation allows to deploy and manage several tenants at the same helm release.

It would be clearer and more useful to change it to deploy only one tenant per helm release:
1. The use case when it's needed to control a few tenants per one release is not clear
2. Currently it's possible to specify a secret to create within tenant definition in the chart, but it's not a part of tenant CRD
```
  - name: minio1
    # pool secrets
    secrets:
      # create a kubernetes secret object with the accessKey and secretKey as defined here.
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
```
3. With one tenant per helm release it would be easier to add more functionality/features/resources to tenant helm chart, for example:
        - add Ingress for tenant console
        - add init Job
        - add periodical CronJob
        - etc

**Describe the solution you'd like**
Refactor helm chart to deploy only one tenant object and move non-tenant fields outside of tenant definition, i.e. replace
```
tenants:
  # Tenant name
  - name: minio1
    namespace: default
    # pool secrets
    secrets:
      # create a kubernetes secret object with the accessKey and secretKey as defined here.
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
	...
```
with
```
tenant:
  # Tenant name
  name: minio1
  namespace: default
  ...

# pool secrets
secrets:
  # create a kubernetes secret object with the accessKey and secretKey as defined here.
  enabled: true
  name: minio1-secret
  accessKey: minio
  secretKey: minio123
```

**Describe alternatives you've considered**
Custom tenant helm chart can be created and used instead.
